In [127]:
import torch
import torch.nn as nn
import torch.optim as optim
import random
import matplotlib.pyplot as plt

In [128]:
# #!/bin/bash
# !kaggle datasets download preetviradiya/english-hindi-dataset

In [129]:
# !unzip english-hindi-dataset.zip

In [130]:
import pandas as pd

In [131]:
df = pd.read_csv("Dataset_English_Hindi.csv")

In [132]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 130476 entries, 0 to 130475
Data columns (total 2 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   English  130474 non-null  object
 1   Hindi    130164 non-null  object
dtypes: object(2)
memory usage: 2.0+ MB

In [133]:
df.head()

  English    Hindi
0   Help!    बचाओ!
1   Jump.    उछलो.
2   Jump.    कूदो.
3   Jump.   छलांग.
4  Hello!  नमस्ते।

In [134]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 130476 entries, 0 to 130475
Data columns (total 2 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   English  130474 non-null  object
 1   Hindi    130164 non-null  object
dtypes: object(2)
memory usage: 2.0+ MB

In [135]:
df["English"] = df["English"].str.lower().str.split()
df["Hindi"] = df["Hindi"].str.split()

In [136]:
df.head()

    English      Hindi
0   [help!]    [बचाओ!]
1   [jump.]    [उछलो.]
2   [jump.]    [कूदो.]
3   [jump.]   [छलांग.]
4  [hello!]  [नमस्ते।]

In [137]:
df["Hindi"] = df["Hindi"].apply(
    lambda x: ["<start>"] + x + ["<end>"] if isinstance(x, list) else ["<start>", "<end>"]
    )

In [138]:
df.head()

    English                      Hindi
0   [help!]    [<start>, बचाओ!, <end>]
1   [jump.]    [<start>, उछलो., <end>]
2   [jump.]    [<start>, कूदो., <end>]
3   [jump.]   [<start>, छलांग., <end>]
4  [hello!]  [<start>, नमस्ते।, <end>]

In [139]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 130476 entries, 0 to 130475
Data columns (total 2 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   English  130474 non-null  object
 1   Hindi    130476 non-null  object
dtypes: object(2)
memory usage: 2.0+ MB

In [140]:
df_subset = df.head(20000)

In [141]:

df_subset = df_subset.dropna(subset=['English', 'Hindi'])

vocab_english = []
for i , sentance in enumerate(df_subset["English"]) :
  if isinstance(sentance, list):
    vocab_english.extend(sentance)

vocab_english = list(set(vocab_english))
vocab_english = ["<PAD>" , "<UNK>"] + vocab_english
print(f"English Vocab Size: {len(vocab_english)}")

English Vocab Size: 33089

In [142]:
vocab_hindi = []
for i , sentance in enumerate(df_subset["Hindi"]) :
  vocab_hindi.extend(sentance)

vocab_hindi = list(set(vocab_hindi))
vocab_hindi = ["<PAD>" , "<start>" , "<end>"] + vocab_hindi
print(vocab_hindi)
print(len(vocab_hindi))

['<PAD>', '<start>', '<end>', 'तरह-एकल', "they're", '1914', 'संक्रमित', 'है-उसे', 'भूमि', 'दुर्घटनाओं', 'मंड़पम', 'बन्ने', 'मेलाइक', 'कोट्टु', 'विद्युत-आपूर्ति', 'रणनीतिकार', 'अमरीकी', 'सेकडों', 'गीली,', 'समस्योओं', 'न?”', '(biological', 'ड़ी.वूल्फेनसोन', 'सामंती', 'नाविक', 'अधिमिश्रण', 'यादृच्छिक', 'एपीजे', 'खानदानी', 'वाहिनी', 'वऋ-ऊण्श्छ्ष्-यतीत', 'द्विभाषीय', 'खिलाये', 'पुष्पिकाएं', 'जला', 'किसको', 'ज्ञानांकुर', 'शांतनु', 'हेटेरॉप्टेरा', 'बेशुमार', 'चढ़े', 'अपर्याप्तता', 'मापन', 'उठा', 'गड्डिंयां', 'डोंब', 'गुंथे', 'भविषऋ-ऊण्श्छ्ष्-य', 'घेरा', 'पांचवें', 'हड्डियां', 'कोंड़ोलीज़ा', 'बट', 'कताई', 'बढ़ना', 'क़दमों', 'मुग़ल', 'नागिदेव', 'मिलेंगे।', 'संकल्पों', 'उड़ातें', 'चुम्बकीय', 'मुकझा', 'हिमनदों', 'मुखों', 'Ka%aa', 'वाकर', 'Anthropogenic', 'चालुकयों', 'आलकमान', 'क्षतिग्रस्त', 'है.धीरे', 'केशे', 'फूंकने', 'चालुक़्यों', 'चौबीस', 'छू', 'केद्रित', 'नादुरूस्त', 'सिलसिले', 'सेनापतियों', 'अभिव्यक्तियां', 'सुनिए,', 'हो.', 'अध्यापक', 'सा', 'वाशिंगटन', 'कोमपीनयों', 'उल्फा', 'DEFRA', 'भारीमात्रा', 'दिखता', 'चौंतीस', '(अमेरिका)', 'हैल्थ', '(VSNL)', 'हेल्थ', 'है,”', 'प्राणियों', 'पिता.', 'सव्Mय', 'मब(1गिगाब्य्ते', 'अZवधि', 'प्रजातान्त्रिक', 'करेंगे/करेंगी', 'model)SRES', 'सिखाया', 'मानना', 'काई', 'राजनीती', 'आवश्य', 'लगाकर', 'नियो>आ', 'मिल', 'निकोबार', 'लाया', 'रीफ', 'व्यवसायिक', '01772', 'ड़ाले', 'प्रासादों', 'नांमाकित', 'समरू', 'पुनरीक्षा', 'शिष्टमंडल', 'ब्राह्म', 'कैरी', 'प्रमाणों', 'रुचिकारक', 'अनुन्मोचित', 'गिरावट', 'रुपए', 'ख़रीदे', 'ज्योतिरीन्द्रनाथ', 'औरतों', '४०', 'माडगूळकर', 'सुनाई', 'असावधानी', '\u200eमिलेगा', '1874', 'ध्वनि-विस्तारक', 'णो', 'किशोर', 'आत्मचरित्र', 'ष्ह्-', 'मूलतत्व', 'AiQakar', '(Lead)', 'पत्रकार', 'क्लिंटन', 'श्रीनगर', 'उल्लेखनीय', 'सहभागी', 'समूहन', 'बक-बक', 'kiryaalaa', 'बरसों', 'बहेलिये', 'घेटालों', 'है-क्योंकि', 'ग्रहणशील', 'चोटें', 'प्रण', 'ग्रीष्मावकाश', 'वितरण', 'टेबल्स', 'सचिवालयों', 'छल', 'हेरात', 'संभवत', 'नहंईं', 'आज्ञाकारी', 'पाना।', 'कीटों', 'भेजे.', 'उद्धेश्य', 'मारिजुआना', 'आप्रावासिय', 'नवनिर्मित', 'साजो', 'जालिका', 'शद', 'जूड़े', 'बसु', 'बहुतों', 'उपलब्धियॉ', 'मित्तर', 'गुजराती', '0-470-85100-7', 'अतएव', '१५', 'कड़े', 'ईरान', 'दी।', 'अग्रवन', 'जरा', 'चिंताएं', 'शाहजहां', 'इंटर', 'स्वतः', 'माकपा', 'पीढऋई-दर्रपीढऋई', 'कानूनत', 'भूकंप', 'वा', 'ऐतिहासिक', 'मान्टेस्कयू', 'कर्हा', 'मुश्किलं', 'कन्सल्टेन्ट', 'कलश', 'Electric', '(१९९८', 'कोलाबा', 'उम्मेद', 'राहदारी', 'दीजिये', 'समज्हैते', 'अनोखा', 'कटवाना', 'ढंके', 'गाना', 'लीलावती', 'जकड', 'मिगर', 'टेम्पल', '1162', 'नागराज', 'आआ', 'वैसी', 'दालान', 'सिन्डिकेशन', 'वागीश्वरम', 'उलऋ-ऊण्श्छ्ष्-टे', '208', 'खोलिए।', 'कोलम्बो', '१-डी।', 'पुस्तिकाओं', 'महामण्डलेश्वर', 'भातीय', '(revolutionary)दृष्टिकोण', 'जमा', 'सामानऋद्दय', 'ग्रान्ट', 'घोड़े', 'रिटर्न', 'अलविदा', 'क़्लर्क', '!!', 'प्रर्वतक', 'निर्भर', 'ऋन', 'व्याकरणिक', 'अनुपस्थित', 'अग्रत्वचा', 'लक्ष्मी', 'तत्पश्चात', 'संलगऋ-ऊण्श्छ्ष्-न', 'थी?', 'पूर्व)', 'दिया!', '61', 'जहर', 'पाठक', 'कोटे', 'bahut', 'दुर्बलों', 'फ़्रांसीसी', 'उपलइधयों', 'एड़ीए', 'कमेंटों', '(atmosphere)', 'घरवालों', 'संबंद्ध', 'मृतक', 'रिंसेज़', 'मलिन', 'आरती', 'पुनरूद्धार', 'समकक्ष', 'समज्ह', 'इन्हेरिटेंस', 'प्रभुसत्ता', 'कवियुर', 'स्वादिष्ट', 'पत्थर', 'अफ्रिका', 'निरसन', 'विक्टोरिया', '/सोफा/टेबल/काउंटर', 'प्रेरणास्रोत', 'स्त्राव', 'प्राणिशास्त्र', 'मोड़ा', 'जेल-अधीक्षक', 'तौलते', 'पादप-रोम', '३-४', 'साधू-संतों', 'सिक्किम', 'प्रतीक', 'म्युज़ियम', 'पाचेलबेल', 'उदाहरण:', 'मुख्यत:', 'ना?', 'sana', 'बेकार', 'ईमानदारी', 'पंखों', 'अवैद', 'स्लेटी', 'अनु', 'बांटा', 'पहेले', 'दें', 'विजयवाड़ा', '(सामान्य)', 'माँगे।', 'देंजिंग', 'दर्शन-जिन्हें', 'दण्ड', 'भुजाओं', 'चूनीं', 'Bruno)आधारित', 'जिमखाने', 'मृदंग', '(विकिस्रोत', 'चपटा', 'फलोद्यान', 'चेचेन्या', 'गोरे', 'गुनी', 'तनों', 'जे-ज़ी', '४००,०००', 'बर्बाद', 'प्रयोजन', 'निकासी', 'बनावटी', 'रही।', 'प्रचलन', 'मामलों', 'होता.', 'principle)', 'व्यक़्ति', 'खोलता', 'सेवानिवृत्ति', 'थोडी', 'ट्यूबरकुलोसिस', '१८००', 'ऐश्वर्या', 'खरीदा', '4490', 'छ्ल', 'मि०', 'अनुपचारित', 'लेखिका', 'India', '(2000).', 'दिलाया', 'आतऋ-ऊण्श्छ्ष्-मनिर्भरता', 'सम्मोहक', 'विठ्ठल', 'परिशोधन', 'अ-धम्म', 'मण्डी', 'अंडकवच', 'कडियों', 'हैं-तो', 'अंबार', 'ह्यमीजल्सहृ', 'मैनेस्टर', '.वे', 'raja', 'दुखाने', 'Defense)', 'बहानों', 'उकरा', 'प्रतिबोध', 'साझेदारों', 'कूड़े', 'कल्लमथड', 'मसनवी', 'Aproch', 'ड़्राइंग', 'रसद-मदद', 'बेसेन्ट', 'मांगो', '(water', 'मोनस्टर.कॉम', 'आएँगे', 'चाहूंगी', '“जूता”', 'उपजीवियों', 'तबसे', 'स्थल)', 'तूफान', 'शस्त्रज्ञ', 'था।', 'किंवदन्ती', 'अनुच्छेद', 'तापमान', '(अंग्रेज़ी', 'विपरीत', 'विलोपन', '(अभिव्यक्ति', '२१२', 'हाफिज', 'स्पाइरल', '२)', 'जिमी', '53हृ', 'गया.संतों', 'वक्ररेखी', 'सत्याग्रह', 'कऋ-ऊण्श्छ्ष्-वालिटी', 'सुनवाई', '............', 'बैटरियां', '1950-95', 'व्यि>गत', 'पेड़-पौधों', 'कैरियर', 'चनिया', '(London', 'कार्यऋमों', 'साऊथ', 'वर्णक्रम', 'कुन्नातुर', 'बाँधती', 'दोषी', 'पॉ', 'अंकीय', 'prMpra', 'थी.इनमें', 'है.अस्थियां', 'गुलबर्गा', '६०', 'साधुमना', 'किल्लरी', "लक्ष्मण'", 'केआक्रमण', 'करर्य', 'लिंक्स', 'ज्यॉफ', 'ललकृष्ण', 'Motorola', 'दौड़ना', 'शि>यां', 'प्रखर', 'भूवैज्ञानिक', 'धक़्का-मुक़्की', 'रातभर', 'भंग', 'जनमत', 'कमरा', 'अंतरिक्ष', 'सार्वलौकिक', 'परिपक़्व', '568-488', 'यूएस-64', 'सुंदार', 'तभी', 'एकाश्म', 'ऋब्रह्मसिद्धांतऋ', 'नेपाल)', 'करुण', 'असमानताएँ', 'पैसे', 'बम्बई', '(', 'कावूरी', 'कॉन्फेडरेशन)', 'नेतृत्व', 'विशऋ-ऊण्श्छ्ष्-वास', 'विकरण', 'भेड़', 'कैमेरून,', 'देखबाल', 'पुनर्व्यवस्थित', 'दिसंबर', 'आनलाइन/आफलाइन', '(socioeconomic)', 'व्यतीत', 'नियुक़्ति', '49', 'तोकियो', 'सूखे', 'मंशा', 'खलीफा', '4.10', 'modalities', 'लौटता', 'बुनाई', '(non-combatant)एसकुछ', 'स्टेटमेंट', 'वार्णावत', 'आऊंगा।', 'कटोरा', 'कॊ', 'एकता', 'ऑक्सफ़र्ड', 'वैबसाईट', 'रेडियोधर्मी', '।', 'कहूँगा', 'पत्रों', 'उपपत्ति', 'थानों', 'जगाने', 'वकीलों', 'निवासों', 'पकड़कर', 'रिपब्लिकन', 'रहा/रही', 'नाजिज़्म', 'कुंजों', 'गैलन', 'वॉयेजर', 'अलीसियम', 'यह', 'बने', 'चमत्कारी', 'सत्ताएं', 'कंट्रोल', '(bog)में', 'खायी', 'जोकि', 'सॉम', 'निरोधक', 'उद्योगीकरण', 'ह्यवऋ-ऊण्श्छ्ष्-यापकताः', 'जलयान', 'छूटी', 'देखा।', 'प्रदर्शन-शृंखलओं', 'अंगरक्षक', 'संपर्क', 'मंगलनी', 'पहाड़ियों', 'हत्थाकुर्सी', 'बढाने', 'ङ्', '“बंग', 'टूट-टूटकर', 'राष्ट्रों', 'तालमेल', 'एंगेल', '(deficit)', 'स्मिथसोनियन', 'कार्याक्षेत्र', 'मोर्चे', 'फार्मलडिहाइड', 'जन-समदाय', 'नेत्र', 'जातिप्रथा', 'आविष्कार', 'कोडोन', 'पूर्व,', 'कहकर', 'येरुसलम', 'कार्यकारी', 'सहयोगपूर्ण', 'समन्वित', 'लागू', 'जेसन,', 'अनुप्रस्थ', '(तालियाँ)', 'चाहे', 'जीवन-वर्ष', 'श्रमिक', 'मई', 'कश्मकश', 'वि०)', 'भाँगा', 'उत्पीड़ित', 'हास्यापद', 'देशवासी', 'रोयप्पा', 'तारदी', '\u200eधरती', 'क्रम-विक्रम', 'कांच', 'लिए)', 'पाठक:', 'प्रभुसत्तारहित', 'देक्र्यप्तिंग', 'जीवन्तता', 'गिरने', 'बदलते', 'भीमगोडा', 'करो!', 'भोजपुरी', 'खोलो।', 'रंग-बिरंगा', 'राज़्यों', 'पार्टी-संयुक़्त', 'मोडता', 'फोम', 'चरण-', 'लोमड़ी', 'वाटसन', 'पढ़ाकू', 'पाण्डवपक्षिय', 'लाभांश', 'चरितार्थ', 'आनुवंश', 'निद्रा', 'उत्पZत्ति', 'आज़मा', '(आवर्धन', 'पर्यटक', 'सोना', 'शेक्सपियर', 'Zअर्थ', 'पदार्थवादी', 'जीव-जंतुओं', 'समझर', 'आओ', 'समाज-शास्त्र', 'काँग्रेस', 'उतारने', 'बुरहानुद्दीन', 'भुगतान-जब-तुम-जाओ', 'सूबेदार', 'तोड़ी', 'कच्छ', 'जन्मोत्सव', 'अलंऋत', 'दर्शकों', 'पायी', 'एजुकेशनल', 'स्याही', 'कैजन', 'शृंखल', 'प्रोटेक़्शन', 'लन्दन', 'मनोदशा', 'लॉस', 'कॉलिंग', 'चिरंतन', 'or', 'लछमणसिंह', 'वीसदी', 'भाई', 'बंगलौर', 'शिक्षाप्रद', 'बचाने', 'हैं-अशरीररी', 'थी.बचे-खुचे', 'किसीप्रकार', 'उतार-चढाव', 'रुकना', '(1943)', 'दिलाकर', 'व्यक़्तिनिष्ठ', 'वाटरलू', 'बहुर्तसे', 'पड़ेगा।', 'यॉर्कशायर', 'खंखारकर', 'नेताजी', 'PBSसीमावर्तीअक्तूबर', 'ठहरकर', 'तरंगे', 'अमीरात', 'लतपत', 'सहित)', 'गुणसेन', 'टूरिज्म', 'लडऋखडऋआते', 'निर्धारक', 'पेज', 'मोड़ो', 'चिन', 'उपाख्यानों', '::', 'बादल', 'वसल्लमका', '1998', 'स्मृतियों', 'बर्रेट', 'भौतिकता', 'औरेकल', 'बचाली।', 'दिया,', 'आइएल-76', 'माँगा.', 'Zतक', 'भावुकतापूर्ण', 'बंगदर्शन', 'बेहद', 'बजाये', 'प्रावघान', 'कथनी', 'सैकड़ों', 'आदार्नप्रदान', 'मिट्टीं', 'शिकायतें', 'शिवसुख', 'प्रविष्टियों', 'गर्भनिरोधक', 'कांड', 'यहीं', 'उमंग', 'ठ्-ऊण्श्छ्ष्-रडिन्ग्हृ', 'एसोसिएशन', 'ज़मीन', 'प्रशेषनीय', 'बीआइएफाअर', 'काश्मीर', 'ब्रह्मगुप्त25', 'कृष्णचंद्र', 'कि।', 'उम्मीदों', '(other', 'निर्वस्त्र', 'प्रद<a', 'आदेश-निर्देश', '01624', 'धनंजय', 'लुटेरों', 'सट्', 'छोडा,', 'संषेचित', 'संवेदना', 'पुता', 'पल्लवों', 'किन्हें', 'ब्रौन', '1947', 'संघों', 'डुबा', '(हाल', 'करूँ.', '८०००', 'तंत्रिकीय', 'महान्यायवादी', 'लड़ेकियों', '60', 'मानव-निर्मित', 'व्यहवार', 'denominators', 'लेर्खानियंत्रक', 'गठन', '(Run', 'अनुभूतियों', 'ढर्रे', 'एंग्लो-इंडियन', 'उप-चुनावों', 'छुट्टियां', 'उदाहरणार्थ', 'निस्संगता', 'युक्तियां-', 'फिरोज़', 'दर्जे', 'ऐक्सक्लूज़न', 'दर्शाया', 'आधी', 'यड़', 'कालखंड', '१९६५', 'विवादों', 'पंक़्तियां', 'स्पष्ट', 'भारोत्तएलन', 'अथर्ववेद', 'रहेनगोल्ड', 'विवाहित', 'सेक़्शन-के', 'भेजें', 'सार्वजनिक़', 'कर्मचारीवृंद', 'राजपूताने', 'पाएगा।', 'वट', 'ओह', 'विमानक्षेत्र', 'कर्जन', '38%', 'मज़ेदार', 'रॉकेट', 'तुड़ि', 'सगोत्री', 'पेपल', 'नाव', 'शिवगय्यां', 'नरेंद्र', 'अभिकरणों', 'विवेकपूर्ण', 'पढ़ाया', 'मतलब,', 'चारे', 'एहसानमंद', 'अधिवृषण', 'वेदों', 'वाड़िया', 'यूएनपी', 'कार्टूनिस्टों', 'पारिभाषिक', 'मुरारीपुकर', 'तीनों', 'आदित्य', 'समीकरण', 'आजीवन', 'छोते', 'तल-प्रक्षिप्त', 'वर्णमाला', 'कायिक', 'अलीगढ', 'सीध', 'खरीदी', 'न्यूरोपेथी', 'जनमेजय', 'अनौपचारिक', 'गीतों', 'हस्त', 'है.इसका', 'बिम्बसार', 'आलोचक', 'अव्वल', 'पराया', 'शहादत', 'द्वीर्पसमूह', 'तक-क्रम', 'बधाई', 'वित्तपोषण', 'निर्णायक', 'ठेस', 'रही', 'हद', 'उपाधऋ-ऊण्श्छ्ष्-यक्ष', 'बल्ला', 'विभावती', 'धाराओं', 'जुर्रत', 'पशऋ-ऊण्श्छ्ष्-चिम', 'हिंदू-मुस्लिम', 'कमजोर', 'क्लेरमोंट', 'आरएसएस', 'पाण्डव', '39.4', 'गया.बाद', 'मनोभावों', '1,100', 'मेहराब', 'सर्वोच्चस्तरीय', 'काव्य', 'बेहोश', 'स्थूल', 'संशोधनों', 'होनेवाले', 'बहरे', '‘प्रेम', 'भरतनाट्यम', 'विल्कुल', 'samaoM', 'वैविध्यकरण', 'कली', 'खद्य', 'सोवरिंउटी', 'भतीजे-भांजो', 'बनवा', 'Gandhi', 'औसतन', 'क्लीनिकल', 'मसौदा', 'फोर्स', 'सीलन-भरी', 'साढै', 'भंडार', 'दीं।', 'त्Lतलियां', 'जरुरी', 'बल्लेबाजों', 'पऋधे', 'मैं।', 'परिणामस्वरुप', 'विशेषरुम', 'थे.संपनऋ-ऊण्श्छ्ष्-न', 'extreme', 'प्रशस्त', 'परमिटस', 'बरसात', 'बाइस', 'शीत', 'फट', 'मीडियम', 'थैली', 'हयात', 'राजेन्द्र', 'समझता', 'इसीलिए', 'Council', 'बदलवाना', 'सकी।', '(pornography)', 'दुष्प्रभाव', '२९३३', ']', '[1571]', 'Apte)', 'America)', 'में.', 'Protocol)पर', '(possible', 'की-जहां', 'नोटों', 'सेवक', 'पुणे.', 'द्वार्रद्वार', 'इंद्रधनुष”', 'सोसइटी', 'पाले', 'साम्राजयवाद-विरोधी', 'दुर्गति', 'फॉर', 'विषयवस्तु', 'बंजारे', 'अक्षर', 'भग़्नावशेष', 'पैकेट', 'अटकलबाजियों', 'सिक़्के', 'फ्राई', 'विंड़', 'स्पा', 'ऑटोरिक्शा', 'baD', 'नापसंद', 'छेदक', 'सकने', 'परिसंघात्मक', 'कोपनहेगन', 'परिष्कृत', 'विधिमान्य', 'चलाता', 'भाषण', 'तबाह', 'कोटेशन', 'vaalaa', 'प्रकटत', 'छोटे-बड़े', 'ऐइस', 'इण्डस', 'सर्वदल', 'तल्ले', 'नजदीकी', 'हृदयस्थल', 'शल्क', 'असरे', 'चूहा', 'खेद', 'बढ़ते', 'सयता', 'अाने', 'बहुदेववाद', 'ह्क्का', 'हृदय-से-हृदय', '519', 'क़्विलन', 'हुजूरी', 'टीटो', 'हैं.आउट', 'एसबेस्टोसिस', 'अवैध', 'हेरफेर', 'दोपहिया', 'ऊल', 'शिल्पकला', 'भट्टं', 'बैठता', 'बुद्ध्', 'बेरूत', 'करनाल', 'वार्ड़न', 'रेलवे', 'पांडिचेरी', 'निरा', 'खामी', 'guitar)वीडियॊ', 'थे.', 'झूठा', 'बानो', 'पत्नीरूप', 'टहिलियाणी', 'ऊंघते', 'बोल्डर', 'मातृहीन', 'फलोद्यानों', 'हिस्टिरिकल', 'चढ़ते', 'काम-क्रियाएं', 'तत्परता', 'मुद्र्ण', 'एड्स.सेल', 'वीर्य', 'अ्धेडावस्था', 'माउथवाश', 'सविता', 'ईंटरनेट', 'ऋषि-मुनियों', '==', 'ऑर्डर', 'बड़ै-बड़ै', 'पंजों', 'सकती।', 'दुष्टता', 'सरोजिनी', 'साधु-संतों', 'नाज़-ए-हिन्द', 'ग्वाडालूप', '(Charles', 'सौफ़्ट्वेयर', 'सुनाइये', 'आत्मकेंद्रित', '1882', 'दावेदार', 'सुविधाओं', 'वंश', 'एलम्हर्स्ट', 'उपचिर', 'भरे', 'लनी', 'पूर्वद्रष्ट', 'तांडव', '(हालांकि', 'भाग-', 'जैसे-जैसे', 'विकृति', 'शौक', 'सिक़्किम', 'हिजरी', 'राजनयिक', 'किलिक्ति', 'प्रान्त', 'अमानवीय', 'authenticity', '21870', 'स्वघोषित', 'अनिस्चित', 'कार्सिनोजेन', 'रूमी', 'लिबरेशन', 'पक्षो', 'समस्यायें', '%).उस', 'चेम्सफोर्ड', 'हल्लय्या', 'वोडगिना', 'इक्विपमेंट', 'उत्तर-पश्चिमी', 'ट्रिब्यून', 'फैसलों', 'रंगीन', '‘द्विवेदी', 'कमजोरियों', 'ऊंटनियों', 'रोकूँगी?', 'वाणी', 'जहन', 'मांग', 'जल्दबाजी,', 'सवार', 'बदरूद्दीन', 'कर्मचारियॊं', 'सूचित', 'मुद्रक:', '712', 'यथार्थ', 'बनी.', 'अवतार', 'कोका', 'रास', 'देवता', 'मैसूर', 'विकास;', '20-25', 'आबाद', 'पोस्टिंग', 'जोधा-अकबर', 'पूंजीपति', 'बाल्को', 'चलाऋ', 'रविल्ला:', 'कहने', 'चार-पांच', 'अग्रकय', 'अम्लों', 'कर्णाली', 'गंधहीन', 'तोह्फ़ा', 'धुधली-सी', 'स्वार्थ', 'आखो', 'फैले', 'जन्में', 'अच', 'छोड़ते', 'book)', 'अहोरात्र', 'मकबरा', 'बहुभुज', 'उद्योगपपियों', 'अमिश्रित', 'परशुराम', 'बौद्धों', 'पूर्वावलोकन', 'Zबस्तियों', 'मैनचेस्टर', 'फिल्मफेयर', '(२००९', 'वंशवाद', 'ट्राट्सकी', 'घटी', 'कैनबिस', 'अन्तक', 'सामान्यरुप', 'become', 'फरेन्ट्', 'इंडिया-', 'त्रुटियां', '190', 'सख्त', 'स्टीक', 'जुर्माने', '1005', 'दृढेता', 'प्रभावों', '६१०', 'लक्ष्मीनारायण', 'गिर', 'वितान', 'हक,दार', 'पिछड़े', 'आ-जा', 'रक्षोपाय', 'सैय्दों', 'हैम्ब्लडन', 'तिलावत', 'गये', 'स्तभों', 'appeals', 'यूनाइटेड', 'झुकी', 'व्यक़्तिगत', 'संचार:', 'एटलस', 'आर्थर', 'गाड़ियों', 'इत्यादि', 'आने', 'कठिन', 'हिंसायाम', '|भाष्', 'छलांग.', 'चाहूँगा।', '?', 'टोयोटा', 'मैकाले', 'गोलकनाथ', 'अलग,', 'असंवैधानिक/रद्द', 'प्राणदान', 'उत्साहवर्धक', 'सुबह', 'कराती', 'मौंकों', 'विरक्त', 'पटेल', 'ज्हेंपड़ें', 'साफतौर', 'हौए', 'ऋआंति', 'निलंबित', 'also', 'पासऋठोस', 'सांचे', 'action', '9000', 'कणिका', 'शारदाश्रम', 'रूपरेखाएं', '117.8', 'थोपा', 'घटनाएं', 'बुद्घि', '[बदलाव', 'गया.यह', 'पहले.', "एक्ट'", 'कि', '(hostage)s', 'पहाडियों', 'सवालात', 'क्रियाशील', 'निस्संदेह', 'निपुण', '1602', 'जळ', 'धनी', 'घ्येय', 'हिल', 'अखंडता', 'सर्विसिज़', 'पछ', 'कोर्टहृ', 'अक्षुण्य', 'ताकतों', 'विक्रम', 'बारे,', 'वाल', 'लेती', 'साफ़्टवेयर', 'काटा', 'वर', 'बुराइयों', 'साधुओं', 'आयुक्त', 'बिछाली', 'ज्यादा-रनों', 'किताब', 'ट्रेक-पैडों', 'खिड़कियों', 'है!', 'लगवाना', '[sa', 'मेजबान', '(wildfires).', 'चित्रों', 'राजपाठ', 'निरपेक्षता', 'मणिपुरी', 'सिकुड़े', 'मिला-', 'अतिशयोक्तिपूर्ण', 'दावों', 'वीजा', 'स्कोरकार्ड', 'श्रुतलेखन-राजभाषा', 'पाशा', 'परमादेश', 'शीशी', '१९२६', 'विकीपीडिया', 'पीढ़ी-दर-पीढ़ी', 'भूगोल', 'प्रभासित', 'तारा-चक्र', 'माड', 'खाद्यकक्ष', 'अटकलं', 'रस', 'कलकारों', 'रूपांतर', 'ओ-ओह', 'उल्लघंन', 'ढोरलकी', 'जन-स्वास्थ,', 'मेलजोल', 'रमैनी', 'सरित्सागर', 'नौसेना', 'द्वाराहुई', '(ईसाईयत', 'तसल्ली', 'आगाह', 'नर्तक', 'पुरानी।', 'हिदुओ', 'आनन्ददायक', 'भाअयामी', 'स्वाधीनता', 'पता?', 'पूर्णतया', 'प्रदेश)', 'प्रचलित', 'अजिताभ', 'ननिया', 'ईसाई', 'बहराइच', 'जायेगा.', 'फुटपाथ', 'श्रेणी:धार्मिक', 'जेटली', '/', 'लि', 'राजनीति', 'अपलॊड', 'WMW', 'न्यूनतम', 'सांडर्स', 'कहूंगा,', '6.10', 'अनुप्रयोगों', 'भंडारघर', 'पुगलिया', 'औरों', 'तीन-चार', 'बांसुरी', 'दसों', 'आओ।', '(conflict).संघर्ष', 'शून्य', 'ग्रिफ़िथ', 'वर्गाकार', 'हिचकिचाहट', 'ह्यऋहृ', 'अध्ययन-अध्यापन', 'ज़रूर', 'गाईड', 'सभागार', 'profit.', '(substitute)', 'ऋसे', 'सुधारवादी', 'जग', 'स्रोतों', 'उत्तर-प्रदेश', 'नेपालन्युज्', 'एकसमान', 'समसऋ-ऊण्श्छ्ष्-याओं', 'गहराइयों', 'रोबोट्स', 'विचाराधिकार', 'देते,', 'Agency).', 'भूनने', 'भीतरी', 'भ्रष्ट', 'रुकीये', 'चॉइस”', 'रागों', 'एवोलुटिओन्', 'नाचने', 'विस्मृत', '259', 'लेते', 'छज्जा', 'सुनते', 'उपवास', '0.75', 'चांद-तारे', '2012', 'उच्चारण', 'हैया', 'मेघनाद', 'अबऋ', 'सांख्यिकी', 'श्री0', 'फेरोमोन्स', 'ऐतरेय', 'असऋ-ऊण्श्छ्ष्-तितऋ-ऊण्श्छ्ष्-वमान', '2030L', 'रचा', 'विश्वनाथन', 'Needlepoint', 'शैलबाला', 'बेटे', 'शंका', 'क्रिस्टीन', 'रेसिस्टेंस', 'चेताते', 'करौली', 'हैं-बिल्कुल', 'प्लैनिंग', 'लैब', 'बिताये', 'अलग', '(roadway', 'संरक्षणीय', '२०.८', 'गिने', 'पहरेबंद', '२२४/५', 'क्रमवार', 'अविवादित', 'ह्यतेलहृ', 'कहिये,', 'मि', 'रखरखाव', 'पक्की', 'जमींदार', 'चश्मदीद', 'Sabha', 'संभालती', 'भिन्न', 'वालं', 'टंकियों', 'चबाने', 'The', 'wicket)', 'नवम्बर', 'यूनेस्को', 'भादुड़ी', 'राजनीतिक', 'बैल', 'तकनलाजी', 'थान', 'लघुरूप', 'डबल्यू', 'मादक', 'प्रतिक्रियाओं', 'दोषारोपण', 'गौओं', 'गुंबद', 'हम,', 'ऋचि', '(Intergovernmental', 'सिद्धान्तों', 'हवादार', 'करते|', 'देगा?', 'व्यक़्तिपरक', 'लक्षऋ-ऊण्श्छ्ष्-य', 'धमकियों', 'सिफ़ारिश', 'आस्ट्रिया-भारत', 'घुसादो।', 'बराबर', 'पिछड़ती', 'गँवाता', 'विशेषञ', 'मारी।', 'टूर-में', 'अभेद्य', 'बढेतरी', 'naka', 'भाषायें', 'तवीत(Tweet)”', 'चावला', 'मायूस', '1912', 'ज़बानी', 'हिमायती', 'सितारा', 'here', 'एजेंटों', 'रक्षक', 'अपीलों', 'इकाई', 'वक़्तव्यों', 'तिरूऊरान', 'उद्यानगृह', '“कृप्या', 'त्रासदी', 'है.भक़्ति', 'जाति,धर्म', 'ब्राह्मण', '“हाँ,', 'Francis', 'अमाप', 'अचंभित', 'आकर्षण', '555', 'धुंध', 'शरीअत', 'लटकाया', 'प्रतिदर्श', 'टल', 'है-अंतिम', 'नेपालमे', 'आते-जाते', 'स्वादिष्ट,', 'सीटें', 'मार', 'डरे', '(लिगेसी)', 'बिरला', '38', 'खोलते', 'जमते', 'उपमंदिर', '(नवरात्रि)', 'धमाका', 'चार-वर्षीय', 'अस्तव्यस्तता', 'सृजित', 'ओथेलो(1959)', 'माय-ड्रीम', 'एस.सी', 'हृदयता', 'जिस्म', 'देवदूतों', 'फ़ीडे', 'और', 'रामकृष्ण', 'दुःख', 'नरेंद', 'कुषाण', 'तिरस्कृत', 'sensitivity)', 'बोद्धा', 'तारामंडल।', 'उदास.', 'पाइलट', 'दृष्टिगत', ',“', 'झगड़ों', 'कडि़याँ', 'यादि', 'सामवेद', 'नाजु़क', 'टेट्रा-पैक', '“मेरा', 'अस्वस्थता', 'गढ़ने', 'फोने', 'पुत्री', 'श्रेणी:अंतरिक्ष', 'कार्यकर्ताओं', 'idXaaAaoM', 'टखने', 'काम-काज', 'लेखों', 'भिजवादूँगा।', 'जातिगत', 'ओड़ीसा', 'विशेशताओं', 'r#anaa', 'काव्यदेवी', 'पार्टियां', 'ग़लत', 'चोर', 'ज़रूरतमंदों', 'फैल', 'सी.', '१०२.२०', 'out)', 'बैट', 'जड़ें', 'घोष', 'बैठेंगे', 'चादरें', 'ढके', 'बाबर', 'आत्मसात्', 'Zथी', 'स्वत', 'दूर्वा', 'चाक', '१९६४)', '१९३१', 'p', 'जागना', 'सफलता', 'लिखवा', 'हैं:', 'एनाऐओटी', '(September', 'कशेरुकी', 'प्रिंसिपल', 'G2G', '3.20', 'चित्रकूट', 'सुर', 'खटखटाया।', 'कहाः', 'बज', 'अंडमानियों', 'अंकोर', '८१', 'परमपावन', 'सेल्युलर', 'था!', 'किरणे', 'मनोवैज्ञानी', 'निगल', 'श्रेणी:फ़र्रुखाबाद', 'अम्ल', 'न्यायनिर्णयन', 'दिग्भ्रमित', 'नाखून', 'रूक्स', 'रूपी', 'तपसऋ-ऊण्श्छ्ष्-वनी', 'धारण्सा', 'महशूस', 'होटल', 'रोमांचक,', 'प्रतिष्ठित', '(Best', 'दावत', 'चिकित्सकीय', 'विद्वान', 'हैं.खगोलशास्त्रियों', '५-', 'विभागों', '31.', 'लाइब्रेरी', 'वाद्य', 'रहता।', 'कार्लचऋ', 'ब्रा', 'चरण', 'बराक', 'आणविक', 'कार्यशीलता', 'जीने', 'टिड्डे', 'मौसम', 'गीली', 'धमाके', 'फौंजे', 'है.इसकी', '1954', 'अन्तर्ध्यान', 'संकटमय', 'धन्य', 'सांख्यिकीय', 'तेलगु', 'पुलीस', '“अगला', 'केपलर', '१)', 'ब्रुनॊ', 'आक्सफोर्ड', 'जोड़ा', 'दक़्कन', 'यांमार', 'बाड़', 'दूतों', 'स्वर्गवासी', 'हैमबर्गर', 'जुटाता', '२८-११-२००७', 'प्रदत्त', 'निगाह', 'four', 'सुदर्शन', 'चौथाई', 'ग़्लिम्पसेज', 'एसा', 'ताल्लुक', 'प्रतिदान', '10.50', 'कॉपीराईट', 'दिया-', 'भाषा-परिवार', 'भिनऋ-ऊण्श्छ्ष्-न', 'विद्यार्थियों', 'सुधारा', 'Men).', 'शृंगारदान', '१९', 'युद्धोपरांत', 'विनम्रता', 'पार्श्ववर्ती', '(१५५१', 'प्रदर्शनी', 'बूटेदार', 'सिडेटिव्ज़', '4.20', 'जनजातियों', 'मालखेड', 'ःइल्ल्', 'अल्लाह', 'बांग्ल', 'एसोसिएशंज़', 'उरुकी', 'इलाके', 'जोड़ो', 'खानदान', 'मानी।', 'बीतता', 'चाटकर', 'तिस', '(डाटा)', 'आत्मविश्लेषी', 'ऋचा', 'पर्यन्त', 'हिट', 'आभासी', 'कमल', 'पे', 'एस', 'पुन', 'सुलह-समझौते', 'शोल्वेन्ट्स्', 'मठ', 'फेफडो', 'धनराशियां', 'Vaman', 'करुणा', '800', 'हमनें', 'होटलं', 'अंत्यसंस्कार', 'माईन', 'ऑफर', 'हाब्बेसियन', 'संबव', 'लखनऊ', 'शि>यों', 'बचाए', 'सूप', 'वजह', 'situation', 'तीर-धनुष', 'क्रास्थवेट', 'सोचें', 'चिट्ठियाँ', 'पडनेवाले', 'अस्त-व्यस्त', 'स्थानों', 'अच्छे,', 'अरकॉट', 'गाली', 'अर्न्तमन', 'उपबंध', 'ठहराएगा', 'और-भी-और', '2.', 'व्यापार,', 'हित-पोषण', 'निगडित', 'विश्व-विजेता', 'मिलें', 'परम्परानुसार', 'देन', 'खोजा', 'वैबसाइट', 'केंद्रकीय', 'खंग', 'दुश्मनी', 'था.इस', 'अनोखी', 'तकहृ', 'विभक्त', 'आलोचनाएँ', 'field)', 'A380,', 'ययाति', 'भरतीयों', 'आनी', 'करवाता', 'मेनिन्जिआइटिस्', 'महाकाशीय', 'ग़ायब', 'उदेश्य', 'डालें,', 'बताओ', 'वालीं', 'पटाया', 'मुर्गियों', 'बनुकर', 'नमस्कार', 'निष्कर्षों', 'स्टूडियो', 'प्राथमिकता', 'निरूपण', 'संघात्मक', 'आर्डर', 'आनंदम', 'प्रतिभावान', 'ढह', 'NOx', 'उपलब्ध', 'हैं.उनकी', 'गलत', 'नागरिकता', 'फैशनेबल', 'वजहें', 'सकी”', 'ड्यूरा', 'खबरों', 'प्रव्Qत्ति', 'वैयक़्तिक', 'gas)', 'प्रऋति', 'संस्थाओँ', 'गीले', 'कीजिए', 'around', 'प्रत्यय', 'मियासथीनिया', 'बनवाया।', 'gases)', 'पीढ़ी)', 'चित्र', 'एक-सी', '१९९०', 'प्रतिषेध', 'पल्ले', 'गाती', 'ह', 'शतरंज', 'संघर्षमय', 'अनुशासनात्मक', 'टेक्स्ट', '-ऊण्श्छ्ष्-रकृति', 'चाल', 'तरिकों', 'विधिमान्यता', 'नीड़-विश्राम', 'वल्ली', 'अनिश्चित', 'टेलर', 'झेल', 'अशुद्ध', 'भारी', 'दाहिने', 'सारथी', 'कारीगरों', 'पाकिस्तान', 'बृमऋ-ऊण्श्छ्ष्-बक', 'gae', 'कॉन्ग्रेस', 'समालोचना', 'कलंक', 'विजयी', 'पीसेंट्स', 'घटनाओं', 'Samsung', '४थी', 'गंजापन', 'धुरी', 'ंमम्स', 'किशनगढ', 'प्लस्टर', 'रीमिक्स', '74.', 'हिमगोला', 'पूछें।', 'स्वचलित', 'क्रिया-कलाप', 'वै&आनिकों', 'लक्ष्य', 'चाहा', 'उदयसिंह', 'हैप्राचीन', 'ढ्श्श्', 'निर्धनों', '१०९वें', 'सफलता.', 'संस्थाओं', 'कबूतर', 'स्वंयवर', 'रवैय्य्ये', 'एक-कमरा', 'दमक', '१९९५', 'धीरे', 'रटना', 'दिखे,', 'सके.लेकिन', 'हॉलैंड', 'बीड़ी', '(1969)', 'सुलह-', 'सेन', 'ilae', 'इनपुट', 'बिल्कुल,', 'गिरफ्तारी', 'वहां', 'लेटिनों', 'शुलऋ-ऊण्श्छ्ष्-क', 'रिएलिटी', 'संबद्ध', 'टेस्ट', 'जाते।', 'यंत्र', 'पुनरूत्थान', 'जोखिम', 'रिकॉर्डिंग', 'इन्हें', 'दिन', 'निर

In [143]:
eng_word_2_idx = {word : idx for idx , word in enumerate(vocab_english)}
print(eng_word_2_idx)

{'<PAD>': 0, '<UNK>': 1, 'timely': 2, "they're": 3, 'medieval': 4, '1914': 5, 'future,and': 6, 'initiatives': 7, 'animals.': 8, 'transformation.': 9, 'vasantesvaram': 10, 'regroup': 11, 'discount': 12, 'upto': 13, 'impersonal': 14, '80th': 15, 'smelled': 16, 'rewards': 17, 'spur': 18, 'smitha-who': 19, 'chakor-chakon': 20, 'occupy': 21, 'announced,': 22, '(moksham).': 23, 'hg': 24, 'extricate': 25, 'inspiring': 26, 'nuhari': 27, 'asi': 28, '1518': 29, 'politely': 30, 'vaca': 31, '(1974)': 32, 'pictures.': 33, 'proves': 34, 'got.': 35, '350km': 36, 'exile.': 37, 'kunduz': 38, 'parvana(1971)': 39, 'makeover': 40, 'sharing.': 41, 'religion.in': 42, 'sudhra': 43, 'airplane': 44, 'initiated': 45, 'weaknesses': 46, 'meter': 47, 'karachi': 48, 'companies,': 49, 'tawa.': 50, 'starve.': 51, 'equal.': 52, 'subjudice': 53, 'wesley,': 54, 'fifty': 55, 'scepticism': 56, 'jainisru': 57, 'restaurants': 58, 'or,': 59, 'toss.': 60, 'maniacs': 61, 'xp-group': 62, 'trained': 63, 'denomination': 64, '(isa)': 65, 'someone,': 66, 'bhalla': 67, '1981,': 68, 'mine,': 69, '1601': 70, 'june': 71, 'glow': 72, 'reading': 73, 'whoredom': 74, 'aparbrahma': 75, 'audio': 76, 'cameos': 77, 'rain-washed': 78, 'optimism': 79, 'duera': 80, 'pasteur': 81, 'load.': 82, 'breathtaking': 83, 'cantankerous': 84, 'branched': 85, 'gobi': 86, 'asbestos.': 87, 'olds': 88, '30000': 89, 'wealthy': 90, 'country.': 91, 'comparative': 92, 'drudge': 93, 'loves': 94, 'lame': 95, 'cholesterol': 96, 'type.': 97, 'providence': 98, 'ayahuasca': 99, 'heard|': 100, 'salas': 101, 'fever': 102, 'plunket': 103, 'dial.': 104, 'labourer': 105, '235': 106, 'wins': 107, 'audited': 108, 'khana': 109, 'heart,': 110, 'imprisonment': 111, 'striking': 112, 'bundles': 113, 'pulikeshi': 114, 'jewelery,': 115, 'oblivion': 116, 'treatment.': 117, 'apology': 118, 'irregularities': 119, 'relationships': 120, 'inevitability': 121, 'religion': 122, 'defence': 123, 'aesthetic': 124, 'russia': 125, '01772': 126, 'scam': 127, 'analogy.': 128, 'billions': 129, 'thou': 130, 'involved': 131, 'long': 132, 'st.': 133, '13.4%': 134, 'another.”': 135, 'kuomintang': 136, 'pad': 137, 'siddharth': 138, 'essence.': 139, '1874': 140, 'clangour': 141, 'disappoint.': 142, 'fragrant': 143, 'vivekananda.': 144, 'dictator': 145, 'consequences,': 146, 'nature.': 147, 'compressed': 148, 'diastolic': 149, 'narrates': 150, 'cementing': 151, 'college': 152, 'tekts': 153, 'downstream': 154, 'skanda': 155, 'taken?': 156, 'shopping': 157, 'kings,': 158, 'dirnna': 159, 'ambulance': 160, 'prosecution': 161, 'retrofitting:': 162, 'tricolour': 163, 'ajonikodith': 164, 'kadamba': 165, 'non-availability': 166, 'paramesvara': 167, 'souvenirs': 168, 'german.': 169, 'continuance': 170, 'caravans': 171, 'fueled': 172, 'novels.': 173, 'dharmashastras': 174, 'funds': 175, 'slogan': 176, '2.680': 177, 'achievements.': 178, "ram's": 179, 'fur': 180, 'mandamus': 181, 'belts': 182, 'assesses': 183, 'passed.': 184, 'sasaram': 185, "chauhan's": 186, 'b.c.': 187, 'unsolvable': 188, 'kolavi': 189, 'tripadis': 190, 'gupt': 191, 'profanity': 192, 'yazh': 193, 'really?': 194, 'begin': 195, 'mahadevi.': 196, 'muraripukur': 197, 'word': 198, 'criticisms': 199, 'grand': 200, 'saying,': 201, 'sindh': 202, 'introduce': 203, 'dismissed': 204, 'airport.': 205, 'badrinath,': 206, 'aarti': 207, 'ocean,second': 208, 'jamnagar,': 209, 'peacefully': 210, 'storeys': 211, 'absolutely.': 212, 'grade:vedic': 213, 'rajatarangini),': 214, 'losses': 215, 'telephony': 216, 'lines:': 217, 'overflow': 218, 'weapon': 219, 'kumudini': 220, 'talwan.': 221, 'expensive.': 222, 'marooned': 223, 'crown': 224, "son'.": 225, 'barahut': 226, 'inspect,': 227, 'store-and-forward': 228, 'ashtank': 229, 'carpet': 230, '650,000': 231, '1162': 232, 'proportionate': 233, 'satirical': 234, 'alahabad': 235, 'synagogue': 236, 'kiosk,': 237, '208': 238, '(original': 239, 'twins,': 240, 'sub-branch': 241, 'screening': 242, 'set': 243, 'know,': 244, 'missing.': 245, 'hokkaido?': 246, 'annexed': 247, 'slender': 248, 'phalguna': 249, 'inclined': 250, 'jewels': 251, 'maize': 252, 'proof': 253, "maoist's": 254, 'chadya': 255, 'lca': 256, 'appam': 257, 'creating': 258, 'beautified': 259, 'gita': 260, 'commons?': 261, 'gates': 262, 'drafted': 263, 'vyala-based': 264, 'senses': 265, 'siddhanta': 266, 'creatively': 267, 'sensations': 268, 'allowance': 269, 'mask': 270, 'cicada': 271, 'affluent': 272, 'facility': 273, 'lucknowi': 274, 'sunbeam': 275, 'ghana': 276, 'egypt': 277, 'undid': 278, 'powerpolitical': 279, 'rgveda,': 280, 'treatments': 281, 'burhanpur,': 282, 'manhattan': 283, 'civilization': 284, 'subject,': 285, 'bachs': 286, 'appearance': 287, 'engm': 288, 'parleyed': 289, '61': 290, 'coincides': 291, 'regimentan': 292, 'concessions': 293, 'blows': 294, 'quaid-e-azam': 295, "ganga'.": 296, 'nichthemeion': 297, 'sitarmaiyya': 298, 'limited': 299, 'teas,': 300, '10d': 301, 'notedthat': 302, 'slump': 303, 'u': 304, 'hilly,': 305, 'aaysaar': 306, 'unicef': 307, 'establishment|': 308, 'shrunk': 309, 'prisoners.': 310, 'far-off': 311, 'authorities': 312, 'pollution': 313, 'tired,': 314, 'bestow': 315, '"it': 316, 'kipling': 317, 'nomadic': 318, 'happy.': 319, 'abating': 320, 'everyone.': 321, 'infinity.': 322, 'bhandar,': 323, 'presumably': 324, 'frolic,': 325, 'sixty': 326, 'celsius': 327, 'evict': 328, 'partons.': 329, 'hi.': 330, 'palanquins': 331, 'investor': 332, 'ford': 333, 'strategy': 334, 'sort': 335, '“my': 336, 'delicate': 337, "islam's": 338, 'disasters': 339, 'seemingly': 340, 'fullers': 341, 'lipi.': 342, 'ugly': 343, 'demanding': 344, 'holstein-friesian': 345, 'wicket.common': 346, 'advaniji': 347, 'dominant': 348, 'ph.d.': 349, 'ms': 350, 'fanatics': 351, 'unprecedented': 352, 'verdicts': 353, 'inoffensive': 354, 'state.and': 355, 'uncut': 356, 'evolving': 357, 'mojud': 358, 'implacable': 359, 'totals': 360, 'password': 361, 'protagonists': 362, 'degradation': 363, 'surat': 364, 'predicting': 365, 'hurriyat': 366, 'cycling.': 367, 'orchard': 368, 'saini': 369, '4490': 370, 'day': 371, 'tax': 372, 'mohamedan': 373, 'hoi': 374, 'mahamuni': 375, 'mw)': 376, 'ads,': 377, 'lengthy': 378, 'imperialists': 379, 'perish.': 380, 'beautiful': 381, 'clad': 382, 'sympathises': 383, 'exhaustion': 384, 'benifits': 385, 'varieties': 386, '26.the': 387, 'ill.': 388, 'geography]]': 389, 'parabrahma': 390, 'dehumanizing': 391, 'chewed': 392, 'deliverance': 393, 'aim.': 394, 'heterozygous': 395, 'cartoons': 396, 'sucks': 397, 'amd': 398, 'raja': 399, 'fan': 400, 'ground': 401, 'vessels': 402, 'pioneer': 403, 'pushcart.': 404, 'chambers': 405, 'and,': 406, 'fulfillment': 407, 'stucco': 408, 'rajdhaanee': 409, 'glut': 410, 'shri': 411, 'similar': 412, 'remark': 413, "festival's": 414, 'balakrishnan': 415, 'one-day': 416, 'diesel': 417, 'films.': 418, 'rs.': 419, 'others,': 420, 'tv?': 421, '85,': 422, 'manibhavan.': 423, 'knee,': 424, 'eras': 425, 'pour': 426, 'she?': 427, 'god!”': 428, 'goddess': 429, "can't.": 430, 'highlighted': 431, 'carriages': 432, 'rules,marylebone': 433, 'remorse': 434, 'saunaka': 435, 'legislator': 436, 'practices,': 437, 'blissful': 438, 'penis.': 439, 'rekha,': 440, 'vanaspati': 441, 'comintern': 442, '1950-95': 443, 'senescence': 444, 'civilization.': 445, 'buddha': 446, 'competed': 447, 'sculptures': 448, 'celebrate-as': 449, 'wickedness': 450, 'bag.': 451, 'ambedkar': 452, 'speech,': 453, 'baikal.': 454, 'desai': 455, '42nd': 456, 'conclusion': 457, 'fans': 458, 'aristocracy': 459, 'sixthly': 460, 'feasibility': 461, 'reddit': 462, 'worse-a': 463, 'chelia': 464, 'ranga-mandapa': 465, 'veiled': 466, 'advi-sory': 467, "government's": 468, 'parthiyo': 469, 'tic': 470, 'asked.': 471, 'gopi.': 472, 'aboriginal': 473, 'investing': 474, 'stabitlity': 475, 'been.': 476, 'maladies': 477, 'stage.': 478, 'universality': 479, 'yuro-3': 480, 'globalized': 481, 'quality': 482, 'yadukul': 483, '568-488': 484, "wing'": 485, 'indica.': 486, 'tony': 487, 'pv': 488, "amitabha's": 489, 'wall-recesses': 490, 'meber': 491, 'garments': 492, 'continuously': 493, 'randomly': 494, '(': 495, 'upanishads(mystic': 496, 'kbg': 497, 'muslim': 498, 'system.': 499, 'tastes': 500, 'fabrication': 501, 'weddings': 502, '49': 503, 'kaviyur': 504, 'away.': 505, 'hinduism': 506, '4.10': 507, '+/-': 508, 'manifestations': 509, 'bills.': 510, 'monoxide': 511, 'victory': 512, 'efficiently.': 513, 'stuffed': 514, 'trajectories': 515, 'coverd': 516, 'incendiary': 517, 'nandikeshwar': 518, 'pursuits': 519, 'admissibility': 520, 'karl': 521, 'birthday!': 522, 'twice.': 523, 'pakistan,': 524, 'initial': 525, 'reporting': 526, 'high-walled': 527, 'inadequacy': 528, 'ghungroo': 529, 'holding': 530, 'bolstered': 531, 'annualy.': 532, 'bhavishya-pumna': 533, 'proactive': 534, 'wars”': 535, 'discriminate.': 536, 'uttarakhand.': 537, 'aggrieved': 538, 'refers': 539, 'propagating': 540, 'more': 541, 'talwar': 542, 'followers.': 543, 'himalayas,': 544, 'dice': 545, 'devices,': 546, 'autobiography': 547, 'kacha': 548, 'splendour': 549, 'one-fourth': 550, 'sickening': 551, 'equity': 552, 'notebook,': 553, 'colourful': 554, 'outraged': 555, 'afternoon': 556, 'meerut,': 557, 'seed-drills': 558, 'heared': 559, '1936.': 560, 'shore.': 561, 'irrelevant': 562, '“sunitha,': 563, 'rightful': 564, 'panjara': 565, 'unitary': 566, 'unloaded': 567, 'tenor': 568, 'metro': 569, 'centimetre': 570, 'realy': 571, 'half-tooth-wide': 572, 'non-existent': 573, 'each.': 574, 'dimly': 575, 'scene': 576, 'menace': 577, 'too.': 578, "'swayamwar'": 579, 'diamonds,': 580, 'disburse': 581, '4,50,000': 582, 'positive': 583, 'habit': 584, '(1375-1700)': 585, 'pleased': 586, 'hearts': 587, 'marginally': 588, 'thrive.': 589, 'bull-elephant': 590, 'rajasthani': 591, 'pradesh,': 592, 'sahibs': 593, 'format:': 594, 'had,': 595, 'anushacan': 596, 'piano.': 597, 'cosmopolitan': 598, '1-800-got-junk?': 599, 'minority': 600, 'scars': 601, 'devanagari).': 602, '“”global': 603, 'ministerial': 604, 'taila': 605, 'ease': 606, 'ponds': 607, 'boondi': 608, 'hajrat': 609, 'realising': 610, 'consultations,': 611, 'crops': 612, 'paste': 613, 'headstart': 614, 'idioceus': 615, 'six-day': 616, 'unofficial': 617, 'frustrating': 618, 'resource': 619, 'crossborder': 620, 'grammar|': 621, 'barari': 622, 'pant.': 623, 'khrushchev': 624, 'cellular': 625, 'essentially': 626, '[1943]': 627, 'electronics': 628, 'yudistar': 629, 'relied': 630, 'cure.': 631, 'makka,': 632, 'pan-pacific': 633, 'vishnuvardhana': 634, 'nets': 635, 'lexicographers': 636, 'scarify': 637, 'capacity': 638, '00,': 639, 'calcute': 640, 'panchayat.': 641, 'sugars': 642, 'caitra': 643, 'radiation.': 644, 'veda)': 645, 'supplied': 646, 'dyes': 647, 'washed': 648, 'sachau': 649, 'hajarat': 650, 'ghatkopar': 651, '3.82m': 652, 'taken': 653, 'participation': 654, 'adoptions': 655, 'or': 656, 'humid': 657, 'stabd': 658, 'revolution-er)': 659, 'helps': 660, 'respected': 661, 'canada': 662, 'published': 663, 'worst': 664, 'benefited': 665, 'mrs.subhadra': 666, 'reclaiming': 667, 'bicycle': 668, 'concepts': 669, 'dma-kudha': 670, 'puranchandra': 671, 'out“”': 672, 'mom': 673, 'need,': 674, 'ayodhya,': 675, 'innovations,': 676, '(1943)': 677, 'mean.': 678, '-pace,': 679, 'phehylalanine': 680, 'ram.': 681, 'planks': 682, 'closets': 683, 'a.k.a': 684, 'uterus': 685, 'founded': 686, 'spiritually': 687, 'talas': 688, 'portrayal': 689, 'tibet,': 690, 'well-known': 691, 'metrical': 692, 'sin': 693, '2600': 694, 'occupied': 695, 'artificial': 696, 'muaviyarji,': 697, 'run.': 698, 'mentality': 699, 'loins': 700, 'medicine,': 701, 'discreetly': 702, 'respectively.during': 703, 'samiti': 704, 'zia': 705, 'chanted': 706, 'paintings.': 707, 'studios,': 708, 'mahadevi': 709, 'dryness': 710, 'composed.': 711, '::': 712, 'wealthiness': 713, 'srikrishna-literature': 714, '1998': 715, 'dine': 716, 'kilo': 717, 'right)': 718, 'worst-case': 719, 'generals': 720, 'dream,': 721, 'highlighting': 722, 'thy': 723, 'delegation': 724, 'chikitsasthana': 725, 'rightness.': 726, 'barking': 727, 'mougal': 728, 'bicp': 729, 'coordinate': 730, 'howling': 731, '3:20."': 732, 'maryada': 733, 'giddha': 734, 'crestfallen.': 735, 'click.': 736, 'releazed': 737, '(constructs': 738, 'one-size-fits-all': 739, 'ramganga,': 740, 'venugopala': 741, 'cunningham': 742, 'syamali': 743, 'attractions,': 744, 'impatient': 745, 'smriti.': 746, '01624': 747, 'shankerlal': 748, '30-year': 749, 'thalheimar': 750, 'gam(2001)and': 751, '(over': 752, 'stuff.': 753, 'these,': 754, '11th,': 755, 'misfortunes': 756, 'sights': 757, 'careful.': 758, 'upamanas': 759, 'descriptive': 760, 'woh': 761, 'storm': 762, 'flirtatious': 763, 'jointly': 764, '1947': 765, 'catalogues': 766, 'president': 767, '60': 768, 'reinstated': 769, 'polo.': 770, 'quran.': 771, 'site,one': 772, "they've": 773, 'bottles': 774, 'chartered': 775, 'sinkhandhar': 776, 'minar': 777, 'missing': 778, 'pitripaksha': 779, 'industries': 780, 'dwijendranath': 781, 'ups': 782, 'jtleie': 783, 'beautifully': 784, 'earnestly': 785, '(12770ft)': 786, '1562': 787, 'innocuous': 788, '3-member': 789, 'human,': 790, 'immunology': 791, 'worst,': 792, 'pulls': 793, 'khaas': 794, 'knit': 795, 'taiwan,': 796, 'loads': 797, '38%': 798, 'cholera': 799, 'regulate': 800, 'thus,': 801, 'amarakosh': 802, 'communicators': 803, 'noncombatant,': 804, 'graphics': 805, 'plight': 806, 'considerably': 807, 'excludes': 808, '-30c': 809, 'thrissur': 810, '1572,': 811, 'partially': 812, 'abovementioned': 813, 'issue': 814, 'box-office': 815, '[over]': 816, 'flowers.': 817, 'indo-arya': 818, 'degeneration': 819, 'visitor': 820, 'alarm.': 821, 'roughage': 822, 'elevations': 823, 'blend': 824, 'nebdada': 825, 'taluk': 826, 'human': 827, 'eutrophication': 828, 'question.”': 829, 'offspring': 830, 'nyaya': 831, 'mandi': 832, 'sheshnag': 833, 'hindi,different': 834, 'addams': 835, 'dissolved': 836, 'enunciated': 837, 'ings': 838, 'desh,': 839, 'rupees,': 840, "they'll": 841, "'rajasthani'.": 842, 'cross-border': 843, 'troposphere': 844, 'marthahalli': 845, 'well-to-do': 846, 'strengthful.': 847, '39.4': 848, 'transliteration': 849, 'up': 850, 'formed.': 851, 'times': 852, 'ceremonies': 853, 'stf': 854, 'extremist': 855, 'edition': 856, 'indicates,': 857, 'team.': 858, 'cad': 859, 'thread': 860, 'likelihood': 861, 'ousted': 862, 'utukkai': 863, 'lights': 864, 'powerfull': 865, 'negligence': 866, 'mcc': 867, 'mass': 868, 'lodged': 869, 'samser': 870, 'interchangeably': 871, 'good-will': 872, 'jagaran': 873, 'travelling': 874, 'rinses': 875, 'behind.': 876, 'unceremoniously': 877, 'mahanagar': 878, 'collectors': 879, 'prevalence': 880, 'ismat': 881, 'emblem': 882, 'mehrab': 883, 'forbids': 884, 'parivara': 885, 'smiling.': 886, 'atheist.': 887, 'specificity': 888, 'intercourse': 889, 'government-state': 890, 'conditioner': 891, 'offences': 892, 'supply': 893, 'bhagirathi': 894, 'extreme': 895, 'tiger': 896, 'spoanjiosam': 897, 'impossibility': 898, 'antagonism': 899, 'goddess,': 900, 'effluents': 901, 'presentation.': 902, 'metric': 903, 'prevention': 904, 'budhha': 905, 'withhold': 906, 'jiyauddani|': 907, 'magnum': 908, 'telecommunications': 909, 'bar': 910, 'bankim': 911, 'farmlands': 912, 'advantages.': 913, 'besdies': 914, 'mamata': 915, 'haven,': 916, 'sorneshwara': 917, 'hotdogs.': 918, 'gases.': 919, 'half-baked': 920, ']': 921, '(sull),': 922, 'shakarulla': 923, 'effected': 924, 'impaired': 925, 'samsher,': 926, 'jaitley': 927, 'makeshift': 928, 'staunchest': 929, 'dolomite.': 930, 'interfere': 931, 'numbers.': 932, 'subscribe': 933, 'gaganendranath': 934, 'about-': 935, 'sluggish': 936, 'furtherance': 937, 'melancholy': 938, 'crs.': 939, 'fractures': 940, 'karvanseri,': 941, 'yielded': 942, 'geography': 943, 'woman.': 944, 'date': 945, 'throne': 946, 'punch': 947, 'leeds': 948, 'entangled': 949, 'twentyfive': 950, 'deepest': 951, 'prisons': 952, 'torn': 953, 'sportsman': 954, 'rubberstamped': 955, 'healing': 956, 'clothes-knit': 957, 'hariwansh': 958, 'chief.': 959, 'formations,': 960, 'plunger': 961, '“before': 962, 'shoulders,': 963, 'taught': 964, 'asphyxiation': 965, 'see,': 966, 'friend.': 967, 'reluctant': 968, 'resting': 969, 'opportunistic': 970, '519': 971, 'losers': 972, 'graveyard.': 973, 'concurrent': 974, 'completed.': 975, 'disinheritance,': 976, 'productivity.': 977, 'chide': 978, 'course.”': 979, 'rainfall.': 980, 'photograph': 981, 'sitting': 982, 'triplet': 983, 'cave': 984, 'bustard.': 985, 'dranatist': 986, 'cognitive': 987, 'quietly': 988, 'brilliantly': 989, 'dislkes': 990, "bayes's": 991, 'maithilicharan': 992, 'highest': 993, 'epithet': 994, 'ratio,': 995, 'churidars': 996, "torture's": 997, 'graphic': 998, 'soils': 999, 'delayed,': 1000, 'who': 1001, 'observes': 1002, 'given': 1003, 'reframe': 1004, 'female.': 1005, 'jeopardised': 1006, 'ambassador': 1007, 'seal': 1008, 'heavenly': 1009, 'aasif': 1010, 'ranks': 1011, 'actions.india': 1012, 'astank': 1013, 'beats': 1014, 'politics:': 1015, 'top': 1016, 'bid,': 1017, '==': 1018, 'hindikunj)': 1019, 'dwelled': 1020, 'ground!': 1021, 'underwent': 1022, 'afraid': 1023, 'referring': 1024, 'invented': 1025, 'sexton': 1026, 'modern': 1027, 'montana': 1028, 'cholas': 1029, '1882': 1030, 'localities': 1031, 'played': 1032, '1899.': 1033, 'encouraged': 1034, 'proofs': 1035, 'revenue.': 1036, 'booted': 1037, 'arbitration': 1038, 'tailpipe': 1039, 'aquatic': 1040, 'dogs': 1041, 'seize': 1042, 'authenticity': 1043, 'dogmatic.': 1044, 'usage': 1045, 'priorities': 1046, 'inflated': 1047, 'approached': 1048, 'playfulness': 1049, 'promises,': 1050, 'pumps': 1051, 'hazari': 1052, 'compulsorily': 1053, 'went,': 1054, 'separtism': 1055, 'toudaiji': 1056, 'bringing': 1057, 'shine': 1058, 'sudra': 1059, 'not-so-loyal': 1060, 'cantonese.': 1061, 'foil': 1062, 'market?': 1063, 'nanda': 1064, 'manoj': 1065, 'revolt': 1066, 'neurological': 1067, 'copyrighted': 1068, 'carnival': 1069, 'racing': 1070, 'discipline': 1071, 'card“”': 1072, 'seeta-': 1073, 'warming,': 1074, 'unnatural': 1075, 'wal-mart.': 1076, '712,': 1077, 'apse': 1078, 'mekegrahill': 1079, 'decaying': 1080, 'through.': 1081, "'complete": 1082, 'talk?': 1083, 'fossil': 1084, 'othello': 1085, 'banerjee': 1086, 'train?': 1087, '20-25': 1088, '81-7446-350-x': 1089, 'karru': 1090, 'haryana|': 1091, 'cash': 1092, 'voice.': 1093, 'shift': 1094, 'reputation': 1095, 'crickets': 1096, 'bestowed': 1097, 'tarachand': 1098, 'headed': 1099, 'fats': 1100, 'surdas-': 1101, 'drill': 1102, 'boudha,': 1103, 'legislative,': 1104, 'hopes': 1105, 'encroachers': 1106, 'strive': 1107, 'university?': 1108, 'enduring': 1109, 'response': 1110, 'rubies': 1111, 'full-grown': 1112, 'jaish-e-mohammed': 1113, '(eleventh': 1114, 'parking': 1115, 'concerns,': 1116, 'amitabh': 1117, 'street.': 1118, 'mahanta': 1119, 'board,': 1120, 'sursagar,': 1121, 'kultar': 1122, 'tissue-engineering': 1123, 'annealed': 1124, 'deaths': 1125, 'aid.': 1126, 'guru,': 1127, '1500bc)': 1128, 'bowls': 1129, 'cereals': 1130, 'imphal': 1131, 'populous': 1132, 'requested': 1133, 'labor': 1134, 'kunte': 1135, 'horrifyingly': 1136, 'favor(excluding': 1137, 'bird.': 1138, 'compact': 1139, 'itrans': 1140, 'sounded.': 1141, 'heeba': 1142, 'appears': 1143, 'reflect': 1144, 'experiments': 1145, 'mosquitoes': 1146, 'amravati': 1147, 'lancer': 1148, 'masseur': 1149, 'ignore': 1150, 'right': 1151, 'manipuri': 1152, 'become': 1153, 'fast.': 1154, 'zinoveiv': 1155, '3735': 1156, '190': 1157, 'trotsky': 1158, 'excreted': 1159, 'tomb.': 1160, '1005': 1161, 'knees': 1162, 'breeding': 1163, 'china:': 1164, 'carr': 1165, "vasallam's": 1166, 'lawyer': 1167, 'pardon': 1168, '422-crore': 1169, 'kalimpong': 1170, 'clause': 1171, 'depdi': 1172, 'appeals': 1173, 'endeavours': 1174, 'colophons': 1175, 'poet-seer': 1176, 'pannels,': 1177, 'ganguly.': 1178, 'released.': 1179, 'simon': 1180, 'sunal': 1181, 'wolfensohn': 1182, 'book?': 1183, 'exhorting': 1184, 'sweater': 1185, 'item,': 1186, '?': 1187, 'jokes': 1188, 'boar-head': 1189, 'grahan': 1190, 'ferrari': 1191, 'transposition': 1192, 'thee': 1193, 'birhat

In [144]:
hindi_word_2_idx = {word : idx for idx , word in enumerate(vocab_hindi)}
print(hindi_word_2_idx)

{'<PAD>': 0, '<start>': 26242, '<end>': 30857, 'तरह-एकल': 3, "they're": 4, '1914': 5, 'संक्रमित': 6, 'है-उसे': 7, 'भूमि': 8, 'दुर्घटनाओं': 9, 'मंड़पम': 10, 'बन्ने': 11, 'मेलाइक': 12, 'कोट्टु': 13, 'विद्युत-आपूर्ति': 14, 'रणनीतिकार': 15, 'अमरीकी': 16, 'सेकडों': 17, 'गीली,': 18, 'समस्योओं': 19, 'न?”': 20, '(biological': 21, 'ड़ी.वूल्फेनसोन': 22, 'सामंती': 23, 'नाविक': 24, 'अधिमिश्रण': 25, 'यादृच्छिक': 26, 'एपीजे': 27, 'खानदानी': 28, 'वाहिनी': 29, 'वऋ-ऊण्श्छ्ष्-यतीत': 30, 'द्विभाषीय': 31, 'खिलाये': 32, 'पुष्पिकाएं': 33, 'जला': 34, 'किसको': 35, 'ज्ञानांकुर': 36, 'शांतनु': 37, 'हेटेरॉप्टेरा': 38, 'बेशुमार': 39, 'चढ़े': 40, 'अपर्याप्तता': 41, 'मापन': 42, 'उठा': 43, 'गड्डिंयां': 44, 'डोंब': 45, 'गुंथे': 46, 'भविषऋ-ऊण्श्छ्ष्-य': 47, 'घेरा': 48, 'पांचवें': 49, 'हड्डियां': 50, 'कोंड़ोलीज़ा': 51, 'बट': 52, 'कताई': 53, 'बढ़ना': 54, 'क़दमों': 55, 'मुग़ल': 56, 'नागिदेव': 57, 'मिलेंगे।': 58, 'संकल्पों': 59, 'उड़ातें': 60, 'चुम्बकीय': 61, 'मुकझा': 62, 'हिमनदों': 63, 'मुखों': 64, 'Ka%aa': 65, 'वाकर': 66, 'Anthropogenic': 67, 'चालुकयों': 68, 'आलकमान': 69, 'क्षतिग्रस्त': 70, 'है.धीरे': 71, 'केशे': 72, 'फूंकने': 73, 'चालुक़्यों': 74, 'चौबीस': 75, 'छू': 76, 'केद्रित': 77, 'नादुरूस्त': 78, 'सिलसिले': 79, 'सेनापतियों': 80, 'अभिव्यक्तियां': 81, 'सुनिए,': 82, 'हो.': 83, 'अध्यापक': 84, 'सा': 85, 'वाशिंगटन': 86, 'कोमपीनयों': 87, 'उल्फा': 88, 'DEFRA': 89, 'भारीमात्रा': 90, 'दिखता': 91, 'चौंतीस': 92, '(अमेरिका)': 93, 'हैल्थ': 94, '(VSNL)': 95, 'हेल्थ': 96, 'है,”': 97, 'प्राणियों': 98, 'पिता.': 99, 'सव्Mय': 100, 'मब(1गिगाब्य्ते': 101, 'अZवधि': 102, 'प्रजातान्त्रिक': 103, 'करेंगे/करेंगी': 104, 'model)SRES': 105, 'सिखाया': 106, 'मानना': 107, 'काई': 108, 'राजनीती': 109, 'आवश्य': 110, 'लगाकर': 111, 'नियो>आ': 112, 'मिल': 113, 'निकोबार': 114, 'लाया': 115, 'रीफ': 116, 'व्यवसायिक': 117, '01772': 118, 'ड़ाले': 119, 'प्रासादों': 120, 'नांमाकित': 121, 'समरू': 122, 'पुनरीक्षा': 123, 'शिष्टमंडल': 124, 'ब्राह्म': 125, 'कैरी': 126, 'प्रमाणों': 127, 'रुचिकारक': 128, 'अनुन्मोचित': 129, 'गिरावट': 130, 'रुपए': 131, 'ख़रीदे': 132, 'ज्योतिरीन्द्रनाथ': 133, 'औरतों': 134, '४०': 135, 'माडगूळकर': 136, 'सुनाई': 137, 'असावधानी': 138, '\u200eमिलेगा': 139, '1874': 140, 'ध्वनि-विस्तारक': 141, 'णो': 142, 'किशोर': 143, 'आत्मचरित्र': 144, 'ष्ह्-': 145, 'मूलतत्व': 146, 'AiQakar': 147, '(Lead)': 148, 'पत्रकार': 149, 'क्लिंटन': 150, 'श्रीनगर': 151, 'उल्लेखनीय': 152, 'सहभागी': 153, 'समूहन': 154, 'बक-बक': 155, 'kiryaalaa': 156, 'बरसों': 157, 'बहेलिये': 158, 'घेटालों': 159, 'है-क्योंकि': 160, 'ग्रहणशील': 161, 'चोटें': 162, 'प्रण': 163, 'ग्रीष्मावकाश': 164, 'वितरण': 165, 'टेबल्स': 166, 'सचिवालयों': 167, 'छल': 168, 'हेरात': 169, 'संभवत': 170, 'नहंईं': 171, 'आज्ञाकारी': 172, 'पाना।': 173, 'कीटों': 174, 'भेजे.': 175, 'उद्धेश्य': 176, 'मारिजुआना': 177, 'आप्रावासिय': 178, 'नवनिर्मित': 179, 'साजो': 180, 'जालिका': 181, 'शद': 182, 'जूड़े': 183, 'बसु': 184, 'बहुतों': 185, 'उपलब्धियॉ': 186, 'मित्तर': 187, 'गुजराती': 188, '0-470-85100-7': 189, 'अतएव': 190, '१५': 191, 'कड़े': 192, 'ईरान': 193, 'दी।': 194, 'अग्रवन': 195, 'जरा': 196, 'चिंताएं': 197, 'शाहजहां': 198, 'इंटर': 199, 'स्वतः': 200, 'माकपा': 201, 'पीढऋई-दर्रपीढऋई': 202, 'कानूनत': 203, 'भूकंप': 204, 'वा': 205, 'ऐतिहासिक': 206, 'मान्टेस्कयू': 207, 'कर्हा': 208, 'मुश्किलं': 209, 'कन्सल्टेन्ट': 210, 'कलश': 211, 'Electric': 212, '(१९९८': 213, 'कोलाबा': 214, 'उम्मेद': 215, 'राहदारी': 216, 'दीजिये': 217, 'समज्हैते': 218, 'अनोखा': 219, 'कटवाना': 220, 'ढंके': 221, 'गाना': 222, 'लीलावती': 223, 'जकड': 224, 'मिगर': 225, 'टेम्पल': 226, '1162': 227, 'नागराज': 228, 'आआ': 229, 'वैसी': 230, 'दालान': 231, 'सिन्डिकेशन': 232, 'वागीश्वरम': 233, 'उलऋ-ऊण्श्छ्ष्-टे': 234, '208': 235, 'खोलिए।': 236, 'कोलम्बो': 237, '१-डी।': 238, 'पुस्तिकाओं': 239, 'महामण्डलेश्वर': 240, 'भातीय': 241, '(revolutionary)दृष्टिकोण': 242, 'जमा': 243, 'सामानऋद्दय': 244, 'ग्रान्ट': 245, 'घोड़े': 246, 'रिटर्न': 247, 'अलविदा': 248, 'क़्लर्क': 249, '!!': 250, 'प्रर्वतक': 251, 'निर्भर': 252, 'ऋन': 253, 'व्याकरणिक': 254, 'अनुपस्थित': 255, 'अग्रत्वचा': 256, 'लक्ष्मी': 257, 'तत्पश्चात': 258, 'संलगऋ-ऊण्श्छ्ष्-न': 259, 'थी?': 260, 'पूर्व)': 261, 'दिया!': 262, '61': 263, 'जहर': 264, 'पाठक': 265, 'कोटे': 266, 'bahut': 267, 'दुर्बलों': 268, 'फ़्रांसीसी': 269, 'उपलइधयों': 270, 'एड़ीए': 271, 'कमेंटों': 272, '(atmosphere)': 273, 'घरवालों': 274, 'संबंद्ध': 275, 'मृतक': 276, 'रिंसेज़': 277, 'मलिन': 278, 'आरती': 279, 'पुनरूद्धार': 280, 'समकक्ष': 281, 'समज्ह': 282, 'इन्हेरिटेंस': 283, 'प्रभुसत्ता': 284, 'कवियुर': 285, 'स्वादिष्ट': 286, 'पत्थर': 287, 'अफ्रिका': 288, 'निरसन': 289, 'विक्टोरिया': 290, '/सोफा/टेबल/काउंटर': 291, 'प्रेरणास्रोत': 292, 'स्त्राव': 293, 'प्राणिशास्त्र': 294, 'मोड़ा': 295, 'जेल-अधीक्षक': 296, 'तौलते': 297, 'पादप-रोम': 298, '३-४': 299, 'साधू-संतों': 300, 'सिक्किम': 301, 'प्रतीक': 302, 'म्युज़ियम': 303, 'पाचेलबेल': 304, 'उदाहरण:': 305, 'मुख्यत:': 306, 'ना?': 307, 'sana': 308, 'बेकार': 309, 'ईमानदारी': 310, 'पंखों': 311, 'अवैद': 312, 'स्लेटी': 313, 'अनु': 314, 'बांटा': 315, 'पहेले': 316, 'दें': 317, 'विजयवाड़ा': 318, '(सामान्य)': 319, 'माँगे।': 320, 'देंजिंग': 321, 'दर्शन-जिन्हें': 322, 'दण्ड': 323, 'भुजाओं': 324, 'चूनीं': 325, 'Bruno)आधारित': 326, 'जिमखाने': 327, 'मृदंग': 328, '(विकिस्रोत': 329, 'चपटा': 330, 'फलोद्यान': 331, 'चेचेन्या': 332, 'गोरे': 333, 'गुनी': 334, 'तनों': 335, 'जे-ज़ी': 336, '४००,०००': 337, 'बर्बाद': 338, 'प्रयोजन': 339, 'निकासी': 340, 'बनावटी': 341, 'रही।': 342, 'प्रचलन': 343, 'मामलों': 344, 'होता.': 345, 'principle)': 346, 'व्यक़्ति': 347, 'खोलता': 348, 'सेवानिवृत्ति': 349, 'थोडी': 350, 'ट्यूबरकुलोसिस': 351, '१८००': 352, 'ऐश्वर्या': 353, 'खरीदा': 354, '4490': 355, 'छ्ल': 356, 'मि०': 357, 'अनुपचारित': 358, 'लेखिका': 359, 'India': 360, '(2000).': 361, 'दिलाया': 362, 'आतऋ-ऊण्श्छ्ष्-मनिर्भरता': 363, 'सम्मोहक': 364, 'विठ्ठल': 365, 'परिशोधन': 366, 'अ-धम्म': 367, 'मण्डी': 368, 'अंडकवच': 369, 'कडियों': 370, 'हैं-तो': 371, 'अंबार': 372, 'ह्यमीजल्सहृ': 373, 'मैनेस्टर': 374, '.वे': 375, 'raja': 376, 'दुखाने': 377, 'Defense)': 378, 'बहानों': 379, 'उकरा': 380, 'प्रतिबोध': 381, 'साझेदारों': 382, 'कूड़े': 383, 'कल्लमथड': 384, 'मसनवी': 385, 'Aproch': 386, 'ड़्राइंग': 387, 'रसद-मदद': 388, 'बेसेन्ट': 389, 'मांगो': 390, '(water': 391, 'मोनस्टर.कॉम': 392, 'आएँगे': 393, 'चाहूंगी': 394, '“जूता”': 395, 'उपजीवियों': 396, 'तबसे': 397, 'स्थल)': 398, 'तूफान': 399, 'शस्त्रज्ञ': 400, 'था।': 401, 'किंवदन्ती': 402, 'अनुच्छेद': 403, 'तापमान': 404, '(अंग्रेज़ी': 405, 'विपरीत': 406, 'विलोपन': 407, '(अभिव्यक्ति': 408, '२१२': 409, 'हाफिज': 410, 'स्पाइरल': 411, '२)': 412, 'जिमी': 413, '53हृ': 414, 'गया.संतों': 415, 'वक्ररेखी': 416, 'सत्याग्रह': 417, 'कऋ-ऊण्श्छ्ष्-वालिटी': 418, 'सुनवाई': 419, '............': 420, 'बैटरियां': 421, '1950-95': 422, 'व्यि>गत': 423, 'पेड़-पौधों': 424, 'कैरियर': 425, 'चनिया': 426, '(London': 427, 'कार्यऋमों': 428, 'साऊथ': 429, 'वर्णक्रम': 430, 'कुन्नातुर': 431, 'बाँधती': 432, 'दोषी': 433, 'पॉ': 434, 'अंकीय': 435, 'prMpra': 436, 'थी.इनमें': 437, 'है.अस्थियां': 438, 'गुलबर्गा': 439, '६०': 440, 'साधुमना': 441, 'किल्लरी': 442, "लक्ष्मण'": 443, 'केआक्रमण': 444, 'करर्य': 445, 'लिंक्स': 446, 'ज्यॉफ': 447, 'ललकृष्ण': 448, 'Motorola': 449, 'दौड़ना': 450, 'शि>यां': 451, 'प्रखर': 452, 'भूवैज्ञानिक': 453, 'धक़्का-मुक़्की': 454, 'रातभर': 455, 'भंग': 456, 'जनमत': 457, 'कमरा': 458, 'अंतरिक्ष': 459, 'सार्वलौकिक': 460, 'परिपक़्व': 461, '568-488': 462, 'यूएस-64': 463, 'सुंदार': 464, 'तभी': 465, 'एकाश्म': 466, 'ऋब्रह्मसिद्धांतऋ': 467, 'नेपाल)': 468, 'करुण': 469, 'असमानताएँ': 470, 'पैसे': 471, 'बम्बई': 472, '(': 473, 'कावूरी': 474, 'कॉन्फेडरेशन)': 475, 'नेतृत्व': 476, 'विशऋ-ऊण्श्छ्ष्-वास': 477, 'विकरण': 478, 'भेड़': 479, 'कैमेरून,': 480, 'देखबाल': 481, 'पुनर्व्यवस्थित': 482, 'दिसंबर': 483, 'आनलाइन/आफलाइन': 484, '(socioeconomic)': 485, 'व्यतीत': 486, 'नियुक़्ति': 487, '49': 488, 'तोकियो': 489, 'सूखे': 490, 'मंशा': 491, 'खलीफा': 492, '4.10': 493, 'modalities': 494, 'लौटता': 495, 'बुनाई': 496, '(non-combatant)एसकुछ': 497, 'स्टेटमेंट': 498, 'वार्णावत': 499, 'आऊंगा।': 500, 'कटोरा': 501, 'कॊ': 502, 'एकता': 503, 'ऑक्सफ़र्ड': 504, 'वैबसाईट': 505, 'रेडियोधर्मी': 506, '।': 507, 'कहूँगा': 508, 'पत्रों': 509, 'उपपत्ति': 510, 'थानों': 511, 'जगाने': 512, 'वकीलों': 513, 'निवासों': 514, 'पकड़कर': 515, 'रिपब्लिकन': 516, 'रहा/रही': 517, 'नाजिज़्म': 518, 'कुंजों': 519, 'गैलन': 520, 'वॉयेजर': 521, 'अलीसियम': 522, 'यह': 523, 'बने': 524, 'चमत्कारी': 525, 'सत्ताएं': 526, 'कंट्रोल': 527, '(bog)में': 528, 'खायी': 529, 'जोकि': 530, 'सॉम': 531, 'निरोधक': 532, 'उद्योगीकरण': 533, 'ह्यवऋ-ऊण्श्छ्ष्-यापकताः': 534, 'जलयान': 535, 'छूटी': 536, 'देखा।': 537, 'प्रदर्शन-शृंखलओं': 538, 'अंगरक्षक': 539, 'संपर्क': 540, 'मंगलनी': 541, 'पहाड़ियों': 542, 'हत्थाकुर्सी': 543, 'बढाने': 544, 'ङ्': 545, '“बंग': 546, 'टूट-टूटकर': 547, 'राष्ट्रों': 548, 'तालमेल': 549, 'एंगेल': 550, '(deficit)': 551, 'स्मिथसोनियन': 552, 'कार्याक्षेत्र': 553, 'मोर्चे': 554, 'फार्मलडिहाइड': 555, 'जन-समदाय': 556, 'नेत्र': 557, 'जातिप्रथा': 558, 'आविष्कार': 559, 'कोडोन': 560, 'पूर्व,': 561, 'कहकर': 562, 'येरुसलम': 563, 'कार्यकारी': 564, 'सहयोगपूर्ण': 565, 'समन्वित': 566, 'लागू': 567, 'जेसन,': 568, 'अनुप्रस्थ': 569, '(तालियाँ)': 570, 'चाहे': 571, 'जीवन-वर्ष': 572, 'श्रमिक': 573, 'मई': 574, 'कश्मकश': 575, 'वि०)': 576, 'भाँगा': 577, 'उत्पीड़ित': 578, 'हास्यापद': 579, 'देशवासी': 580, 'रोयप्पा': 581, 'तारदी': 582, '\u200eधरती': 583, 'क्रम-विक्रम': 584, 'कांच': 585, 'लिए)': 586, 'पाठक:': 587, 'प्रभुसत्तारहित': 588, 'देक्र्यप्तिंग': 589, 'जीवन्तता': 590, 'गिरने': 591, 'बदलते': 592, 'भीमगोडा': 593, 'करो!': 594, 'भोजपुरी': 595, 'खोलो।': 596, 'रंग-बिरंगा': 597, 'राज़्यों': 598, 'पार्टी-संयुक़्त': 599, 'मोडता': 600, 'फोम': 601, 'चरण-': 602, 'लोमड़ी': 603, 'वाटसन': 604, 'पढ़ाकू': 605, 'पाण्डवपक्षिय': 606, 'लाभांश': 607, 'चरितार्थ': 608, 'आनुवंश': 609, 'निद्रा': 610, 'उत्पZत्ति': 611, 'आज़मा': 612, '(आवर्धन': 613, 'पर्यटक': 614, 'सोना': 615, 'शेक्सपियर': 616, 'Zअर्थ': 617, 'पदार्थवादी': 618, 'जीव-जंतुओं': 619, 'समझर': 620, 'आओ': 621, 'समाज-शास्त्र': 622, 'काँग्रेस': 623, 'उतारने': 624, 'बुरहानुद्दीन': 625, 'भुगतान-जब-तुम-जाओ': 626, 'सूबेदार': 627, 'तोड़ी': 628, 'कच्छ': 629, 'जन्मोत्सव': 630, 'अलंऋत': 631, 'दर्शकों': 632, 'पायी': 633, 'एजुकेशनल': 634, 'स्याही': 635, 'कैजन': 636, 'शृंखल': 637, 'प्रोटेक़्शन': 638, 'लन्दन': 639, 'मनोदशा': 640, 'लॉस': 641, 'कॉलिंग': 642, 'चिरंतन': 643, 'or': 644, 'लछमणसिंह': 645, 'वीसदी': 646, 'भाई': 647, 'बंगलौर': 648, 'शिक्षाप्रद': 649, 'बचाने': 650, 'हैं-अशरीररी': 651, 'थी.बचे-खुचे': 652, 'किसीप्रकार': 653, 'उतार-चढाव': 654, 'रुकना': 655, '(1943)': 656, 'दिलाकर': 657, 'व्यक़्तिनिष्ठ': 658, 'वाटरलू': 659, 'बहुर्तसे': 660, 'पड़ेगा।': 661, 'यॉर्कशायर': 662, 'खंखारकर': 663, 'नेताजी': 664, 'PBSसीमावर्तीअक्तूबर': 665, 'ठहरकर': 666, 'तरंगे': 667, 'अमीरात': 668, 'लतपत': 669, 'सहित)': 670, 'गुणसेन': 671, 'टूरिज्म': 672, 'लडऋखडऋआते': 673, 'निर्धारक': 674, 'पेज': 675, 'मोड़ो': 676, 'चिन': 677, 'उपाख्यानों': 678, '::': 679, 'बादल': 680, 'वसल्लमका': 681, '1998': 682, 'स्मृतियों': 683, 'बर्रेट': 684, 'भौतिकता': 685, 'औरेकल': 686, 'बचाली।': 687, 'दिया,': 688, 'आइएल-76': 689, 'माँगा.': 690, 'Zतक': 691, 'भावुकतापूर्ण': 692, 'बंगदर्शन': 693, 'बेहद': 694, 'बजाये': 695, 'प्रावघान': 696, 'कथनी': 697, 'सैकड़ों': 698, 'आदार्नप्रदान': 699, 'मिट्टीं': 700, 'शिकायतें': 701, 'शिवसुख': 702, 'प्रविष्टियों': 703, 'गर्भनिरोधक': 704, 'कांड': 705, 'यहीं': 706, 'उमंग': 707, 'ठ्-ऊण्श्छ्ष्-रडिन्ग्हृ': 708, 'एसोसिएशन': 709, 'ज़मीन': 710, 'प्रशेषनीय': 711, 'बीआइएफाअर': 712, 'काश्मीर': 713, 'ब्रह्मगुप्त25': 714, 'कृष्णचंद्र': 715, 'कि।': 716, 'उम्मीदों': 717, '(other': 718, 'निर्वस्त्र': 719, 'प्रद<a': 720, 'आदेश-निर्देश': 721, '01624': 722, 'धनंजय': 723, 'लुटेरों': 724, 'सट्': 725, 'छोडा,': 726, 'संषेचित': 727, 'संवेदना': 728, 'पुता': 729, 'पल्लवों': 730, 'किन्हें': 731, 'ब्रौन': 732, '1947': 733, 'संघों': 734, 'डुबा': 735, '(हाल': 736, 'करूँ.': 737, '८०००': 738, 'तंत्रिकीय': 739, 'महान्यायवादी': 740, 'लड़ेकियों': 741, '60': 742, 'मानव-निर्मित': 743, 'व्यहवार': 744, 'denominators': 745, 'लेर्खानियंत्रक': 746, 'गठन': 747, '(Run': 748, 'अनुभूतियों': 749, 'ढर्रे': 750, 'एंग्लो-इंडियन': 751, 'उप-चुनावों': 752, 'छुट्टियां': 753, 'उदाहरणार्थ': 754, 'निस्संगता': 755, 'युक्तियां-': 756, 'फिरोज़': 757, 'दर्जे': 758, 'ऐक्सक्लूज़न': 759, 'दर्शाया': 760, 'आधी': 761, 'यड़': 762, 'कालखंड': 763, '१९६५': 764, 'विवादों': 765, 'पंक़्तियां': 766, 'स्पष्ट': 767, 'भारोत्तएलन': 768, 'अथर्ववेद': 769, 'रहेनगोल्ड': 770, 'विवाहित': 771, 'सेक़्शन-के': 772, 'भेजें': 773, 'सार्वजनिक़': 774, 'कर्मचारीवृंद': 775, 'राजपूताने': 776, 'पाएगा।': 777, 'वट': 778, 'ओह': 779, 'विमानक्षेत्र': 780, 'कर्जन': 781, '38%': 782, 'मज़ेदार': 783, 'रॉकेट': 784, 'तुड़ि': 785, 'सगोत्री': 786, 'पेपल': 787, 'नाव': 788, 'शिवगय्यां': 789, 'नरेंद्र': 790, 'अभिकरणों': 791, 'विवेकपूर्ण': 792, 'पढ़ाया': 793, 'मतलब,': 794, 'चारे': 795, 'एहसानमंद': 796, 'अधिवृषण': 797, 'वेदों': 798, 'वाड़िया': 799, 'यूएनपी': 800, 'कार्टूनिस्टों': 801, 'पारिभाषिक': 802, 'मुरारीपुकर': 803, 'तीनों': 804, 'आदित्य': 805, 'समीकरण': 806, 'आजीवन': 807, 'छोते': 808, 'तल-प्रक्षिप्त': 809, 'वर्णमाला': 810, 'कायिक': 811, 'अलीगढ': 812, 'सीध': 813, 'खरीदी': 814, 'न्यूरोपेथी': 815, 'जनमेजय': 816, 'अनौपचारिक': 817, 'गीतों': 818, 'हस्त': 819, 'है.इसका': 820, 'बिम्बसार': 821, 'आलोचक': 822, 'अव्वल': 823, 'पराया': 824, 'शहादत': 825, 'द्वीर्पसमूह': 826, 'तक-क्रम': 827, 'बधाई': 828, 'वित्तपोषण': 829, 'निर्णायक': 830, 'ठेस': 831, 'रही': 832, 'हद': 833, 'उपाधऋ-ऊण्श्छ्ष्-यक्ष': 834, 'बल्ला': 835, 'विभावती': 836, 'धाराओं': 837, 'जुर्रत': 838, 'पशऋ-ऊण्श्छ्ष्-चिम': 839, 'हिंदू-मुस्लिम': 840, 'कमजोर': 841, 'क्लेरमोंट': 842, 'आरएसएस': 843, 'पाण्डव': 844, '39.4': 845, 'गया.बाद': 846, 'मनोभावों': 847, '1,100': 848, 'मेहराब': 849, 'सर्वोच्चस्तरीय': 850, 'काव्य': 851, 'बेहोश': 852, 'स्थूल': 853, 'संशोधनों': 854, 'होनेवाले': 855, 'बहरे': 856, '‘प्रेम': 857, 'भरतनाट्यम': 858, 'विल्कुल': 859, 'samaoM': 860, 'वैविध्यकरण': 861, 'कली': 862, 'खद्य': 863, 'सोवरिंउटी': 864, 'भतीजे-भांजो': 865, 'बनवा': 866, 'Gandhi': 867, 'औसतन': 868, 'क्लीनिकल': 869, 'मसौदा': 870, 'फोर्स': 871, 'सीलन-भरी': 872, 'साढै': 873, 'भंडार': 874, 'दीं।': 875, 'त्Lतलियां': 876, 'जरुरी': 877, 'बल्लेबाजों': 878, 'पऋधे': 879, 'मैं।': 880, 'परिणामस्वरुप': 881, 'विशेषरुम': 882, 'थे.संपनऋ-ऊण्श्छ्ष्-न': 883, 'extreme': 884, 'प्रशस्त': 885, 'परमिटस': 886, 'बरसात': 887, 'बाइस': 888, 'शीत': 889, 'फट': 890, 'मीडियम': 891, 'थैली': 892, 'हयात': 893, 'राजेन्द्र': 894, 'समझता': 895, 'इसीलिए': 896, 'Council': 897, 'बदलवाना': 898, 'सकी।': 899, '(pornography)': 900, 'दुष्प्रभाव': 901, '२९३३': 902, ']': 903, '[1571]': 904, 'Apte)': 905, 'America)': 906, 'में.': 907, 'Protocol)पर': 908, '(possible': 909, 'की-जहां': 910, 'नोटों': 911, 'सेवक': 912, 'पुणे.': 913, 'द्वार्रद्वार': 914, 'इंद्रधनुष”': 915, 'सोसइटी': 916, 'पाले': 917, 'साम्राजयवाद-विरोधी': 918, 'दुर्गति': 919, 'फॉर': 920, 'विषयवस्तु': 921, 'बंजारे': 922, 'अक्षर': 923, 'भग़्नावशेष': 924, 'पैकेट': 925, 'अटकलबाजियों': 926, 'सिक़्के': 927, 'फ्राई': 928, 'विंड़': 929, 'स्पा': 930, 'ऑटोरिक्शा': 931, 'baD': 932, 'नापसंद': 933, 'छेदक': 934, 'सकने': 935, 'परिसंघात्मक': 936, 'कोपनहेगन': 937, 'परिष्कृत': 938, 'विधिमान्य': 939, 'चलाता': 940, 'भाषण': 941, 'तबाह': 942, 'कोटेशन': 943, 'vaalaa': 944, 'प्रकटत': 945, 'छोटे-बड़े': 946, 'ऐइस': 947, 'इण्डस': 948, 'सर्वदल': 949, 'तल्ले': 950, 'नजदीकी': 951, 'हृदयस्थल': 952, 'शल्क': 953, 'असरे': 954, 'चूहा': 955, 'खेद': 956, 'बढ़ते': 957, 'सयता': 958, 'अाने': 959, 'बहुदेववाद': 960, 'ह्क्का': 961, 'हृदय-से-हृदय': 962, '519': 963, 'क़्विलन': 964, 'हुजूरी': 965, 'टीटो': 966, 'हैं.आउट': 967, 'एसबेस्टोसिस': 968, 'अवैध': 969, 'हेरफेर': 970, 'दोपहिया': 971, 'ऊल': 972, 'शिल्पकला': 973, 'भट्टं': 974, 'बैठता': 975, 'बुद्ध्': 976, 'बेरूत': 977, 'करनाल': 978, 'वार्ड़न': 979, 'रेलवे': 980, 'पांडिचेरी': 981, 'निरा': 982, 'खामी': 983, 'guitar)वीडियॊ': 984, 'थे.': 985, 'झूठा': 986, 'बानो': 987, 'पत्नीरूप': 988, 'टहिलियाणी': 989, 'ऊंघते': 990, 'बोल्डर': 991, 'मातृहीन': 992, 'फलोद्यानों': 993, 'हिस्टिरिकल': 994, 'चढ़ते': 995, 'काम-क्रियाएं': 996, 'तत्परता': 997, 'मुद्र्ण': 998, 'एड्स.सेल': 999, 'वीर्य': 1000, 'अ्धेडावस्था': 1001, 'माउथवाश': 1002, 'सविता': 1003, 'ईंटरनेट': 1004, 'ऋषि-मुनियों': 1005, '==': 1006, 'ऑर्डर': 1007, 'बड़ै-बड़ै': 1008, 'पंजों': 1009, 'सकती।': 1010, 'दुष्टता': 1011, 'सरोजिनी': 1012, 'साधु-संतों': 1013, 'नाज़-ए-हिन्द': 1014, 'ग्वाडालूप': 1015, '(Charles': 1016, 'सौफ़्ट्वेयर': 1017, 'सुनाइये': 1018, 'आत्मकेंद्रित': 1019, '1882': 1020, 'दावेदार': 1021, 'सुविधाओं': 1022, 'वंश': 1023, 'एलम्हर्स्ट': 1024, 'उपचिर': 1025, 'भरे': 1026, 'लनी': 1027, 'पूर्वद्रष्ट': 1028, 'तांडव': 1029, '(हालांकि': 1030, 'भाग-': 1031, 'जैसे-जैसे': 1032, 'विकृति': 1033, 'शौक': 1034, 'सिक़्किम': 1035, 'हिजरी': 1036, 'राजनयिक': 1037, 'किलिक्ति': 1038, 'प्रान्त': 1039, 'अमानवीय': 1040, 'authenticity': 1041, '21870': 1042, 'स्वघोषित': 1043, 'अनिस्चित': 1044, 'कार्सिनोजेन': 1045, 'रूमी': 1046, 'लिबरेशन': 1047, 'पक्षो': 1048, 'समस्यायें': 1049, '%).उस': 1050, 'चेम्सफोर्ड': 1051, 'हल्लय्या': 1052, 'वोडगिना': 1053, 'इक्विपमेंट': 1054, 'उत्तर-पश्चिमी': 1055, 'ट्रिब्यून': 1056, 'फैसलों': 1057, 'रंगीन': 1058, '‘द्विवेदी': 1059, 'कमजोरियों': 1060, 'ऊंटनियों': 1061, 'रोकूँगी?': 1062, 'वाणी': 1063, 'जहन': 1064, 'मांग': 1065, 'जल्दबाजी,': 1066, 'सवार': 1067, 'बदरूद्दीन': 1068, 'कर्मचारियॊं': 1069, 'सूचित': 1070, 'मुद्रक:': 1071, '712': 1072, 'यथार्थ': 1073, 'बनी.': 1074, 'अवतार': 1075, 'कोका': 1076, 'रास': 1077, 'देवता': 1078, 'मैसूर': 1079, 'विकास;': 1080, '20-25': 1081, 'आबाद': 1082, 'पोस्टिंग': 1083, 'जोधा-अकबर': 1084, 'पूंजीपति': 1085, 'बाल्को': 1086, 'चलाऋ': 1087, 'रविल्ला:': 1088, 'कहने': 1089, 'चार-पांच': 1090, 'अग्रकय': 1091, 'अम्लों': 1092, 'कर्णाली': 1093, 'गंधहीन': 1094, 'तोह्फ़ा': 1095, 'धुधली-सी': 1096, 'स्वार्थ': 1097, 'आखो': 1098, 'फैले': 1099, 'जन्में': 1100, 'अच': 1101, 'छोड़ते': 1102, 'book)': 1103, 'अहोरात्र': 1104, 'मकबरा': 1105, 'बहुभुज': 1106, 'उद्योगपपियों': 1107, 'अमिश्रित': 1108, 'परशुराम': 1109, 'बौद्धों': 1110, 'पूर्वावलोकन': 1111, 'Zबस्तियों': 1112, 'मैनचेस्टर': 1113, 'फिल्मफेयर': 1114, '(२००९': 1115, 'वंशवाद': 1116, 'ट्राट्सकी': 1117, 'घटी': 1118, 'कैनबिस': 1119, 'अन्तक': 1120, 'सामान्यरुप': 1121, 'become': 1122, 'फरेन्ट्': 1123, 'इंडिया-': 1124, 'त्रुटियां': 1125, '190': 1126, 'सख्त': 1127, 'स्टीक': 1128, 'जुर्माने': 1129, '1005': 1130, 'दृढेता': 1131, 'प्रभावों': 1132, '६१०': 1133, 'लक्ष्मीनारायण': 1134, 'गिर': 1135, 'वितान': 1136, 'हक,दार': 1137, 'पिछड़े': 1138, 'आ-जा': 1139, 'रक्षोपाय': 1140, 'सैय्दों': 1141, 'हैम्ब्लडन': 1142, 'तिलावत': 1143, 'गये': 1144, 'स्तभों': 1145, 'appeals': 1146, 'यूनाइटेड': 1147, 'झुकी': 1148, 'व्यक़्तिगत': 1149, 'संचार:': 1150, 'एटलस': 1151, 'आर्थर': 1152, 'गाड़ियों': 1153, 'इत्यादि': 1154, 'आने': 1155, 'कठिन': 1156, 'हिंसायाम': 1157, '|भाष्': 1158, 'छलांग.': 1159, 'चाहूँगा।': 1160, '?': 1161, 'टोयोटा': 1162, 'मैकाले': 1163, 'गोलकनाथ': 1164, 'अलग,': 1165, 'असंवैधानिक/रद्द': 1166, 'प्राणदान': 1167, 'उत्साहवर्धक': 1168, 'सुबह': 1169, 'कराती': 1170, 'मौंकों': 1171, 'विरक्त': 1172, 'पटेल': 1173, 'ज्हेंपड़ें': 1174, 'साफतौर': 1175, 'हौए': 1176, 'ऋआंति': 1177, 'निलंबित': 1178, 'also': 1179, 'पासऋठोस': 1180, 'सांचे': 1181, 'action': 1182, '9000': 1183, 'कणिका': 1184, 'शारदाश्रम': 1185, 'रूपरेखाएं': 1186, '117.8': 1187, 'थोपा': 1188, 'घटनाएं': 1189, 'बुद्घि': 1190, '[बदलाव': 1191, 'गया.यह': 1192, 'पहले.': 1193, "एक्ट'": 1194, 'कि': 1195, '(hostage)s': 1196, 'पहाडियों': 1197, 'सवालात': 1198, 'क्रियाशील': 1199, 'निस्संदेह': 1200, 'निपुण': 1201, '1602': 1202, 'जळ': 1203, 'धनी': 1204, 'घ्येय': 1205, 'हिल': 1206, 'अखंडता': 1207, 'सर्विसिज़': 1208, 'पछ': 1209, 'कोर्टहृ': 1210, 'अक्षुण्य': 1211, 'ताकतों': 1212, 'विक्रम': 1213, 'बारे,': 1214, 'वाल': 1215, 'लेती': 1216, 'साफ़्टवेयर': 1217, 'काटा': 1218, 'वर': 1219, 'बुराइयों': 1220, 'साधुओं': 1221, 'आयुक्त': 1222, 'बिछाली': 1223, 'ज्यादा-रनों': 1224, 'किताब': 1225, 'ट्रेक-पैडों': 1226, 'खिड़कियों': 1227, 'है!': 1228, 'लगवाना': 1229, '[sa': 1230, 'मेजबान': 1231, '(wildfires).': 1232, 'चित्रों': 1233, 'राजपाठ': 1234, 'निरपेक्षता': 1235, 'मणिपुरी': 1236, 'सिकुड़े': 1237, 'मिला-': 1238, 'अतिशयोक्तिपूर्ण': 1239, 'दावों': 1240, 'वीजा': 1241, 'स्कोरकार्ड': 1242, 'श्रुतलेखन-राजभाषा': 1243, 'पाशा': 1244, 'परमादेश': 1245, 'शीशी': 1246, '१९२६': 1247, 'विकीपीडिया': 1248, 'पीढ़ी-दर-पीढ़ी': 1249, 'भूगोल': 1250, 'प्रभासित': 1251, 'तारा-चक्र': 1252, 'माड': 1253, 'खाद्यकक्ष': 1254, 'अटकलं': 1255, 'रस': 1256, 'कलकारों': 1257,

In [145]:
def word_to_number(sentance , vocab):
  value = []
  for i in sentance:
    value.append(vocab[i])
  return value

In [146]:
word_to_number(["reminded" , "and" , "in"] , eng_word_2_idx)

[18430, 25460, 31066]

In [147]:
# ["English"] , df_subset["hindi"]

In [148]:
temp_for_eng = []
temp_for_hindi = []
for i , j in zip(df_subset["English"] , df_subset["Hindi"]):
  temp_for_eng.append(word_to_number(i , eng_word_2_idx))
  temp_for_hindi.append(word_to_number(j , hindi_word_2_idx))


# print(temp_for_eng)
df_subset["English"] = temp_for_eng
df_subset["Hindi"] = temp_for_hindi

In [149]:
df_subset["English"][100]
df_subset["Hindi"][100]

[26242, 23727, 23555, 12947, 31790, 22851, 30857]

In [150]:
df_subset.head()

   English                  Hindi
0   [9290]   [26242, 7127, 30857]
1  [23804]  [26242, 19125, 30857]
2  [23804]   [26242, 6100, 30857]
3  [23804]   [26242, 1159, 30857]
4  [29185]  [26242, 32444, 30857]

In [153]:
from torch.utils.data import DataLoader , Dataset
import torch

class dataset(Dataset):
  def __init__(self , df):
    self.x = df["English"].tolist()
    self.y = df["Hindi"].tolist()

  def __len__(self):
    return len(self.x)

  def __getitem__(self , index):
    return torch.tensor(self.x[index] , dtype=torch.long) , torch.tensor(self.y[index] , dtype=torch.long)

In [154]:
from torch.nn.utils.rnn import pad_sequence
import torch

PAD_IDX = 0

def collate_fn(batch):

    src = [x[0] for x in batch]
    trg = [x[1] for x in batch]

    src = pad_sequence(
        src,
        batch_first=True,
        padding_value=PAD_IDX
    )

    trg = pad_sequence(
        trg,
        batch_first=True,
        padding_value=PAD_IDX
    )

    return src, trg

In [155]:
train_dataset = dataset(df_subset)
dataLoader = DataLoader(train_dataset , batch_size=8 , shuffle=True , collate_fn=collate_fn)

In [156]:
for i , (m, n) in enumerate(dataLoader):
  print(m.size())
  if i == 5 : break

torch.Size([8, 18])
torch.Size([8, 43])
torch.Size([8, 14])
torch.Size([8, 40])
torch.Size([8, 22])
torch.Size([8, 18])

In [157]:
class Encoder(nn.Module):
  def __init__(self , vocab_size):
    super().__init__()
    self.emb = nn.Embedding(vocab_size , 128)
    self.GRU = nn.GRU(128 , 50 , 3 , batch_first=True)

  def forward(self , x):
    emb = self.emb(x)
    output , hidden = self.GRU(emb)
    return hidden

In [158]:
class Decoder(nn.Module):
  def __init__(self , vocab_size):
    super().__init__()
    self.emb = nn.Embedding(vocab_size , 128)
    self.gru = nn.GRU(128 , 50 , 3 , batch_first=True)
    self.fc = nn.Linear(50 , vocab_size)

  def forward(self , prev_prediction , hidden):
    emb = self.emb(prev_prediction)
    emb = emb.unsqueeze(1)

    output , hidden = self.gru(emb , hidden)
    output = output.squeeze(1)

    prediction = self.fc(output)

    return prediction , hidden

In [159]:
len(vocab_english)

33089

In [160]:
class Seq2Seq(nn.Module):
  def __init__(self , vocab_english , vocab_hindi):
    super().__init__()
    self.encoder = Encoder(len(vocab_english))
    self.decoder = Decoder(len(vocab_hindi))

  def forward(self , english_src , hindi_target):
    hidden = self.encoder(english_src)
    decoder_input = hindi_target[: , 0]

    predictions = []

    target_len = hindi_target.shape[1]

    for t in range(1, target_len):

      prediction , hidden = self.decoder(decoder_input , hidden)
      predictions.append(prediction)

      teacher_forcing_ratio = 0.7
      teacher_force = random.random() < teacher_forcing_ratio

      if teacher_force:
        decoder_input = hindi_target[: , t]
      else:
        decoder_input = prediction.argmax(dim=1)

    predictions = torch.stack(predictions, dim=1)
    return predictions

In [161]:
# import torch_xla.core.xla_model as xm
# device = xm.xla_device()

In [162]:
device = torch.device("mps" if torch.backends.mps.is_available() else ("cuda" if torch.cuda.is_available() else "cpu"))
device

device(type='cuda')

In [163]:
model = Seq2Seq(vocab_english , vocab_hindi)
model = model.to(device)

In [164]:
epochs = 2
learning_rate = 0.001

In [165]:
loss_fn = nn.CrossEntropyLoss(ignore_index=PAD_IDX)
optimizer = optim.Adam(params=model.parameters() , lr=learning_rate)

In [ ]:
losses = []
for epoch in range(epochs):
  total_loss = 0
  for i , (src , target) in enumerate(dataLoader):
    optimizer.zero_grad()
    src = src.to(device)
    target = target.to(device)
    output = model(src , target)

    loss = loss_fn(output.reshape(-1, len(vocab_hindi)),target[:, 1:].reshape(-1))
    loss.backward()

    torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
    optimizer.step()
    total_loss += loss.item()
    if i % 4000 == 0:
      print("1", end="--", flush=True)

    avg_loss = total_loss / len(dataLoader)
    losses.append(avg_loss)
  print()
  print(f"Epoch: {epoch+1} , Loss: {avg_loss:.4f}")

1--

In [ ]:
plt.plot(range(1, epochs + 1), losses, marker="o")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("Training Loss per Epoch")
plt.grid(True)

In [ ]:
torch.save(model.state_dict() , f"model_epoch{epochs}.pth")
torch.save(model.state_dict(), 'model.pth')

In [ ]:
del model
del optimizer
del output
del loss
import gc
gc.collect()
torch.cuda.empty_cache()