<a href="https://colab.research.google.com/github/PriyanshuChaudhary00/English_to_hindi_using_encoder_decoder/blob/main/Hindi_to_english.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# #!/bin/bash
# !kaggle datasets download preetviradiya/english-hindi-dataset

In [2]:
# !unzip english-hindi-dataset.zip

In [3]:
import pandas as pd

In [4]:
df = pd.read_csv("Dataset_English_Hindi.csv")

In [5]:
df.head()

  English    Hindi
0   Help!    बचाओ!
1   Jump.    उछलो.
2   Jump.    कूदो.
3   Jump.   छलांग.
4  Hello!  नमस्ते।

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 130476 entries, 0 to 130475
Data columns (total 2 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   English  130474 non-null  object
 1   Hindi    130164 non-null  object
dtypes: object(2)
memory usage: 2.0+ MB

In [7]:
df["English"] = df["English"].str.lower().str.split()
df["Hindi"] = df["Hindi"].str.split()

In [8]:
df.head()

    English      Hindi
0   [help!]    [बचाओ!]
1   [jump.]    [उछलो.]
2   [jump.]    [कूदो.]
3   [jump.]   [छलांग.]
4  [hello!]  [नमस्ते।]

In [9]:
df["Hindi"] = df["Hindi"].apply(
    lambda x: ["<start>"] + x + ["<end>"] if isinstance(x, list) else ["<start>", "<end>"]
    )

In [10]:
df.head()

    English                      Hindi
0   [help!]    [<start>, बचाओ!, <end>]
1   [jump.]    [<start>, उछलो., <end>]
2   [jump.]    [<start>, कूदो., <end>]
3   [jump.]   [<start>, छलांग., <end>]
4  [hello!]  [<start>, नमस्ते।, <end>]

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 130476 entries, 0 to 130475
Data columns (total 2 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   English  130474 non-null  object
 1   Hindi    130476 non-null  object
dtypes: object(2)
memory usage: 2.0+ MB

In [17]:
df_subset = df.head(5000)

In [25]:
vocab_english = []
for i , sentance in enumerate(df_subset["English"]) :
  vocab_english.extend(sentance)
  # print(sentance)
  # if i == 5000 :break
vocab_english = list(set(vocab_english))
vocab_english = ["<UNK>"] + vocab_english
print(vocab_english)

['<UNK>', 'reminded', 'indira', 'ambitious', 'veterinary', 'instrumental', 'crying.', 'syndicalists', 'smelling', 'distribution', 'energy,', '(ruling', 'elevator?', 'intention', 'began', 'bin', 'stayed', 'total', 'ago', 'aman.', 'resolves', 'dust,', 'motor', 'eats', 'live.', 'rss', 'suit.', 'redundant', 'branch.', 'crisis', '51', 'oriented', 'temples', 'january1763-4', '4,000', 'mindset', 'assent', 'secondary', 'white', 'states', 'supper?', 'middle', 'came.', 'escape', 'massive', 'well-developed', 'dynasties)', 'rejuvenation', 'exercise', 'earlier', 'plague', 'fever', 'naren', 'o', 'niraja', 'bhandar,', 'area', 'director-general', 'burj.', 'getting', 'came', 'nature', 'sq.', '266', 'spoke', 'ideal', '“women', 'feathers.', 'signs', 'contributing', 'exploitation', 'costs', 'supervisor', 'exercised', '47', '1979.', 'appointment?', 'phd', 'go', 'michanary', 'inc,', 'length', 'azhar', 'playmates', 'hogged', 'happen?', 'frame', 'stamp', 'gandhinagar', 'personand', 'hec', 'tea', 'illness.', 'failure', 'motilal', 'disposed', 'little', 'house?', 'factors', 'flooding', 'sms', 'hanging', 'transfer', 'media', 'allowing', 'avatar', 'saxena', 'chirping', 'contributed', 'includes', 'windows?', 'indigenous', 'congratulations!', 'under-trial', '3102', 'impact.', 'charles', 'is', 'optimized.', 'hang', 'monitored', 'bibliography', 'march', 'concept.', 'communalism', 'yajurvedh,', 'explain', 'democracies', 'labour', 'hygiene', 'mint', 'plays', 'application', 'fair', '1922', '1980', 'teacher.', 'jagaran', '35', 'bachchan', 'frequently.', 'constellation', 'picked', 'now?', 'football', 'zindabad.', 'predisposition', "one's", 'delhi', 'waterfall,', 'rl', 'speed', 'matter?', '3100-5600', 'size?', 'study.', 'hair.', 'reproduction', 'hambledon', 'useful', 'rejuvenation.', 'authoritythe', 'terms', '25,000', 'mumbai.', 'chakrabarti', 'cat?', 'procedural', 'problem,', 'scalability', "sun's", 'river', 'observed', 'served', 'oh,', 'teresa', 'charge.', 'inclement', 'netaji', 'unused', 'breaking', 'cats', 'drinks?', 'generally', 'was.', 'one-day', 'tunnel', 'antarraman', 'basketball.', 'reference', '$10.', 'agile', 'calculate', 'rose', 'his', 'celebrated', '1965,', 'sixth', 'chute', 'orissa', 'pendra', 'calling', 'carries', 'rank', 'disciple', 'synthetic', 'aeronautical', 'ganga', 'udder', 'fis', 'acquainted', 'sumitranandan', 'curvilinearcircular', 'shade.', 'incorporating', 'enter', 'excitedly', 'calls', 'heap.', 'librarians', 'irrespective', 'backside', 'similar', 'lipikaar', 'taj', 'rabbit', 'wonder', 'bays', 'terrorised', 'muscles', 'late', 'traffic.', 'develop', 'devtas', 'factory', 'notes.', 'combine', 'socks,', 'work', 'melted', 'senapati', 'grasim', 'battlefield', 'association', 'are.', 'mauryan', 'cultural', 'asbestos.', 'hindi.', 'bhatena', 'abreast', 'winning', 'alternative', 'ambulance?', 'sur', 'yuvraj', 'highest', 'sakalesha', 'existing', 'museum', 'acts', 'innings', 'industries', 'voluntary', 'consulted', 'burning.', '2007', 'it.', 'actions', 'point.', 'mean?', 'flatter.', 'industries.', 'edition.', 'missionary', 'sectioned', 'dangerous.', 'mr', 'general', 'baseball!', 'association.', 'darkness', 'naphtha', 'fuel', 'tackled', '2100', 'measurements.', 'citizens', 'accomplished', 'city', 'ardent', 'khalistan', 'tomorrow?', 'anti-leninist', 'ourselves,', 'manages', 'emperors', 'inhabitants', 'experiments,', 'tourism,', 'shia', 'mentally', 'रख', 'conspiracy', 'avoiding', 'mayo', 'ik', 'fielding', 'u.s.?', 'opposition', 'garments', 'men“”', 'writing', 'prevent', 'survey', 'federal', 'copying', 'owners', 'blindly', 'roundabout', 'religion', 'wifi.', 'lahore.', 'difference', 'stop', 'himalayan', 'elevated', 'unnoticed', 'hub', 'bring', 'accessible', 'included', 'lord', 'glut', 'barabanki', 'pakistan]', 'translate', 'key', 'mobilised', 'gone', 'trail', 'bhagalpur', 'militant', 'vivekanand(12th', 'tata', 'subject,', '3.4', 'karunguzhi', 'studied', 'indoor', 'v', 'apples', 'yes,', 'foreign-made', 'disabled', 'indigo', '1131', 'evoked', 'nation', 'catastrophe', 'relics', "power's", '(development', 'percent.', 'characters', '368', 'khas', 'motifs', 'rotten.', 'pleased', 'no,', 'applied.', 'dirty.', 'sheer', 'hungry,', 'susceptibility', 'estimation', 'merchants', 'kayastha', 'up?', 'firmly', 'quality', 'misuse', ',first', 'instances', 'depends', 'a.m.', 'female', 'civilisation', 'broke', 'oars', 'hurry,', '(which', '12th', 'obtained', 'it?', 'invert', 'madarasa', 'performs', 'tired.', 'occasion', 'how.', 'vedic', 'lenin', 'koala.', 'pradesh,', 'goats', 'methyl', 'over.', 'mountain.', 'aur', 'sal', 'occurs', 'capitalists', 'bugs', 'secure', 'clothing', 'irrigated', 'easy,', 'services.', 'organized', 'software.', 'happy."', 'sari', 'frankly', 'think?', 'biological', 'estates', 'smelled', 'disease', 'naina', 'ease', 'ananth', 'vinayadhara', '(1981)', 'remember.', 'millions', 'inanimate', 'eight-thirty.', 'titht', 'target', 'hello!', 'kulti', 'imprisoned', 'greatly', 'mirzapur,patna,and', 'deaf', 'proverb?', 'harif', 'taliban', 'asia.', 'deals', 'operation', 'ranging', 'so.”', 'google', 'fail.', 'costly', '13th', "dhamayanthi'", 'you.”', 'performance', 'louder', 'resource,', 'thousands', 'imperialist', 'prosecutor', "i've", 'instant', 'typical', 'barrel', 'lewis', 'vogue,', 'advantage', 'fiery', 'planet', 'penalty.', 'self-respect', 'pepped', 'thoroughly', 'views', 'ugly', 'flopped', 'andaman', 'california', 'absence', 'palace', 'bhagwan', 'salient', 'premchand', 'women.', 'taiwan,', 'cloister', 'car?', 'boston.', 'actual', 'wrong', 'perhaps', 'more.', 'membership', 'jacket.', 'movies?', 'action', 'relatively', 'kota', 'back', 'exam.', 'treatment', 'ashtank', 'stability,', 'everest', 'kabir', 'mobile', 'whatever.', '30.', 'provided', 'strong,', 'saharanpur,', 'immutable', 'nonavailability', 'hockey', 'kalyan-dombivili,', '1859', 'tabar', '"it\'s', 'accounts', 'epoch-making', 'only', 'tajmahal', 'elephants', 'saunaka', 'friend', 'jump.', 'catching', 'genius', 'vidur', 'passing', '(0.22', 'should', 'locally', 'music', 'shiva', '2100,', 'charter', 'ablaze.', 'original', 'desk,', 'health', 'smooth', 'contained', 'prescription', 'several', 'tower.', 'least', 'uncertainties', 'danceroom', 'measure', 'their', 'filtering', 'colours/fluorescent', 'flowers', 'arising', 'kilometers)ganga', 'wo', 'e,', 'trouble,', 'rights', 'herbs', 'ganapuraka', 'hitting', 'drink.', 'hoping', "o'clock.", 'deceive', 'medicine.', 'hardships.', 'thar', 'win.', 'ones,', 'succeeded.', 'beer.', 'struggled', 'round', '3:30.', 'examples.', 'parshuram', 'large-scale', 'causing', 'ten.', 'safe', 'week.', 'ahmad', 'sight,', 'prostitute,', 'sc', "we'd", 'bid', 'desk.', 'koloniyom', 'pakur', 'gum', 'ayodhya', 'manifestation', 'respected', 'happen.', 'genital', 'together', 'history.', 'mamallapuram', 'sow.', 'aryans', 'statement.', 'count', 'muhammad', 'required', 'practised', 'auloo', 'whether', 'write.', 'placing', 'reparation', 'regard', 'me."', 'maithili', 'operations.', 'thinks', 'reasons.', 'noise.', 'cake', 'aggravation', 'morals', 'authorities', 'thing', 'peacefully', 'skilled', 'voice.', 'riaz:', 'view', 'practises', "jagran'", 'looked', 'fixed', 'ears.', 'imagine', 'pehele', 'sprung', 'reducing', 'rebuild', 'danger?', 'corner', 'king.', 'comic', 'global', 'affiliation', 'hurry', 'remaining', 'combinations', 'affairs', 'secret', 'rabbi', 'gurubhai', 'curing', 'developed,', "mary's", 'wearing', 'com-', 'liturature', 'tremendous', 'directed', 'ganges', 'light?', 'princely', 'hope', 'to?', 'haksar', 'discount', 'female.', 'evil', 'vehicle', 'minds', 'bank.', 'only,', 'directly', 'okay,', 'pride', 'specific', 'chaudhari', 'cited', 'precious', 'particles', 'august', 'repair', 'watch.', 'habit.', 'front.', 'blue,', 'expenditure', 'mobility', 'computer?', 'dealer', 'ami', 'refutation', 'varieties', 'thing.', 'scenarios', 'non-partisan', 'monopolistic', 'islam.', 'andamans', 'park.', 'secretary', 'breath,', 'book', 'universities', 'skating.', 'sumru', 'events', 'advantages', 'smiles.', 'structure', 'god,', 'astrologist', '3', 'uncut', 'sushma', 'year!', '100', 'famines', 'tea.', 'tool', 'reap', 'dalit', 'struggle,', 'foretold', 'substance', 'punished', 'collectively', 'discover', 'daal', 'kumar.', 'reaction', 'well,', 'uses', 'disclosing', 'language),', 'moment.', 'by', 'wishes', 'incorporate', 'regret', 'brahma', 'stroke', 'sat', 'suddenly.', 'apple.', 'mud', 'khan', 'engaged', 'approved', '1947,', 'waterway', 'good', 'child,', 'survive', 'bottle', 'ago.so', 'male-specific', '=', 'user', 'girls.', 'sheets', 'mountains', 'lyrical', 'cancer,mesothelioma(it', 'infant', 'calcutta', 'index', 'rekahayein.', 'autumn', 'eggs.', 'lame', "chawla's", 'telemedicine', 'money', 'village', '1999.', 'taxed', 'wickets(', 'sign', '...', 'presidential', 'network', 'anjuman-i-islam', 'critisizing', 'registered', '1979-80', 'fusion', 'cough', 'expect', 'continual', 'ocean,second', 'subhashbabu', 'south', 'quick.', 'competed', 'periods', 'ram', 'california.', 'fortnight', 'miniaturization.', 'dangers', 'ca:', 'disinterest', 'dial', 'buddhism', 'casts', '2005,', 'districts', 'fever.', 'room?', 'symbolised', 'ravaged', 'earmarked', 'ironically', 'situated', 'impass.', 'cleaning', 'battingthat', 'finger.', 'feynman,', '“well,', 'generation', 'segments', '1956', 'sticks', 'ground.', 'declined', 'cities', 'section:east', 'enactment', 'needs', 'harmful', 'sending', 'fat', 'sweater', 'horse.', 'things', 'clogged.', 'advising', 'participation,', 'listened', 'monetary', 'vidhata,', 'abstract.', 'warming', 'bounds', 'graduate', 'meaningful.', 'artist.', 'lyall', 'anything', 'lexicographers', '(e-paper,unicoded)', 'tariff', 'tekchand', 'superintentant', 'vimana', 'poverty', "brahma's", 'everything,', 'mahanadi', 'bet', 'dozen', 'sijistan', "'bade", 'consumers', 'nepali', 'killed', 'witnessed', 'advent', 'health.', 'database', 'pianist.', 'standing', 'lateral', 'official', '21st.', 'preapproved', 'imperialism', 'drama', 'governments?', 'pocket', '27', 'drenched', 'dark', '50,000', 'scholars', 'special', 'extensions', 'cried.', 'job', 'true', 'babu', 'canada?', "pandu's", 'prosecution', 'clot', 'surdas.', 'metabolism', 'tobacco.', 'drove', "raj's", 'revolution,the', 'idol', 'appearance', 'bed', 'awasheshne', 'ranges', 'daytime.', 'warranty', 'encounter', 'crudest', 'challenge', 'independently,', 'milk.', 'realize', 'fulfill', 'thereby', 'dhanbad', 'vikramaditya', 'deputy', 'proceed', 'narasimha', 'prejudice', 'ramalinga', 'colony', 'fast.', 'tables', 'minar,', 'time.', 'horn.', 'weeks.', 'festivals', 'expressions', 'this.', 'sacrificing', 'helmet,', 'bed!', '685682', 'drink', 'keeping', 'udahrano', 'betcha.', 'rupnnie', 'possibly', 'cat?”', 'hello', 'garden', 'tajmahal(vary', 'illiterate', "[you'll", 'scottish', 'internationl', 'proves', 'channel.', 'assaulted.', 'capital.', 'dire', 'caught', 'methods,', '!', 'revolution', 'circumstances.', 'masterpieces', 'scientific', 'as,', 'ago.', 'contact', 'definitely!', 'launching', 'stripped', 'dalits', 'discretion', 'hips', 'breathed', 'proved', 'troposphere', 'which', 'sabha', 'repeated', 'treaties.', 'now', 'coins.', 'cooker', 'arguable', 'saver.', 'fined', 'octagon,', 'liberty', 'judgment', 'me', 'genuine', 'feature', 'disorderly', 'interactive', 'strategy,', 'ag:', 'ashamed', 'retire', 'alpa', 'representations', 'insights', 'timely', 'rest', 'yashaarat', 'conquests', 'poor,', 'ultimate', 'toilers', 'adhishthana', 'regime', 'air.', 'chatta', 'assurances', 'mosques', 'respective', 'turn', 'oppose', 'ulfa', 'proportions', 'avoided', 'permament', 'gopichand', 'harbinger', 'try.', 'cave-temple', 'seeing', 'dpc', 'dainik', 'persian', 'snails', 'pew', 'inclined', 'dictionary,', 'chair.', 'marriage.', 'list', 'counting', 'tom', 'september', 'saying,', 'settlement', 'deliver', 'propaganda', 'ex-', 'cloth', 'commit', 'nationalist-secessionist', 'sinha', '“huh!”', 'residents', 'counted', 'cake?', 'crossing', 'fractures', 'socialist,', 'downloaded', 'sleep', 'energy', 'us?', 'advances', 'swimming.', 'non-spanish', 'library', 'ability', 'kms.', 'arrangements', 'schools', '375', 'school', 'script', 'presumably', "they're", 'researches', 'trajectories', 'voting', 'reduced', 'barabaki', 'opened', 'earning', 'appreciate', 'expressly', 'because,', 'races', 'itself', 'line,', 'whoredom', 'deprecated', 'algorithms', 'echo', 'bullocks', 'appears', 'youngster.', 'amend', 'rare', 'humans.', 'doctor', 'employment', 'barely', 'sub-branch', 'boys.', 'simple', 'grandmother.', 'galaxy', 'daulatpur', 'places', 'prove', 'kochler,hans', 'unauthorised', '(maharashtra', 'backafter', 'vaishmpayan', 'name', 'wide', 'bhagirath', 'stone', 'dedicated', 'cats.', 'in,', 'height', 'nandeesh', 'lawyer', 'german.', 'write', 'milestone', 'bungling', 'murderer', 'plastics', 'run,', 'lack', 'addressed', 'grown', 'maintain', 'speaker,', 'selvam', 'low', 'hay', 'watch', 'references', '“no', 'leaving', 'concerned', 'rounds', 'weak', 'all', 'stadium', 'excluded', 'science,', "ravana's", 'p+q', 'advancing', 'learning.', 'last', 'base,', 'drop', 'rubber', '50,000.', 'formats.this', 'bill', 'pieces.', 'dhimee', 'multiple', 'sainiks', 'brahmaputra', 'indefinitely', 'techniques', 'solution', 'reconciliation', 'completion.', 'devote', "aren't", 'damage', 'exploration', 'anti-islam', 'suddenly', 'crafts,', 'fundamental,', 'ghoda', 'hereditary', 'manufacturing', 'categories', 'broken', 'banned', 'scarcely', 'asssembly', 'roundtable', '1471481', 'group,', 'bullet.', 'duryodhan', 'utensils', 'republican', 'tragedy', '“”aanar“”(sparkling', 'high-end', 'disabilities', 'perdvi', 'trip', 'train.', 'suo', 'approaching', 'haemorrhage', 'levies', 'lady', 'pallava', 'barack', 'skilfully', 'whilein', 'terminology', '324[1],', 'catch', 'rice', 'robot.', 'higher', 'umar', 'might', 'kutch', 'wicket.', 'clam.', 'clinton', 'superintendent', 'confluence', 'changes', 'dna.', 'forgetting', 'tons', 'smoke.', 'ada', 'delineates', 'exclusionhe', 'coal', 'safety.', 'detail.', 'readers,', 'french', 'do?', 'kill', 'dim', 'locked', 'underestimated', 'rudyard', 'turtles', 'grandmother', 'accustomed', 'whereas', 'area,', 'afine', 'agone', 'kind', 'ups', 'referred', 'acreage', 'nawjawan', 'overseas', 'emerge', 'ruled', 'squatter', 'jrson', 'elections', 'children', 'receive', 'bhangalpur.', 'minds,', 'concened', 'self-financing', 'jews', 'samser', '“”sam', 'ball', "what're", 'bold', 'housework.', '12', 'made.', 'somewhere?', 'sunga,', 'story?', 'match.here', 'isocyanate', 'while', 'does', 'dehati', 'same', 'alphabetical', 'increasingly', 'portraits', 'boarding', 'scbaceous', "century,country's", 'ghaziabad,', 'exposed', 'disagreement', 'through', 'mother', 'last.', 'thirteen', 'holiday', 'boon', 'features:full', 'principlea', 'every', 'waliullah', 'comparable', 'spend', 'tibetan', 'coinciding', 'panchal', 'walk.', 'hungry', 'calligraphy', 'i', 'chauvinism', 'force', 'negotiations', 'politicians', 'recently,', 'halebid', 'loyalty.', 'stick', 'road.', 'subba', 'fail', '(', 'f)', 'struggling', 'cafe?', 'wish', 'word', 'constructed', 'inside.', 'sums', 'countries.', 'खुला', 'twenty-four', 'it,', 'ats-107', 'bulls.', 'literally', 'appreciation', 'pinching', 'regulating', 'choices.', 'pictures', 'machine', 'asked', 'sitting', 'staying', 'inflated', 'pant', 'cliff', 'arbitrators', 'island.', 'forest', 'shatrughan', 'contains', 'ad-on', 'follow', 'makka,', 'below', 'box', 'established', 'sung', "'re", 'go,', 'benefit', 'attended', 'sinner', 'frustration', 'ache', 'closed.', 'dissolved', 'number?', 'akin', 'literature.', 'moneylenders', 'ws', 'devices', 'athlete', 'canal', 'described', 'balkh', 'get', 'jamshedpur', 'cursed', 'written', 'cow', 'arguing', 'returning', 'social', 'campaign.', 'divine', '2000', 'parents.', 'cheek', 'complains', 'done.', '80', 'bat,', 'vivan', 'difficulty', 'evening', 'typing', 'vessel', 'players', '105', 'governor', 'turning', '(kings', 'monuments', 'published', 'excellent.', 'carry', 'connection.', 'bicycle', 'angry', 'man,', 'prefer', 'cells)', 'historic', 'friday.', 'happened', 'television?', 'compounded', 'setting', 'recommended.', 'palanquins', 'disposing', 'find', '1985', 'nagesh', 'mate', 'amazing.', 'twin', 'toholoo', 'govind', 'thick', 'terrorism', 'sad', 'collects', 'teach', "(1998)'", 'undue', 'useful.', 'interpretative', 'sister.', 'culture,', 'pencils.', 'how,', 'linked', '1998', 'good,', 'exemption', 'stay', 'badami', 'nudity,', 'types', 'drafting', 'absolute', '262', 'chinese.', 'attention,', 'cabinet', '“blue,', 'season.', 'arise', 'exacerbate.', 'lay', 'defined', 'posts', 'quarters,', 'portals', 'fateh', 'indicate', 'functions', 'refused.', 'say', 'affecting', 'fernandes', 'world.', 'spent', 'attacked', "“you've", 'altering', 'locals', 'quiet', 'test', 'gypsum,', 'planned?', 'successful,', 'putro', 'producing', 'cantankerous', 'links', 'note', 'sinking', 'hindus', 'volatile', 'gems', 'page.', 'ship', 'tired?', 'bear', 'accidents', 'power', 'music,', 'ingots', 'broken.', 'unique', 'zoo.', 'maine', 'possible,', 'feels', 'sunday.', 'medical', 'desirable', 'weekend.', 'subrahmanya', 'state', 'valid', 'temperature?', 'nice', 'direction', 'any', 'servant.', 'text', 'spending', 'revolt', 'surrounding', 'acclaimed', 'headlines', 'salt', 'countryside.', 'seventeen.', 'conscious', 'important,', 'prevailing', 'superior', 'that,', 'differ', 'genetic', 'burma', 'silent.', 'solid', 'motivation', 'miles', 'wiktionary)', 'balram(1980),', 'unbelievable!', 'often', 'know', 'employs', 'production-the', 'experiments', 'complex', 'jharkhand.', 'moment', 'john.', 'burned', 'pardon', 'seller', 'foot.', ',', 'subunits', 'court.', '10.', 'severe', 'lie.', 'vacancies', 'feed', '2008,', 'session', 'killers', 'called.', 'feast', 'crazy', '153,090', 'rishi', 'bathroom.', 'is.', 'narrow', 'wants', 'parking.', 'elations', 'question.', 'motherland', 'restrictions', 'french.', 'insignificant', 'subhas', 'thumbs', 'neglect', 'visvabharati', 'copyrighted', 'contacts', 'bottom', 'motioned', 'casual', 'sultans', 'understand,', 'osaka.', 'produced.', 'behalf', '3,200', 'minutes', 'aslthe', 'valley', 'yet.', 'variations', 'matter.', 'picture,', 'shrank', 'buddhist', 'danger', '<number>)', 'main', '13,662,885', 'young', 'sallallahu', 'vidhyalaya“”,', 'mouse.', 'product', 'whoever', 'favor', 'contract,', 'nepalese', 'accident.', 'mover', 'possible.', 'hire', 'tmj', 'sages,', 'smog', 'china.', 'tanks', 'rich.', 'messaging', 'tom?', 'proposal.', 'quality.', 'tirup-parankunram', 'merit', 'sutured', 'andhra', 'thirsty.', 'skanda', 'moods', '1989', 'website.', "janamejaya's", 'cafeteria.', 'taste', '949].', 'camps', 'beleaguered', 'brahmins.', 'grasses', 'good-sized', 'recesses', 'ground', 'decisions', 'beauty.', 'measured', 'this?', 'visit', 'sex', 'senierio', 'unbalanced', 'new?', 'billowing,', 'tears.', 'discussing', 'tiger', 'prided', 'bats.', 'austere', 'guaranteeing', 'achieved', 'dispassionate', 'revolution.', 'conduct', 'kurushetra.', 'rumor', 'hopes', 'airy-fairy', 'prisoner', 'anger', 'furniture.', 'following', 'tone', 've', 'maharshi', 'vitro', 'l', 'breakthrough', 'blog', 'available.', 'volume', 'pradesh', 'male', 'pay,', 'shouted', 'destroyed.', 'business.', 'mountains,', 'sudden,', 'security', 'poems', 'gills', 'pretty.', 'deep', 'harmless', '100.nakki', 'power.', 'ligament', 'पाएँ', 'kabeer', 'danveer', 'wrote', 'poisonous.', 'wear', 'kids?', 'plants', 'schedule', 'impolitic', 'warming“”', 'input', 'procedure', 'soldiers', 'molecular', 'jaishankar', 'myanmar', 'sail', 'acceptance', 'words', 'attracted', 'dilip', 'rivers', 'bored', 'excluding', 'using', 'energy:', 'debt', 'arabic.', 'form,', 'etc', '149%', 'survived', 'released.', 'address.', 'metempsychosis', 'worry', 'praised', "you'll", 'water', 'pay.', 'give', 'league', 'such', 'smoke?', 'respectively.during', 'ice.', 'art', 'practicable', 'himself.', 'leads', 'filed', 'to', 'quitting', 'african.', 'personally', 'earthquake', 'assistant', 'diesel', 'away!', 'diseases', 'sikri.', 'bloom.', 'identify', 'hindutva', 'bholanath', 'towns', 'subash', 'fastened', 'users', 'matter', 'sangha', 'htr', 'kid.', '(n

In [26]:
vocab_hindi = []
for i , sentance in enumerate(df_subset["Hindi"]) :
  vocab_hindi.extend(sentance)

  # print(sentance)
  if i == 5000 :break
vocab_hindi = list(set(vocab_hindi))
vocab_hindi = ["<start" , "<end>"] + vocab_hindi
print(vocab_hindi)
print(len(vocab_hindi))

['<start', '<end>', 'घरवालों', 'व्यापक', 'नियमित', 'गणितीय', 'श्रेणी:ताजमहल', 'जवाहरलाल', 'स्पेनी', 'ग़ुलाम', 'गीले', 'लोलक', 'छोड़', 'बडऋआ', 'यज्ञ', '११३१', 'पशुओं', 'दिन', 'बुलाएँगे।', 'लिखा', 'मानवजाति', 'प्रेम', 'आपत्ति', 'करो,', 'रहती', '51', 'सूँघ', 'गिरि', 'मंडप', 'पीली', 'टालने', 'मुसलाधार', '4,000', 'राज्यों', 'दूर', 'सुनते', 'मज़दूर', 'वार्ता', 'सूरसारावली', 'मेने', 'फलती', 'शाकाहारी', 'श्रेष्ठता', 'मूर्खता', '(प्राकृतिक', 'मांसाहारी', 'लाभांश', 'लघुरूप', 'हानिकर', 'उद्देश्य', 'तर्कों', 'खेती', 'पड़ता', 'साम्राज़्य', 'कीमती', 'पहिए', 'वस्तुएं', '266', 'हँसे।', 'कालखंड', 'सोनिया', 'कार्लचऋ', 'अक्टूबर', 'खलीफा', 'पुराना', 'जाए', 'विवादी', 'XI', 'जनवादी', 'सैमसंग', '47', 'लगाई।', 'योग्य', 'करवाया।', 'परिवहन', 'कयोंकि', 'दिखाऊँगा', 'छोड़ूँ?', 'किताब', 'सहमत', 'अभ्यास', 'ताल्लुक', 'उपायों', 'कदमः', 'ख़त्म', 'ढक', 'कारण', 'बांग्लदेश', '(air', 'रु', 'संग', 'आएगा।', 'डालें।', 'य', 'मुलाकातें', 'तक.', 'थी,', 'उत्साहित', 'निकटता', 'सहते', 'काकी', 'अलग-', 'मूँगफलियाँ', 'मण्डप', 'प्राइसेज', 'महालेखानियंत्रक', 'महाराष्ट्र', 'निवासियों', 'जातीय', 'मछवारे', 'एटीपी', 'विवेकानन्द', 'था,', 'is', 'है.स्त्रियों', 'पुत्र', 'पीढ़ियों', 'खासकर', 'क्रम.', 'डीज़ल', 'हुए।', 'आयु', 'जंगल', 'गुंबज', 'अणु', 'सहने', 'दूसरा', '(coal)', 'रणनीति', 'हैया', 'टी-शर्ट', 'छूटता', 'सुधार', 'चुनौती', '1922', 'डालते', '1980', '35', 'भगतराम', 'शताब्दी', 'लाईन', 'जुटाने', 'हलाँकि', 'सके।', '१५४२', 'सुनाया', 'हें', 'निति', 'जाता।', 'बटुए', 'संघात्मक', 'ऊंचा', 'इत्यादि', 'गिनती', 'प्रयास', 'सरस्वती', 'चुनाव', '25,000', 'होने', 'सन्दर्भों', 'भगीरथ-तपस्या', 'आन', 'पूछने', 'अधीक्षक', 'Control', 'जगत', 'फोटोग्राफ़रों', 'हिल', 'प्राण', 'शरद', 'बङी', 'बाराबंकी', 'झोब्चेन्ट्रे', 'थक', 'काटा', 'तौलिया', 'स्थापत्य', 'ट्रैफीक', 'मिनी-USB', 'अनंत', 'बारहवीं', 'पूर्ववर्ती', 'सांप्रदायिक', 'एशोसिएशन', 'ना?', 'वरिउष्', 'अभी-अभी', 'लंबाई', 'क-ख-ग-ध', '(scenarios)का', 'काम', 'अंदमान-निकोबार', 'hO', 'रू-ब-रू', 'बनाओ।', 'गमन', 'दौरे', 'उत्तरी', 'सर्वतोभद्र', 'जवाब', 'काफी', 'विषय', 'तरह', 'भैमका', 'अभिकल्पक', '(climate', 'टेक', 'कही', 'वफादार', 'जैन', 'था', 'बोलिए।', 'युद्ध', 'अर्ध-चंद्राकार', 'ताज', 'खेतों', 'शास्त्र', 'पूर्वाध', 'सदृश', 'रेखांकनों', 'conduct)निषिद्ध', 'मामले', 'श्रमिकों', 'किए।', 'ग्रैंड', 'हत्या', 'लौह-प्रगालन', 'अरूट्पा', 'पानी', 'भाव', 'विधानमंडल', 'टॉयलेट', 'मिलेगा।', 'भिड़', 'हवाऋ', 'Zदक्षिणपंथी', 'ग्रुप', 'मामूली', 'मेयो', 'चाबी', 'हफ़्तों', 'तीनों', 'युवराज', 'घमंडी', '५८०', 'घटक', 'हिन्दुओं', 'काल', 'प्रयासों', 'गणेश', 'दीमक', 'आधारशिला', '(runs)', 'सूर्य', 'अगला', 'जॉर्ज', 'हैं.टेस्ट', 'सर्वमान्य', 'बैठिए।', 'वक्ररेखी', 'अपनाया', 'रेटिनल', 'अतः', 'नवीनतम', 'लगा,', 'फ्लड', 'हुये', 'कमा', 'पकाया', 'इतनी', 'ट्रायंगुलर', 'गोलाबारी', 'संश्लेषण', 'सयता', 'शाप', 'रहिए।', 'आउटपुट', 'दिलाने', 'रोमांचक', 'प्रतीक्षा', 'हवाईअड्डे', 'खरीदीं।', 'सिरिंज', 'पावरबोट', 'यहां', 'गो', 'तोला।', 'धक़्का', 'इस्राइली,', 'अभिमान', 'पाया', '2100', 'ऊष्ण-कटिबंधीय', 'अथर्ववेद', 'जैसा', 'हानिकारक', '(single', 'भक्त', 'इंडोनेशिया', 'नज़र', 'सेल', 'उड़ाओ।', 'कांग्रेसी', 'निचले', 'सिकुड़', 'प्रतिशोधपूर्ण', 'रख', 'मेथड्स', 'जाने?', 'पड़ोसी', 'संघीय', 'बच्चे', 'कूदो।', 'ललित', 'निभता', 'कूद', 'खुद', 'तानाशाही', 'धीरे-धीरे', 'उस्मान', 'मृतक', 'कर्ताओं', 'ट्यूमर', 'भेजने', 'आपूर्ति', 'नहीं।', 'वोह', '(Bade', 'उत्सुकता', 'टेस्ट', 'मान्यता', 'शिपयार्ड', 'इनका', 'भैया', 'फ़ीडे', 'बृज', 'खोलिए।', 'हिन्दुस्तान', 'निवासी', 'उछल', 'निदान', 'सोविएत', 'बताने', 'फ़रिश्तों', 'बार।', 'सदा', 'इमारतें', '3.4', 'लड़कियों', 'झोंक', 'अलावा', 'तकनलाजी', 'बावर्ची', 'ख़राब', 'मुस्लिम', 'सुचारु', 'परीक्षा', '(2002)', 'clathrate)', '(development', 'जमाने', 'अंडों', '368', 'नकारात्मक', 'आंकड़ें', 'सिन्हां', 'बॅटर', 'करती।', 'ली', 'उत्तरदायित्व', 'मृग', 'तूफ़ान', 'प्रस्तार', 'है.वह', 'जाओ।', 'संतुष्ट', 'नाथा', '१९६४)', 'रहस्योद्घाटन', 'ली।', 'रूपयोजनाएं-प्रारंभिक', 'बेचने', 'मर्यादा', 'प्रांतीय', 'रेगिस्तान', 'लेग', 'स्वतंत्रता', 'आयुर्वेद', 'सकते।', 'सफल', 'करोड़', 'नियोजन', 'उकड़ू', 'बेचना', 'रहीं', 'काव्य', 'मुलाकात', 'सोचते', 'ओस', 'केशव', 'साझे', 'शिलाखण्डों', 'गयामिलियन', 'नियोप्रोतेरोजोइक', 'युक़्त', '२७', 'तैरना', 'विशेषताओं', 'पहुंचने', 'यंत्र', 'बोलना', 'निकेतन', 'सकें,', 'मलें', 'वर्महोल', 'बढावा', 'लिंग', 'वार्षिक', 'कार्यकलापों', 'आकर', 'स्थायी', 'दूसरे', 'पाँचवी', 'ओसाका', 'गर्दन', 'millions', 'राजपूत', 'खेद', 'बलपूर्वक', 'वाले1', 'खट्टा', 'स्थिति', 'पैकेट', 'लैपिज़', 'व्यक्तित्व', '(Lexington', 'रियली', 'ग्रह', 'भारत,', 'इसमे', 'नियमानुसा', 'प्रजापति', 'बेटी', 'जानता?', 'देंगी', 'संकट', 'कोशिकाओं', 'करदो,', 'लड़ने-झगड़ने', 'वजहसे', 'प्रतियाँ', 'लिग्नाइट', 'बाहुल्य', 'अविश्वसनीय!', 'तरीके', 'निबंध', 'टिकट', 'समुज्जवल', 'टाइम', 'बालों', 'झीलों', 'पत्तन', 'मात्रा', 'जिम्मा', 'तत्काल', 'शत्रुओं', 'पहनी', 'जबकि', 'ज्ञात', 'अनुयायियों', 'हिन्दू', 'न्यूजप्रिंट', 'पतली', 'कलाकार', 'अण्डे', 'सुमित्रानन्दन', 'मानसिक', 'उत्पाद', 'बार', 'रुप', 'भुगतने', 'फ़ोर्डाइस', 'खुल', 'मिला', 'थान', 'गया,', 'फिक्सर', '(हंसी)', 'कल्याण-डोंभीवली', 'सुन', 'विद्यार्थियों', 'युकार्योतेस', 'जाऊँगा।', 'डरता', 'कविताओं', 'सती', 'स्थापित', 'बाढे', 'ईस्ट', 'अफ़्रीका', 'तबाही', 'एक्सप्रेस', 'लेकर', 'थे:', 'प्रतिष्ठित', '30.', 'पिया', 'मास', 'गुप्ता', 'सोते', 'पकड़ी', 'तापमान', '102', 'Air', 'Security', 'मोती', 'अटक', 'रखूँ,', 'शास्त्रीय', 'इन्हेरिटेंस', 'ग्रन्थसूची', 'लगादी।', 'तरफ़', 'गारिमा', 'शासनकाल', 'एनर्जी', 'छोटे-छोटे', 'विदेशाई', 'रऋगाऋ', 'शोध', 'वादों', 'आसन्न', 'मुबारक', 'प्रोग्राम', 'पक्तिं', 'ख़तरे', 'अनुभव', '(0.22', 'चाहें', 'दूसरों', 'झगड़ा', 'अहंकारी', 'लाइट)', 'कष्टकर', 'प्रकाशक:', 'जिम्मेदार', 'छूते', 'मिलाली', 'मार्गदर्शक', 'बनाई', 'हैं.आउट', 'सो', 'भराली', 'अंधेर', 'सारी', 'डाली।', 'जोसेफ', 'थनों', 'आपने', 'अनदेखे', 'छूट', 'जमा', 'रिपोर्टें', 'भगवान,', 'बूंद', 'वास्तविक', 'क्षेत्रफल', 'यूनिसेफ़', 'तिवारी', 'शोधों', 'नाचघर', 'लो,', 'गया', 'भिजवादूँगा।', 'जब्त', 'होती', 'घाना', 'शक़', 'मुर्गियाँ', 'जीवन', 'अफगानिस्तान', 'होंगे।', 'विधेयक', 'लेजाओगे', 'रहेंगे', 'चट्टा', 'उठाती', '°F)', 'कीमतें', 'अमरसाल', 'विघटन', 'बनारस', 'दूरी', 'डालकर', 'निकली।', 'नमूना', 'स्थानिय', 'गला', 'केद्रित', 'रहस्यवाद', 'पसंदीता', 'गतिविधियों', 'फ़ेसबुक', 'एवम्', 'टेलीविजन', 'मरने', 'स्कोरर', 'केंद्र', 'चिल्लाया।', 'माऋग', '2पृ', 'शक्ल', 'सदा-भूखे', 'बहुत,', 'हार्मोनों', 'गुड़ेगुड़ने', 'किलोग्राम', 'उठाएं.', 'मदर', 'देवी-देवताओं', 'शब्द', '१९७३', 'भीग', 'सेवन,', '२२४', '(National', 'यात्रा', 'कहेंगे', 'दस-साल', 'वीडियॊ)', 'बी.ए', 'करते-करते', 'सामरिक', 'समीकरण', 'जवानी', 'पार्सल', 'इंदिरा', 'पडऋ', 'दण्ड', 'नयी', '(nudity)', 'दासता', 'शरीर', 'वाल्व', 'ज़िन्दगी', 'वनस्पति', 'सहभागिता', 'मुसीबत', 'बनाने', 'ओवेर्सेट', 'टाइपराइटर', 'जमींदारियां', 'श्रेणी:धर्म', 'कमेन्न्ज', 'अगुआई', 'बेहद', 'साँयः', 'सभापति', 'तीक्ष्ण', 'मेहमान', 'रंगमंच', 'महिलएं', 'पढ़ने', 'पुर्तगाली', 'मीनारों', 'कराते', 'पंद्राह', 'उधार', 'ईश्वर', 'दया', 'खैर', 'अंतर्बाधा', 'तरीको', 'सैय्यद', 'माँगता', 'बरफ़', 'स्टेशन', 'पालनी', 'चार्टर', 'कोशिकीय', 'बिन', 'नाश्ता', 'कीचड़', 'population)के', 'भिवंडी-निज़ामपुर', 'बढ़ावा', 'बहिष्कार', 'हिस्से', 'अवसर', 'आलोचनात्मक', 'विदोश', 'पायी।', 'रिसॉर्सेस', 'सहयोग', 'प्रखर', '(ERT)', 'चेकोस्लोवाकिया', 'विठ्ठल', 'साक्ष्य', 'नस्ल', 'भूलना', 'उड़न', 'सजे-धजे', 'बेटियाँ', 'उड़ते', 'निष्कासन', 'हूँगा।', '(मार्क्सवादी)', 'निर्वाण', 'अरे', 'भाषा-परिवार', 'समता', 'मुआवज़ा', 'पनीर', 'बिस्तर', '43वें', 'मह्ल', 'स्मरणशक्ति', 'उड़ना', 'कविताएँ', 'शब्दावली', 'पीछा', 'हकीकतः', '3', 'उत्पादित', 'प्रधानमन्त्री', '100', 'पाऊँगा।', 'रामानन्द', 'जगन्नाथदास', 'मतलबी', 'उपलब्द्ध', 'ख़ूब!', 'टोंस', 'इसलिये', 'जाना', 'दृढ़', '(disenfranchisement)', 'याददाश्त', 'ऑक्सफ़र्ड', 'हीरा', 'एक-दो', 'सुलाना', 'कालीन', 'मुद्दे', 'समकय', 'फ़्रांसीसी', 'तत्व', 'भरते', 'कोरिया', 'उन्हीं', 'शुलऋ-ऊण्श्छ्ष्-क', 'ठहरा', 'ढनीति', '=', 'जागरा', 'स्याही', 'ल्क्ष्य', 'देखभाल', 'समुंदर', 'अरुचि', 'आता', 'ऐक्सीडेंट', 'प्रवृत्तियों', 'काराई', 'तोड़ो।', 'छात्र,', 'टिपण्णी', 'संवाद', 'पापा', 'मलमल', 'दोहराने', 'लेना-देना', 'स्वायत्तता', 'उभरे', 'सदी', 'खोलो!', 'चाहूंगी,', '(राजनीतिक)', 'रौंद', 'अपर्याप्त', 'मंत्रालय', 'जल', 'प्रकोप', 'दायरे', 'उल्हासनगर', 'स्वीकार', 'पड़ते', 'दीजिए।', '...', 'गवर्नमेंट', 'कक्षों', 'तैरकर', 'ब्रितानी', 'भरती', 'जुटी', 'ब्यौरा', '1979-80', 'पिता', '(domestic', 'पेड़-पौधों', 'कमर', 'जनता', 'विशेष', 'सिक़्के', 'कवायदों', 'अवधारणा', 'देता', 'प्रकाशक', '(VOCs)', 'बढ्ना', '३-वर्षीय', 'एल्गोरिदम', 'उछलती', 'बंगालनागपुर', 'वॉर्मिंग', 'मैसेजिंग', 'मिली?', 'डालदो।', 'मे', 'करूँ', 'मध्य', 'फिक़ह', 'रक़्तस्राव', 'गोलीबारी', 'ख़रीदीं', 'पहनता', 'जेसा', 'तेराब्य्ते', 'आर्टिलरी', 'दामहृ', 'निबंधों', 'पचास-एक', 'ऑस्ट्रेलिया', 'सकेगा', 'बोला।', 'षेसिडेन्टिअल्', 'वर्धमान', 'पन्ना', 'ज़रूर', 'पत्तियाँ', '1956', 'दीवान-ए-खास', 'वैमानिकी', 'ग', '|', 'देवर', 'अस्पताल', 'तैवान', 'तू', 'जूड़े', '(फेरुनुलम)', '(पूर्व', '(plywood)', 'घूम', 'सान्याल', 'समेत', 'रत्न', 'गुलदान', 'करोगे?', 'अलीगढ', 'ललू', 'बोलती', 'बंध', 'अंतराल', 'माँ-बाप', 'अध्यात्म', 'विष्णु', 'हुएँ', 'माने', '(यदि', 'निर्वासनों', 'दूंगा।', 'खंडन', 'Mahatma', 'अनके', 'कोर्ट', 'match)', 'पियानिस्ट', 'वेबसाइट', 'दूँगा।', 'प्रबंधन,', 'फूलन', '१८८८', 'आभा', '२२४/५', 'दुम', 'सार्वजनिक', 'लालकिले', 'बुर्ज', 'आराम', 'इनकी', '(advertisements)और', 'चुट्टांबलम', 'स्वाभाविक', 'प्लैन', 'भूमध्यरेखा', 'फंच', 'आत्मविश्वास', 'सूरदास', 'उम्मीदवार', '27', 'दोपहरभर', 'हमको', 'फैलती', '50,000', 'इनमें', 'गोबोट.', 'अनुशासन', 'Err:509', 'वो', 'वापिस', 'ईर्ष्यालु', 'गरीब', 'कई', 'गवर्नर', '१८८९', 'I', 'सकती', 'पृथक', 'असहमति', 'जाएगी।', 'संस्कृत', 'थे,', '(H2CO)', 'विलोम', 'कहानियाँ', 'अड्डा', 'क्षेत्रॉ', 'पूछें', 'अभिनेताओं', 'करों', 'हिन्द', 'तथापि', 'पद्धती', 'प्रकट', 'यव', 'किंतु', 'खिड़कियाँ', 'अधिकार', 'बैण्टोनाइट', 'योगदान', 'पुराणों', 'बन्द)', 'दिमाग़', 'संगिनी', 'cloud)', 'ट्रिब्यूनल', 'इजसके', 'कपिल', 'एच', '685682', 'से', '“James', 'स्वचलित', 'सामान्यत', 'कीजिएगा,', 'गईं', 'ऑर्डर', 'बजे', 'नीला', 'शक्कर', '(चाहे', 'छोड़ी', 'ये', 'ख़ुद', '१९९१-१९९२', 'पेशियों', 'लगों', 'शायद', '!', 'हालात', 'आंका', 'संस्करण', 'मिश्रण', 'मोड़े,', 'मिलेगी।', 'प्रेमचंद', 'जताई।', 'शाखा', 'गलफड़ों', 'जानती', 'यूट्यूब', 'मोह', 'एवज', 'Board', 'गुण', 'सीमंकी', 'शुरुवात', '(Test', 'प्रथमार्ध', 'नॉट', 'अजनबियों', '\u200eउसने', 'निबटने', 'पहुंचाना', 'संचालित', 'सब्जियों', 'तोदाइजी', 'कमेटी', 'बल्लेबाजो', 'थैलों', 'सुविधाओं', 'वार्मिंग', 'चींचीं', 'गजलक्ष्मी', 'हादसा', 'श्रेणी:संयुक्त', 'ज्ञानकोष', 'आवश्यकता', 'है।', 'गाय', 'करो।', 'मोटरसाईकल', 'खिलड़ियों', 'पड़ा।', 'Available', 'चाहतें', 'की,', '२५%', 'गंभीर', '(१९८१)', 'शैली', 'अलंकृत', 'ईमानदार', 'गृह', 'नये', 'दोनो', 'हॊ', 'इसलिये,', 'दवाईयों', 'फेर', 'कंप्यूटर', 'अपूर्ण', 'मोटी', 'ग्लासिअल', 'रास्ता', 'हवाना', 'कराया', 'लंबा', 'उदा', 'अवशेष', 'विकासात्मक', 'प्रत्येक', 'बंदर', 'साधारणत:', 'मीटर', 'पल्लवों', 'म्युज़ियम', 'नींद', 'मंदिरों', 'लम्बे', 'बाँध', 'स्काटिश', 'फेडरशन', 'आया।', 'डाले', 'आखें', 'कमनीय', 'राजखोसला', 'इसको', 'बूढ़े', 'उत्तओजना', 'चाह्ती', 'उदसे', 'थर', 'नौकरशाह', 'राज्यसंगठन', 'जैसे,आपको', 'क्रीज', 'करदो।', 'अनुमोदनार्थ', 'त्रिकोणीय', 'मकान', 'मुखबिरों', '(हिजरी', 'पंद्रह', 'किसलिए', 'से]', 'गहमागहमी', 'समानित', 'भारती', 'गुट', 'उड़ाने', 'सुदूर', 'भागवत', 'प्रदर्शित', 'स्राव', 'मुझमें', 'उठाते', 'स्थ', '१८५०', 'गोलियों', 'दमयन्ती', 'आलेख', 'लक्षणों', 'रहता', 'घुसादो।', 'अंधकार-युक्त', 'प्रभावी', 'सीखनी', 'गाते', 'जटिलताएं', 'बनाओ”', 'पौधों', 'भार', 'सोमवार', 'शीशी', 'लेना।', 'घर', 'ताकत', 'यूरोपीय', 'terrorism)', 'प्रतियोगितात्मक', 'टाटा', 'Chote', 'बनने', 'कॉलेज', 'सफ़ाई', 'पात्र', 'असत्य-मार्ग', 'टाइपैड', 'खिलाफ', 'ऋषि', '१९४७', 'दरगाह', 'बनते', 'हवाईजहाज़', 'घुमाऊं,', 'विमर्शो', 'व्याख्यान', 'बेहतरीन', 'योग्यता', 'रोमांच', 'लेने', 'मानिए,', 'प्रवाहित', 'अपमानित', 'सकने', 'चोरी', 'कंपनी', 'पाए', 'जया', 'कंबल', '२५००', 'लगभग', 'संवेदनाओं', 'कल्पनाओं', 'आँसुओं', 'मूलभूत', 'बेजा', 'आऊट', 'आपके', 'रहकर', 'सिखाया।', 'नीली', 'हुयी', 'संयोग', 'मानना', 'छीना', 'मारे', 'चालू', 'झलक', 'बनना', 'गत', 'जबरदस्त', '☻☻☻☻☻', 'महज', 'उत्सर्जित', 'खुशकिसमत', 'दुखदायी', 'ब्लॉग', 'फ्रांस', 'सिर्फ', 'बुनियादी', 'अधिसूचना', 'वॉयल', 'विकिरणों', '२०', 'अपेक्षित', 'संवेदना', 'ज़हरीले', 'डी.एन.ए', 'कंजूस', 'बाताऊँगी।', 'दिये', 'बाँट', 'मुहतसिब', 'दुर्घटनाएँ', 'तय', 'एच.ई.सी', 'जिनकी', 'पेंटिंग', 'ग्रंथालय', 'यो', 'तेरा', 'रखा', 'ठहराएगा', 'हटीं', 'प्रस्थान', 'महंगा', 'गुर्दों', 'चिकितऋद्दसासऋद्दथान', 'नेतृत्व', 'विपरीत', 'मुहम्मद', 'रखते', 'गलती', 'वाशिंगटन', 'ऋषि-मुनियों', 'श्रेणी:नोबेल', '१५००', 'अरब', 'विविधतापूर्ण', 'मिथाइल', 'नजदीक', 'निकायों', '(troposphere)में', 'उत्तम!', 'लें', 'वाहन', 'हिन्द-आर्य', 'काटो।', 'समझकर', 'पाएगा।', 'मजबूरियों', 'याचिकादाता', 'पिऊँगा,', 'गीतात्मक', 'बैंड', 'बुआ-जी', 'खिलते', 'सल्फाइड', '60,000', 'पर.', 'वी/एसटीओएल', 'गहरा', 'ऋतुएं', 'घोड़ा', 'आईए।', 'दिखाना', 'बना', 'आयात', 'कजा', 'बारे', 'बजट', 'बकवास', 'पार्लियामेट', '(conflict).संघर्ष', 'पेकिंग', 'मजदूरी', 'प्रातः', 'कोलम्बस', 'विचारशील', 'खान', 'सांस्कृतिक', 'कायल', 'तक,', 'कर,', 'कॉमिक', 'आजमगढ़', 'बोलने', 'विलम', 'कुछेक', 'नियत', 'अलाउद्दीन', 'करूँ।', 'इनसे', 'उछलो.', 'भरना', 'आओ', 'दूरदर्शिता', 'अनधिकृत', 'विवेकाधिकार', 'मंगवाया', 'गठन', 'मंज़िल', 'सामान्य', 'व्यतीत', 'पर्वतों', 'रखनी', 'ऑपरेशन', 'मरा।', 'भीत्त', 'अधिनियमों', 'जुड़', 'प्यार', 'संभावनाओं', 'ज़िला', 'बडी', 'बीवी', 'भरी', 'शीध्र', 'अनुरेखक', 'काट', 'अधीक', 'कर्ण', 'रूचिकारक', 'डरना', 'सेनाएँ', '१', 'पांडिचेरी', 'बंदूक', 'बन्धन', 'पुष्टि', 'बेमानी', 'साइकिल', 'नमस्ते।', 'चाहते', 'प्रयोजन', 'वासुदेव', 'मित्र', '12', '१९९०', 'तुम्हारा', 'हेल्थ', 'चलानी', 'उभरा', 'बंगाल', 'कीजिएगा।', 'तेजी', 'तोड-फोड़', '17', 'Journal)ने', 'रिटायर्ड', 'अलग-अलग', 'आक्रोश', 'अजीबो-गरीब', 'प्रोटेम', 'स्थिरता', 'जापान', 'बल्कि', 'लगाए', 'कोभी', 'विवेकानुसार', 'अनुयायी', 'जरूरी', 'रूपरेखा', 'खुलकर', 'सदृश्य', 'धर्मो', 'गिरतार', 'चीरते', 'कमरा', 'अटैची', '‘द्विवेदी', 'विधायकों', 'पैक', 'इंजीनियर', 'तालाब', 'चूहा', 'जाओगी.”', 'ऋन', 'नहा', 'बैट', 'सिलकर', 'टुकड़ा', 'सिल्क', 'पढ़ा', 'चलें', '(', 'पुलेल', 'स्वैच्छिक', 'मुसम्मन', 'दूसरी', '(ALDE)', 'भलई', 'मिशिगन', 'इलज़ाम', 'कौनसा', 'मुस्कुराहट', 'खुला', 'डालियों', 'नाज़', 'उतारा', 'बचाव', 'उठाने', 'क्योंकि', 'बसन्त।', 'रोका।', 'विख़्यात', 'समानता', 'धुएँ', 'सांख्यिकी', 'टकसाल', 'चिंगल', 'संदेश', 'बाक्स', 'समूची', 'पांचवां', 'है.हालंकि', 'पहुँच', 'established', 'तह', 'आसन', 'जहाज़', 'Ground)', '[अस्पष्ट]', 'समझाया।', 'बेइज़्जत', 'गिरनी', 'होगा', 'निंदा', 'स्नातक', 'समालोचना', 'अभ', 'प्रोपेन', 'तटीय', 'जाएगा।', 'गान', 'क्वाला', 'हटाना', 'पुरानी', 'सीखा।', 'चलचित्र', 'करदोगे', 'आनंदमग़्न', 'रहेहै', 'औचित्य', 'गांधी', 'मत्स्य', 'गवा', 'थामे', 'जुर्माना', 'कला-क्षेत्रों', 'उनका', 'खिलाईएगा।', '१३६६२८८५', 'उसपर', 'होमवर्क', 'कहा।', 'पहुँचे।', 'दिवालिया', 'छोटे', '80', 'विशेषीकृत', 'स्वीऋत', 'हाथ', 'मांसल', 'ब्रह्मचर्य-पालन', 'भागलपुर', 'रवाना', 'जंजीर', 'सड़े', 'कार्यवाही', 'जनसमूह', 'इस्लाम', 'अत', 'घुसते', 'हैं-', 'कमीशन', '१०००००', 'वनरक्षक', 'अभिमानी', 'कहना', 'क्रम', 'बुनाई', 'रमादेवी', 'छत', 'हरिनारायण', 'cells)', 'पर।', 'करतीं', 'दाय', 'पाओ।', 'अल्पकालीन', 'हुए,', 'गैस', 'पक्ष', '(चुनें)', '1985', 'तोह्फ़ा', 'है|', 'किन्गडम्\u200c', 'निभाती', 'बल्ब', 'परस्पर', 'शताब्दियों', 'अखबारों', 'रूक', 'जभी', 'मंत्री', 'पढ़ता', 'दैनंदिन', 'दीं।', 'पूछती', 'करते', 'गए।', '1998', 'ड्यूटी', 'पटरी', 'जिप्सम', 'थपथपाते', '262', 'वाले', 'करदी।', 'दुर्गंधयुक़्त', '(१९९८', '५वी', 'आश्रित', 'hurt)', 'पिट', 'हैं.ऐसा', 'बैठो।', 'दिगलीपुर', 'वास्तु', 'मिलेंगीं।', 'पुत्रों', 'सदनों', 'गाल', 'लयल', 'भागीदार', 'बतायेगा', 'डाँवाडोल', 'इकठ्ठी', 'यदि', '२००१', 'बतखों', 'ब्रश', 'गिखाना', 'केन्द्रीय', 'चाहिए', 'प्रारम्भ', 'साफ-सफाई', 'त्रुटि', 'डाक्टर', 'आधारित', 'कार्बनिक', 'धमकते', 'ठंड', 'ज़बान', 'व्यावहारिक', 'समसऋद्दत', 'हीं', 'बिल', 'रेत', 'टेनिस', 'न्यायाधीशों', 'मस्तिस्क', 'वंश', 'फायरफॉक्स', 'देशी', 'अनुकूल', 'देखनी', 'अद्वितीय', 'सच्चे', 'संयुक़्त', 'स्पर्श', 'डाला', 'वह', 'एल.ई.डी.', 'नाचना', 'रूप', 'नम्बर', 'तत्पश्चात', 'बधाईंयाँ।', 'ज्ञानियों', 'सकते', 'संचरण', 'चतुराई', 'गाँधीजी', 'Zबिना', 'ऋ.से', 'ढालते', 'गणपूरक', 'ग्राउंड', 'शक्तियाँ', 'कर्जन', 'प्रकाशन', 'क्रोमोसोमों', 'आज़माए.', 'संस्कृत,', 'संकरों', 'लयबद्ध', 'स्थल', 'चौड़ी', 'था?', 'वस्त्र', 'धन्यवाद.', 'कूदने', 'गठजोड़', '१६००', 'यौगिक', 'क्षेत्ररक्षण', 'गवाही', 'पहुंच', 'एसटर', 'पूर्ण', 'वेश्यावृति', 'कृष्ण', 'बड़े', 'लाभ', 'जाओ', 'होनेवाला', 'बोलतीं', 'प्रभावों', 'पतवार', 'बबलगम', 'तो,', 'पहुँचाने', '३', 'सादगी', 'गई.', 'अौर', '2,74,000', 'चाहिए,', 'चरते', 'देवनागरी-', 'खालिद', 'सामिल', 'माँगनी', 'निर्गुण-सगुण', 'वात्सल्य', 'मुताबिक,', 'पूर्णत', 'मौत', 'अन्Lश्चित', 'हज़रत', 'रिज़ल्ट', 'सत्तासीन', 'complex', 'इतने', 'ड्रा', 'कस्बे', ',', 'ख़ज़ाना', 'गतिविधि', 'दैनिक', 'संसऋ-ऊण्श्छ्ष्-मरणों', 'गोलिकाएं', 'नुक्सान', 'मयूर', '७०', 'दहशत', 'है.इसका', 'Group)', 'उनऋ-ऊण्श्छ्ष्-होंने', 'वीडियॊ', 'होगा।', 'औरडर', '153,090', 'क्रिस', 'भूलूँगा।', 'देखीये', 'कि.मी.', 'ग़लत', 'मौंहदिया', '(complexity)है', 'क्रांतिकारी', 'पड़ेता', 'असली', 'समर्पण', 'थक़्का', 'बसे।', 'जमशेदपुर', 'सचमुच', 'कोटे', 'चेतना', 'Peach.”', 'गोल्फ', 'मार्च', 'पुण्य', 'सिगरेट', 'श्रेष्ट', 'बहुमूल्य', 'विनिवेश', 'हाथों', 'कब्ज', 'निर्भर', 'आदर्शों', 'Protection', 'आये', 'चलना', 'कुलटी', 'व्यायाओं', 'होता!', 'हैं,|भाष्;', 'कोलकाता', 'छात्र', 'परिस्थिती', 'सफ़लताएं,', 'यधपि', 'लेट', 'गाड़ी', 'सूखा', 'बकरियों', 'उड़ाता', 'कक्ष', 'बिंदी', 'प्रभावशाली', 'अवशोषण', 'एकमात्र', 'असामयिक', 'राजस्व', 'बाज़ी', 'निकाला', 'राष्ट्रवादी-अलगाववादी', 'निर्लेप', 'उच्चकोटि', 'और्थोपेडिक', 'आय', 'चुनीं,', 'हों', 'मध्कालीन', 'अनुच्छेदो', 'governments)ने', 'याचिका', 'तत्त्व', 'बातो', '1989', 'आखिरकार', 'माऋलेज', 'पहलेवाली', 'नऋर्नमेनटेन्ड', 'निकला', 'रोजी', 'हक्सर', 'झिल्ली', 'ठाणे', 'सिनेमा', 'ढल', 'कार्यसूची', 'गलियारे', 'लोक', 'दूतों', 'अलिंगी', 'बढ़ा-चढ़ाकर', 'विश्वविद्यालयों', 'हर्ज', 'व्यक़्तिगत', '(state', 'जंबुद्वीप', 'तंत्रिका', 'पिच', 'आंकडे', 'असंतुलन', 'एकदम', 'जोधपुर', 'लगवाना', 'भागीदारी', 'उलझन', 'जानलेवा', 'नमूनों', 'निष्फल', 'वाकर', 'उड़ाया।', 'ट्रायल', 'इनकार', 'खामोशी', 'पाये', 'प्रवक़्ता', 'लेनीं', 'प्रणिता', 'बहुलता', 'प्राप्त', 'शरीफ', 'विज्ञापन', 'बहु', 'pOda', 'नौकरानी', 'सतह', 'लागू', 'लॅटरी', 'चादरें', 'लिहाज', 'लेती', 'फट', 'सूर', 'बहुत', 'बुनी', 'सिद्धांत', 'हाँ', 'अफ़वाह', 'पड़ेताल', '(tar', 'महर्षि', 'चाकू', 'वायल', 'डिग्री', 'कर्मचारियों', 'ऋऋमैनें', 'अभिनेत्री', '.धन्यवाद', 'आएगा', 'गहणात्मक', 'स्टाऋल', 'परिश्रम', 'hO-', 'स्कैरब', 'पाठ्यक्रम', 'रोबोट', 'लिच्छवियो', '(आवर्धन', 'ग्रिड', 'पूर्व', 'टकराव', 'ऐक्ट,', 'मिलाना', 'संगीन', 'हाथः', 'अभिव्यक़्ति', 'जलयान', 'प्रगतिशील', 'विडियो', 'जल्दी', 'व्यय', 'इतिहासकारों', 'शहरों', 'ऑट्टोमन', 'AaOr', 'अकलमंद', 'कलम', 'हैं?', 'जलवायु', '(Lead)', 'गस्सा', '149%', 'निम्नतर', 'परिपत्र', 'सॉफ़्टवेयर', '(मुख्यतः', 'कब्जा़', 'लुघात', 'अप्रैल', 'अक्खड़पन', 'लिये।', 'ईर्ष्या', 'प्2', 'जर्नल', 'मैथिली', 'इंजक्शन', 'हमदर्दी', 'लाते', 'निशानों', '(terabyte))और', 'बज्रेश्वरी', 'डा', 'साफ-सुथरे', 'बहरहाल', 'फ्रांसिसी', 'सैंकड़ों', '६', 'ज्ञानार्जन', 'सहचारिता', 'वृद्वि', 'अत्यधिक', 'वेल्स', '(Neoproterozoic)', 'कह', 'सुप्रीम', 'किरणें', 'रहे।', 'कार्यक्षमता', 'हाल', 'अर्थ', 'सालों', '(outer', 'आलोक', 'मोहक', 'झुकी।', 'मोटे', 'सच', 'मांत्र', 'ताजमहल', 'सम्पर्क', 'टूक', 'दृष्टि', 'समाधान', 'समन्वय', 'दिखाया', 'संतुलन', 'सीटी', 'यहाँ-वहाँ', 'कोशिकाऒं', 'ढूँढो।', 'कारक', '१९६५', 'लिखित', 'स्थलों', 'गेंदबाज', 'उच्चतल', 'और', 'एरवेस', 'पीने', 'लीग', 'संभावना', 'फांसी', 'द्वारका', 'लिपियां', 'रह', 'तीखे', 'ओवरों', 'अकेले', 'अल्प&आन', 'आमतौर', 'पुस्तकें', 'नतीजा', 'क्रिकेट', '11.', 'वाईन', 'बेंजीन,', 'जलाने', 'दाता', 'गर्म', 'St', 'पुरूषों', 'ढूंढऋने', 'चाहिएँ।', 'वसा', 'वेदान्त', '(सबसे', 'कट्टंरपंथ', 'उसी', 'प्रशिक्षण', 'अगर', 'लेखकों', 'महक', 'घिनौना', 'idyaa', 'दत्त', 'निराशा', 'ख़रीदो', 'पहनने', 'ट्रांस्पोर्ट', 'तूल', 'अधिक)', 'बरी', 'प्रिक्स', 'खोता', 'सामाजिक', 'जलाती', 'ठहराया', 'हस्त', 'इंगित', 'शिखामणि', 'मसिओसरे', 'क्यों', 'से।', 'सामान्यतः', 'पासपोर्ट', 'आउट', 'गधियों', 'इंपीरियल', '8,325', '121-ए', 'सम्मेलन', 'अगले', 'ख़्यालों', 'है.(बल्लेबाज', 'एशिया', 'बुलाया', 'कुशाग्र', 'मानकों', 'विदेशी', 'सरकारी', 'रखना।', '”', 'नसीब', 'सगाई', 'सिराज-उल-', 'उदाहरण', 'एयरपोर्ट', 'कच्छ', 'देखकर', 'ऋणों', 'प्रजातियाँ', 'अविश्वसनीय', 'सबूतों', 'पुनर्निर्माण', 'आश्विन', 'खिंचाव', 'हथकरघे', 'बाताऊँगा।', 'National', 'निशान', 'लाईसैंस', 'सीखा', 'ओडिया', 'वेदों', '(counter', 'आत्मविश्लेषी', 'एश्वर्या', 'प्रतिकूल', 'नवीनीकरण', 'व्यायाम', 'प्रिय', 'प्रदान', 'सफाई', '1,81,278', 'योनि', 'साहित्य', 'सादा', 'विविध', 'एन्ड्रोमिडा', 'साड़ी', 'अगणित', '२', 'अमाप', 'सींग', 'विष्णुसहस्रनाम', 'कपडऋआ', 'मुंह', 'कड़वी', 'अनियमितताओं', 'उभारदार', 'सन्दर्भ', 'नार्थ', 'नई', 'धनबाद', 'खाँसी', 'आस-पड़ोस'

In [31]:
eng_word_2_idx = {word : idx for word , idx in enumerate(vocab_english)}
print(eng_word_2_idx)

{0: '<UNK>', 1: 'reminded', 2: 'indira', 3: 'ambitious', 4: 'veterinary', 5: 'instrumental', 6: 'crying.', 7: 'syndicalists', 8: 'smelling', 9: 'distribution', 10: 'energy,', 11: '(ruling', 12: 'elevator?', 13: 'intention', 14: 'began', 15: 'bin', 16: 'stayed', 17: 'total', 18: 'ago', 19: 'aman.', 20: 'resolves', 21: 'dust,', 22: 'motor', 23: 'eats', 24: 'live.', 25: 'rss', 26: 'suit.', 27: 'redundant', 28: 'branch.', 29: 'crisis', 30: '51', 31: 'oriented', 32: 'temples', 33: 'january1763-4', 34: '4,000', 35: 'mindset', 36: 'assent', 37: 'secondary', 38: 'white', 39: 'states', 40: 'supper?', 41: 'middle', 42: 'came.', 43: 'escape', 44: 'massive', 45: 'well-developed', 46: 'dynasties)', 47: 'rejuvenation', 48: 'exercise', 49: 'earlier', 50: 'plague', 51: 'fever', 52: 'naren', 53: 'o', 54: 'niraja', 55: 'bhandar,', 56: 'area', 57: 'director-general', 58: 'burj.', 59: 'getting', 60: 'came', 61: 'nature', 62: 'sq.', 63: '266', 64: 'spoke', 65: 'ideal', 66: '“women', 67: 'feathers.', 68: 'signs', 69: 'contributing', 70: 'exploitation', 71: 'costs', 72: 'supervisor', 73: 'exercised', 74: '47', 75: '1979.', 76: 'appointment?', 77: 'phd', 78: 'go', 79: 'michanary', 80: 'inc,', 81: 'length', 82: 'azhar', 83: 'playmates', 84: 'hogged', 85: 'happen?', 86: 'frame', 87: 'stamp', 88: 'gandhinagar', 89: 'personand', 90: 'hec', 91: 'tea', 92: 'illness.', 93: 'failure', 94: 'motilal', 95: 'disposed', 96: 'little', 97: 'house?', 98: 'factors', 99: 'flooding', 100: 'sms', 101: 'hanging', 102: 'transfer', 103: 'media', 104: 'allowing', 105: 'avatar', 106: 'saxena', 107: 'chirping', 108: 'contributed', 109: 'includes', 110: 'windows?', 111: 'indigenous', 112: 'congratulations!', 113: 'under-trial', 114: '3102', 115: 'impact.', 116: 'charles', 117: 'is', 118: 'optimized.', 119: 'hang', 120: 'monitored', 121: 'bibliography', 122: 'march', 123: 'concept.', 124: 'communalism', 125: 'yajurvedh,', 126: 'explain', 127: 'democracies', 128: 'labour', 129: 'hygiene', 130: 'mint', 131: 'plays', 132: 'application', 133: 'fair', 134: '1922', 135: '1980', 136: 'teacher.', 137: 'jagaran', 138: '35', 139: 'bachchan', 140: 'frequently.', 141: 'constellation', 142: 'picked', 143: 'now?', 144: 'football', 145: 'zindabad.', 146: 'predisposition', 147: "one's", 148: 'delhi', 149: 'waterfall,', 150: 'rl', 151: 'speed', 152: 'matter?', 153: '3100-5600', 154: 'size?', 155: 'study.', 156: 'hair.', 157: 'reproduction', 158: 'hambledon', 159: 'useful', 160: 'rejuvenation.', 161: 'authoritythe', 162: 'terms', 163: '25,000', 164: 'mumbai.', 165: 'chakrabarti', 166: 'cat?', 167: 'procedural', 168: 'problem,', 169: 'scalability', 170: "sun's", 171: 'river', 172: 'observed', 173: 'served', 174: 'oh,', 175: 'teresa', 176: 'charge.', 177: 'inclement', 178: 'netaji', 179: 'unused', 180: 'breaking', 181: 'cats', 182: 'drinks?', 183: 'generally', 184: 'was.', 185: 'one-day', 186: 'tunnel', 187: 'antarraman', 188: 'basketball.', 189: 'reference', 190: '$10.', 191: 'agile', 192: 'calculate', 193: 'rose', 194: 'his', 195: 'celebrated', 196: '1965,', 197: 'sixth', 198: 'chute', 199: 'orissa', 200: 'pendra', 201: 'calling', 202: 'carries', 203: 'rank', 204: 'disciple', 205: 'synthetic', 206: 'aeronautical', 207: 'ganga', 208: 'udder', 209: 'fis', 210: 'acquainted', 211: 'sumitranandan', 212: 'curvilinearcircular', 213: 'shade.', 214: 'incorporating', 215: 'enter', 216: 'excitedly', 217: 'calls', 218: 'heap.', 219: 'librarians', 220: 'irrespective', 221: 'backside', 222: 'similar', 223: 'lipikaar', 224: 'taj', 225: 'rabbit', 226: 'wonder', 227: 'bays', 228: 'terrorised', 229: 'muscles', 230: 'late', 231: 'traffic.', 232: 'develop', 233: 'devtas', 234: 'factory', 235: 'notes.', 236: 'combine', 237: 'socks,', 238: 'work', 239: 'melted', 240: 'senapati', 241: 'grasim', 242: 'battlefield', 243: 'association', 244: 'are.', 245: 'mauryan', 246: 'cultural', 247: 'asbestos.', 248: 'hindi.', 249: 'bhatena', 250: 'abreast', 251: 'winning', 252: 'alternative', 253: 'ambulance?', 254: 'sur', 255: 'yuvraj', 256: 'highest', 257: 'sakalesha', 258: 'existing', 259: 'museum', 260: 'acts', 261: 'innings', 262: 'industries', 263: 'voluntary', 264: 'consulted', 265: 'burning.', 266: '2007', 267: 'it.', 268: 'actions', 269: 'point.', 270: 'mean?', 271: 'flatter.', 272: 'industries.', 273: 'edition.', 274: 'missionary', 275: 'sectioned', 276: 'dangerous.', 277: 'mr', 278: 'general', 279: 'baseball!', 280: 'association.', 281: 'darkness', 282: 'naphtha', 283: 'fuel', 284: 'tackled', 285: '2100', 286: 'measurements.', 287: 'citizens', 288: 'accomplished', 289: 'city', 290: 'ardent', 291: 'khalistan', 292: 'tomorrow?', 293: 'anti-leninist', 294: 'ourselves,', 295: 'manages', 296: 'emperors', 297: 'inhabitants', 298: 'experiments,', 299: 'tourism,', 300: 'shia', 301: 'mentally', 302: 'रख', 303: 'conspiracy', 304: 'avoiding', 305: 'mayo', 306: 'ik', 307: 'fielding', 308: 'u.s.?', 309: 'opposition', 310: 'garments', 311: 'men“”', 312: 'writing', 313: 'prevent', 314: 'survey', 315: 'federal', 316: 'copying', 317: 'owners', 318: 'blindly', 319: 'roundabout', 320: 'religion', 321: 'wifi.', 322: 'lahore.', 323: 'difference', 324: 'stop', 325: 'himalayan', 326: 'elevated', 327: 'unnoticed', 328: 'hub', 329: 'bring', 330: 'accessible', 331: 'included', 332: 'lord', 333: 'glut', 334: 'barabanki', 335: 'pakistan]', 336: 'translate', 337: 'key', 338: 'mobilised', 339: 'gone', 340: 'trail', 341: 'bhagalpur', 342: 'militant', 343: 'vivekanand(12th', 344: 'tata', 345: 'subject,', 346: '3.4', 347: 'karunguzhi', 348: 'studied', 349: 'indoor', 350: 'v', 351: 'apples', 352: 'yes,', 353: 'foreign-made', 354: 'disabled', 355: 'indigo', 356: '1131', 357: 'evoked', 358: 'nation', 359: 'catastrophe', 360: 'relics', 361: "power's", 362: '(development', 363: 'percent.', 364: 'characters', 365: '368', 366: 'khas', 367: 'motifs', 368: 'rotten.', 369: 'pleased', 370: 'no,', 371: 'applied.', 372: 'dirty.', 373: 'sheer', 374: 'hungry,', 375: 'susceptibility', 376: 'estimation', 377: 'merchants', 378: 'kayastha', 379: 'up?', 380: 'firmly', 381: 'quality', 382: 'misuse', 383: ',first', 384: 'instances', 385: 'depends', 386: 'a.m.', 387: 'female', 388: 'civilisation', 389: 'broke', 390: 'oars', 391: 'hurry,', 392: '(which', 393: '12th', 394: 'obtained', 395: 'it?', 396: 'invert', 397: 'madarasa', 398: 'performs', 399: 'tired.', 400: 'occasion', 401: 'how.', 402: 'vedic', 403: 'lenin', 404: 'koala.', 405: 'pradesh,', 406: 'goats', 407: 'methyl', 408: 'over.', 409: 'mountain.', 410: 'aur', 411: 'sal', 412: 'occurs', 413: 'capitalists', 414: 'bugs', 415: 'secure', 416: 'clothing', 417: 'irrigated', 418: 'easy,', 419: 'services.', 420: 'organized', 421: 'software.', 422: 'happy."', 423: 'sari', 424: 'frankly', 425: 'think?', 426: 'biological', 427: 'estates', 428: 'smelled', 429: 'disease', 430: 'naina', 431: 'ease', 432: 'ananth', 433: 'vinayadhara', 434: '(1981)', 435: 'remember.', 436: 'millions', 437: 'inanimate', 438: 'eight-thirty.', 439: 'titht', 440: 'target', 441: 'hello!', 442: 'kulti', 443: 'imprisoned', 444: 'greatly', 445: 'mirzapur,patna,and', 446: 'deaf', 447: 'proverb?', 448: 'harif', 449: 'taliban', 450: 'asia.', 451: 'deals', 452: 'operation', 453: 'ranging', 454: 'so.”', 455: 'google', 456: 'fail.', 457: 'costly', 458: '13th', 459: "dhamayanthi'", 460: 'you.”', 461: 'performance', 462: 'louder', 463: 'resource,', 464: 'thousands', 465: 'imperialist', 466: 'prosecutor', 467: "i've", 468: 'instant', 469: 'typical', 470: 'barrel', 471: 'lewis', 472: 'vogue,', 473: 'advantage', 474: 'fiery', 475: 'planet', 476: 'penalty.', 477: 'self-respect', 478: 'pepped', 479: 'thoroughly', 480: 'views', 481: 'ugly', 482: 'flopped', 483: 'andaman', 484: 'california', 485: 'absence', 486: 'palace', 487: 'bhagwan', 488: 'salient', 489: 'premchand', 490: 'women.', 491: 'taiwan,', 492: 'cloister', 493: 'car?', 494: 'boston.', 495: 'actual', 496: 'wrong', 497: 'perhaps', 498: 'more.', 499: 'membership', 500: 'jacket.', 501: 'movies?', 502: 'action', 503: 'relatively', 504: 'kota', 505: 'back', 506: 'exam.', 507: 'treatment', 508: 'ashtank', 509: 'stability,', 510: 'everest', 511: 'kabir', 512: 'mobile', 513: 'whatever.', 514: '30.', 515: 'provided', 516: 'strong,', 517: 'saharanpur,', 518: 'immutable', 519: 'nonavailability', 520: 'hockey', 521: 'kalyan-dombivili,', 522: '1859', 523: 'tabar', 524: '"it\'s', 525: 'accounts', 526: 'epoch-making', 527: 'only', 528: 'tajmahal', 529: 'elephants', 530: 'saunaka', 531: 'friend', 532: 'jump.', 533: 'catching', 534: 'genius', 535: 'vidur', 536: 'passing', 537: '(0.22', 538: 'should', 539: 'locally', 540: 'music', 541: 'shiva', 542: '2100,', 543: 'charter', 544: 'ablaze.', 545: 'original', 546: 'desk,', 547: 'health', 548: 'smooth', 549: 'contained', 550: 'prescription', 551: 'several', 552: 'tower.', 553: 'least', 554: 'uncertainties', 555: 'danceroom', 556: 'measure', 557: 'their', 558: 'filtering', 559: 'colours/fluorescent', 560: 'flowers', 561: 'arising', 562: 'kilometers)ganga', 563: 'wo', 564: 'e,', 565: 'trouble,', 566: 'rights', 567: 'herbs', 568: 'ganapuraka', 569: 'hitting', 570: 'drink.', 571: 'hoping', 572: "o'clock.", 573: 'deceive', 574: 'medicine.', 575: 'hardships.', 576: 'thar', 577: 'win.', 578: 'ones,', 579: 'succeeded.', 580: 'beer.', 581: 'struggled', 582: 'round', 583: '3:30.', 584: 'examples.', 585: 'parshuram', 586: 'large-scale', 587: 'causing', 588: 'ten.', 589: 'safe', 590: 'week.', 591: 'ahmad', 592: 'sight,', 593: 'prostitute,', 594: 'sc', 595: "we'd", 596: 'bid', 597: 'desk.', 598: 'koloniyom', 599: 'pakur', 600: 'gum', 601: 'ayodhya', 602: 'manifestation', 603: 'respected', 604: 'happen.', 605: 'genital', 606: 'together', 607: 'history.', 608: 'mamallapuram', 609: 'sow.', 610: 'aryans', 611: 'statement.', 612: 'count', 613: 'muhammad', 614: 'required', 615: 'practised', 616: 'auloo', 617: 'whether', 618: 'write.', 619: 'placing', 620: 'reparation', 621: 'regard', 622: 'me."', 623: 'maithili', 624: 'operations.', 625: 'thinks', 626: 'reasons.', 627: 'noise.', 628: 'cake', 629: 'aggravation', 630: 'morals', 631: 'authorities', 632: 'thing', 633: 'peacefully', 634: 'skilled', 635: 'voice.', 636: 'riaz:', 637: 'view', 638: 'practises', 639: "jagran'", 640: 'looked', 641: 'fixed', 642: 'ears.', 643: 'imagine', 644: 'pehele', 645: 'sprung', 646: 'reducing', 647: 'rebuild', 648: 'danger?', 649: 'corner', 650: 'king.', 651: 'comic', 652: 'global', 653: 'affiliation', 654: 'hurry', 655: 'remaining', 656: 'combinations', 657: 'affairs', 658: 'secret', 659: 'rabbi', 660: 'gurubhai', 661: 'curing', 662: 'developed,', 663: "mary's", 664: 'wearing', 665: 'com-', 666: 'liturature', 667: 'tremendous', 668: 'directed', 669: 'ganges', 670: 'light?', 671: 'princely', 672: 'hope', 673: 'to?', 674: 'haksar', 675: 'discount', 676: 'female.', 677: 'evil', 678: 'vehicle', 679: 'minds', 680: 'bank.', 681: 'only,', 682: 'directly', 683: 'okay,', 684: 'pride', 685: 'specific', 686: 'chaudhari', 687: 'cited', 688: 'precious', 689: 'particles', 690: 'august', 691: 'repair', 692: 'watch.', 693: 'habit.', 694: 'front.', 695: 'blue,', 696: 'expenditure', 697: 'mobility', 698: 'computer?', 699: 'dealer', 700: 'ami', 701: 'refutation', 702: 'varieties', 703: 'thing.', 704: 'scenarios', 705: 'non-partisan', 706: 'monopolistic', 707: 'islam.', 708: 'andamans', 709: 'park.', 710: 'secretary', 711: 'breath,', 712: 'book', 713: 'universities', 714: 'skating.', 715: 'sumru', 716: 'events', 717: 'advantages', 718: 'smiles.', 719: 'structure', 720: 'god,', 721: 'astrologist', 722: '3', 723: 'uncut', 724: 'sushma', 725: 'year!', 726: '100', 727: 'famines', 728: 'tea.', 729: 'tool', 730: 'reap', 731: 'dalit', 732: 'struggle,', 733: 'foretold', 734: 'substance', 735: 'punished', 736: 'collectively', 737: 'discover', 738: 'daal', 739: 'kumar.', 740: 'reaction', 741: 'well,', 742: 'uses', 743: 'disclosing', 744: 'language),', 745: 'moment.', 746: 'by', 747: 'wishes', 748: 'incorporate', 749: 'regret', 750: 'brahma', 751: 'stroke', 752: 'sat', 753: 'suddenly.', 754: 'apple.', 755: 'mud', 756: 'khan', 757: 'engaged', 758: 'approved', 759: '1947,', 760: 'waterway', 761: 'good', 762: 'child,', 763: 'survive', 764: 'bottle', 765: 'ago.so', 766: 'male-specific', 767: '=', 768: 'user', 769: 'girls.', 770: 'sheets', 771: 'mountains', 772: 'lyrical', 773: 'cancer,mesothelioma(it', 774: 'infant', 775: 'calcutta', 776: 'index', 777: 'rekahayein.', 778: 'autumn', 779: 'eggs.', 780: 'lame', 781: "chawla's", 782: 'telemedicine', 783: 'money', 784: 'village', 785: '1999.', 786: 'taxed', 787: 'wickets(', 788: 'sign', 789: '...', 790: 'presidential', 791: 'network', 792: 'anjuman-i-islam', 793: 'critisizing', 794: 'registered', 795: '1979-80', 796: 'fusion', 797: 'cough', 798: 'expect', 799: 'continual', 800: 'ocean,second', 801: 'subhashbabu', 802: 'south', 803: 'quick.', 804: 'competed', 805: 'periods', 806: 'ram', 807: 'california.', 808: 'fortnight', 809: 'miniaturization.', 810: 'dangers', 811: 'ca:', 812: 'disinterest', 813: 'dial', 814: 'buddhism', 815: 'casts', 816: '2005,', 817: 'districts', 818: 'fever.', 819: 'room?', 820: 'symbolised', 821: 'ravaged', 822: 'earmarked', 823: 'ironically', 824: 'situated', 825: 'impass.', 826: 'cleaning', 827: 'battingthat', 828: 'finger.', 829: 'feynman,', 830: '“well,', 831: 'generation', 832: 'segments', 833: '1956', 834: 'sticks', 835: 'ground.', 836: 'declined', 837: 'cities', 838: 'section:east', 839: 'enactment', 840: 'needs', 841: 'harmful', 842: 'sending', 843: 'fat', 844: 'sweater', 845: 'horse.', 846: 'things', 847: 'clogged.', 848: 'advising', 849: 'participation,', 850: 'listened', 851: 'monetary', 852: 'vidhata,', 853: 'abstract.', 854: 'warming', 855: 'bounds', 856: 'graduate', 857: 'meaningful.', 858: 'artist.', 859: 'lyall', 860: 'anything', 861: 'lexicographers', 862: '(e-paper,unicoded)', 863: 'tariff', 864: 'tekchand', 865: 'superintentant', 866: 'vimana', 867: 'poverty', 868: "brahma's", 869: 'everything,', 870: 'mahanadi', 871: 'bet', 872: 'dozen', 873: 'sijistan', 874: "'bade", 875: 'consumers', 876: 'nepali', 877: 'killed', 878: 'witnessed', 879: 'advent', 880: 'health.', 881: 'database', 882: 'pianist.', 883: 'standing', 884: 'lateral', 885: 'official', 886: '21st.', 887: 'preapproved', 888: 'imperialism', 889: 'drama', 890: 'governments?', 891: 'pocket', 892: '27', 893: 'drenched', 894: 'dark', 895: '50,000', 896: 'scholars', 897: 'special', 898: 'extensions', 899: 'cried.', 900: 'job', 901: 'true', 902: 'babu', 903: 'canada?', 904: "pandu's", 905: 'prosecution', 906: 'clot', 907: 'surdas.', 908: 'metabolism', 909: 'tobacco.', 910: 'drove', 911: "raj's", 912: 'revolution,the', 913: 'idol', 914: 'appearance', 915: 'bed', 916: 'awasheshne', 917: 'ranges', 918: 'daytime.', 919: 'warranty', 920: 'encounter', 921: 'crudest', 922: 'challenge', 923: 'independently,', 924: 'milk.', 925: 'realize', 926: 'fulfill', 927: 'thereby', 928: 'dhanbad', 929: 'vikramaditya', 930: 'deputy', 931: 'proceed', 932: 'narasimha', 933: 'prejudice', 934: 'ramalinga', 935: 'colony', 936: 'fast.', 937: 'tables', 938: 'minar,', 939: 'time.', 940: 'horn.', 941: 'weeks.', 942: 'festivals', 943: 'expressions', 944: 'this.', 945: 'sacrificing', 946: 'helmet,', 947: 'bed!', 948: '685682', 949: 'drink', 950: 'keeping', 951: 'udahrano', 952: 'betcha.', 953: 'rupnnie', 954: 'possibly', 955: 'cat?”', 956: 'hello', 957: 'garden', 958: 'tajmahal(vary', 959: 'illiterate', 960: "[you'll", 961: 'scottish', 962: 'internationl', 963: 'proves', 964: 'channel.', 965: 'assaulted.', 966: 'capital.', 967: 'dire', 968: 'caught', 969: 'methods,', 970: '!', 971: 'revolution', 972: 'circumstances.', 973: 'masterpieces', 974: 'scientific', 975: 'as,', 976: 'ago.', 977: 'contact', 978: 'definitely!', 979: 'launching', 980: 'stripped', 981: 'dalits', 982: 'discretion', 983: 'hips', 984: 'breathed', 985: 'proved', 986: 'troposphere', 987: 'which', 988: 'sabha', 989: 'repeated', 990: 'treaties.', 991: 'now', 992: 'coins.', 993: 'cooker', 994: 'arguable', 995: 'saver.', 996: 'fined', 997: 'octagon,', 998: 'liberty', 999: 'judgment', 1000: 'me', 1001: 'genuine', 1002: 'feature', 1003: 'disorderly', 1004: 'interactive', 1005: 'strategy,', 1006: 'ag:', 1007: 'ashamed', 1008: 'retire', 1009: 'alpa', 1010: 'representations', 1011: 'insights', 1012: 'timely', 1013: 'rest', 1014: 'yashaarat', 1015: 'conquests', 1016: 'poor,', 1017: 'ultimate', 1018: 'toilers', 1019: 'adhishthana', 1020: 'regime', 1021: 'air.', 1022: 'chatta', 1023: 'assurances', 1024: 'mosques', 1025: 'respective', 1026: 'turn', 1027: 'oppose', 1028: 'ulfa', 1029: 'proportions', 1030: 'avoided', 1031: 'permament', 1032: 'gopichand', 1033: 'harbinger', 1034: 'try.', 1035: 'cave-temple', 1036: 'seeing', 1037: 'dpc', 1038: 'dainik', 1039: 'persian', 1040: 'snails', 1041: 'pew', 1042: 'inclined', 1043: 'dictionary,', 1044: 'chair.', 1045: 'marriage.', 1046: 'list', 1047: 'counting', 1048: 'tom', 1049: 'september', 1050: 'saying,', 1051: 'settlement', 1052: 'deliver', 1053: 'propaganda', 1054: 'ex-', 1055: 'cloth', 1056: 'commit', 1057: 'nationalist-secessionist', 1058: 'sinha', 1059: '“huh!”', 1060: 'residents', 1061: 'counted', 1062: 'cake?', 1063: 'crossing', 1064: 'fractures', 1065: 'socialist,', 1066: 'downloaded', 1067: 'sleep', 1068: 'energy', 1069: 'us?', 1070: 'advances', 1071: 'swimming.', 1072: 'non-spanish', 1073: 'library', 1074: 'ability', 1075: 'kms.', 1076: 'arrangements', 1077: 'schools', 1078: '375', 1079: 'school', 1080: 'script', 1081: 'presumably', 1082: "they're", 1083: 'researches', 1084: 'trajectories', 1085: 'voting', 1086: 'reduced', 1087: 'barabaki', 1088: 'opened', 1089: 'earning', 1090: 'appreciate', 1091: 'expressly', 1092: 'because,', 1093: 'races', 1094: 'itself', 1095: 'line,', 1096: 'whoredom', 1097: 'deprecated', 1098: 'algorithms', 1099: 'echo', 1100: 'bullocks', 1101: 'appears', 1102: 'youngster.', 1103: 'amend', 1104: 'rare', 1105: 'humans.', 1106: 'doctor', 1107: 'employment', 1108: 'barely', 1109: 'sub-branch', 1110: 'boys.', 1111: 'simple', 1112: 'grandmother.', 1113: 'galaxy', 1114: 'daulatpur', 1115: 'places', 1116: 'prove', 1117: 'kochler,hans', 1118: 'unauthorised', 1119: '(maharashtra', 1120: 'backafter', 1121: 'vaishmpayan', 1122: 'name', 1123: 'wide', 1124: 'bhagirath', 1125: 'stone', 1126: 'dedicated', 1127: 'cats.', 1128: 'in,', 1129: 'height', 1130: 'nandeesh', 1131: 'lawyer', 1132: 'german.', 1133: 'write', 1134: 'milestone', 1135: 'bungling', 1136: 'murderer', 1137: 'plastics', 1138: 'run,', 1139: 'lack', 1140: 'addressed', 1141: 'grown', 1142: 'maintain', 1143: 'speaker,', 1144: 'selvam', 1145: 'low', 1146: 'hay', 1147: 'watch', 1148: 'references', 1149: '“no', 1150: 'leaving', 1151: 'concerned', 1152: 'rounds', 1153: 'weak', 1154: 'all', 1155: 'stadium', 1156: 'excluded', 1157: 'science,', 1158: "ravana's", 1159: 'p+q', 1160: 'advancing', 1161: 'learning.', 1162: 'last', 1163: 'base,', 1164: 'drop', 1165: 'rubber', 1166: '50,000.', 1167: 'formats.this', 1168: 'bill', 1169: 'pieces.', 1170: 'dhimee', 1171: 'multiple', 1172: 'sainiks', 1173: 'brahmaputra', 1174: 'indefinitely', 1175: 'techniques', 1176: 'solution', 1177: 'reconciliation', 1178: 'completion.', 1179: 'devote', 1180: "aren't", 1181: 'damage', 1182: 'exploration', 1183: 'anti-islam', 1184: 'suddenly', 1185: 'crafts,', 1186: 'fundamental,', 1187: 'ghoda', 1188: 'hereditary', 1189: 'manufacturing', 1190: 'categories', 1191: 'broken', 1192: 'banned', 1193: 'scarcely', 1194: 'asssembly', 1195: 'roundtable', 1196: '1471481', 1197: 'group,', 1198: 'bullet.', 1199: 'duryodhan', 1200: 'utensils', 1201: 'republican', 1202: 'tragedy', 1203: '“”aanar“”(sparkling', 1204: 'high-end', 1205: 'disabilities', 1206: 'perdvi', 1207: 'trip', 1208: 'train.', 1209: 'suo', 1210: 'approaching', 1211: 'haemorrhage', 1212: 'levies', 1213: 'lady', 1214: 'pallava', 1215: 'barack', 1216: 'skilfully', 1217: 'whilein', 1218: 'terminology', 1219: '324[1],', 1220: 'catch', 1221: 'rice', 1222: 'robot.', 1223: 'higher', 1224: 'umar', 1225: 'might', 1226: 'kutch', 1227: 'wicket.', 1228: 'c

In [32]:
hindi_word_2_idx = {word : idx for word , idx in enumerate(vocab_hindi)}
print(hindi_word_2_idx)

{0: '<start', 1: '<end>', 2: 'घरवालों', 3: 'व्यापक', 4: 'नियमित', 5: 'गणितीय', 6: 'श्रेणी:ताजमहल', 7: 'जवाहरलाल', 8: 'स्पेनी', 9: 'ग़ुलाम', 10: 'गीले', 11: 'लोलक', 12: 'छोड़', 13: 'बडऋआ', 14: 'यज्ञ', 15: '११३१', 16: 'पशुओं', 17: 'दिन', 18: 'बुलाएँगे।', 19: 'लिखा', 20: 'मानवजाति', 21: 'प्रेम', 22: 'आपत्ति', 23: 'करो,', 24: 'रहती', 25: '51', 26: 'सूँघ', 27: 'गिरि', 28: 'मंडप', 29: 'पीली', 30: 'टालने', 31: 'मुसलाधार', 32: '4,000', 33: 'राज्यों', 34: 'दूर', 35: 'सुनते', 36: 'मज़दूर', 37: 'वार्ता', 38: 'सूरसारावली', 39: 'मेने', 40: 'फलती', 41: 'शाकाहारी', 42: 'श्रेष्ठता', 43: 'मूर्खता', 44: '(प्राकृतिक', 45: 'मांसाहारी', 46: 'लाभांश', 47: 'लघुरूप', 48: 'हानिकर', 49: 'उद्देश्य', 50: 'तर्कों', 51: 'खेती', 52: 'पड़ता', 53: 'साम्राज़्य', 54: 'कीमती', 55: 'पहिए', 56: 'वस्तुएं', 57: '266', 58: 'हँसे।', 59: 'कालखंड', 60: 'सोनिया', 61: 'कार्लचऋ', 62: 'अक्टूबर', 63: 'खलीफा', 64: 'पुराना', 65: 'जाए', 66: 'विवादी', 67: 'XI', 68: 'जनवादी', 69: 'सैमसंग', 70: '47', 71: 'लगाई।', 72: 'योग्य', 73: 'करवाया।', 74: 'परिवहन', 75: 'कयोंकि', 76: 'दिखाऊँगा', 77: 'छोड़ूँ?', 78: 'किताब', 79: 'सहमत', 80: 'अभ्यास', 81: 'ताल्लुक', 82: 'उपायों', 83: 'कदमः', 84: 'ख़त्म', 85: 'ढक', 86: 'कारण', 87: 'बांग्लदेश', 88: '(air', 89: 'रु', 90: 'संग', 91: 'आएगा।', 92: 'डालें।', 93: 'य', 94: 'मुलाकातें', 95: 'तक.', 96: 'थी,', 97: 'उत्साहित', 98: 'निकटता', 99: 'सहते', 100: 'काकी', 101: 'अलग-', 102: 'मूँगफलियाँ', 103: 'मण्डप', 104: 'प्राइसेज', 105: 'महालेखानियंत्रक', 106: 'महाराष्ट्र', 107: 'निवासियों', 108: 'जातीय', 109: 'मछवारे', 110: 'एटीपी', 111: 'विवेकानन्द', 112: 'था,', 113: 'is', 114: 'है.स्त्रियों', 115: 'पुत्र', 116: 'पीढ़ियों', 117: 'खासकर', 118: 'क्रम.', 119: 'डीज़ल', 120: 'हुए।', 121: 'आयु', 122: 'जंगल', 123: 'गुंबज', 124: 'अणु', 125: 'सहने', 126: 'दूसरा', 127: '(coal)', 128: 'रणनीति', 129: 'हैया', 130: 'टी-शर्ट', 131: 'छूटता', 132: 'सुधार', 133: 'चुनौती', 134: '1922', 135: 'डालते', 136: '1980', 137: '35', 138: 'भगतराम', 139: 'शताब्दी', 140: 'लाईन', 141: 'जुटाने', 142: 'हलाँकि', 143: 'सके।', 144: '१५४२', 145: 'सुनाया', 146: 'हें', 147: 'निति', 148: 'जाता।', 149: 'बटुए', 150: 'संघात्मक', 151: 'ऊंचा', 152: 'इत्यादि', 153: 'गिनती', 154: 'प्रयास', 155: 'सरस्वती', 156: 'चुनाव', 157: '25,000', 158: 'होने', 159: 'सन्दर्भों', 160: 'भगीरथ-तपस्या', 161: 'आन', 162: 'पूछने', 163: 'अधीक्षक', 164: 'Control', 165: 'जगत', 166: 'फोटोग्राफ़रों', 167: 'हिल', 168: 'प्राण', 169: 'शरद', 170: 'बङी', 171: 'बाराबंकी', 172: 'झोब्चेन्ट्रे', 173: 'थक', 174: 'काटा', 175: 'तौलिया', 176: 'स्थापत्य', 177: 'ट्रैफीक', 178: 'मिनी-USB', 179: 'अनंत', 180: 'बारहवीं', 181: 'पूर्ववर्ती', 182: 'सांप्रदायिक', 183: 'एशोसिएशन', 184: 'ना?', 185: 'वरिउष्', 186: 'अभी-अभी', 187: 'लंबाई', 188: 'क-ख-ग-ध', 189: '(scenarios)का', 190: 'काम', 191: 'अंदमान-निकोबार', 192: 'hO', 193: 'रू-ब-रू', 194: 'बनाओ।', 195: 'गमन', 196: 'दौरे', 197: 'उत्तरी', 198: 'सर्वतोभद्र', 199: 'जवाब', 200: 'काफी', 201: 'विषय', 202: 'तरह', 203: 'भैमका', 204: 'अभिकल्पक', 205: '(climate', 206: 'टेक', 207: 'कही', 208: 'वफादार', 209: 'जैन', 210: 'था', 211: 'बोलिए।', 212: 'युद्ध', 213: 'अर्ध-चंद्राकार', 214: 'ताज', 215: 'खेतों', 216: 'शास्त्र', 217: 'पूर्वाध', 218: 'सदृश', 219: 'रेखांकनों', 220: 'conduct)निषिद्ध', 221: 'मामले', 222: 'श्रमिकों', 223: 'किए।', 224: 'ग्रैंड', 225: 'हत्या', 226: 'लौह-प्रगालन', 227: 'अरूट्पा', 228: 'पानी', 229: 'भाव', 230: 'विधानमंडल', 231: 'टॉयलेट', 232: 'मिलेगा।', 233: 'भिड़', 234: 'हवाऋ', 235: 'Zदक्षिणपंथी', 236: 'ग्रुप', 237: 'मामूली', 238: 'मेयो', 239: 'चाबी', 240: 'हफ़्तों', 241: 'तीनों', 242: 'युवराज', 243: 'घमंडी', 244: '५८०', 245: 'घटक', 246: 'हिन्दुओं', 247: 'काल', 248: 'प्रयासों', 249: 'गणेश', 250: 'दीमक', 251: 'आधारशिला', 252: '(runs)', 253: 'सूर्य', 254: 'अगला', 255: 'जॉर्ज', 256: 'हैं.टेस्ट', 257: 'सर्वमान्य', 258: 'बैठिए।', 259: 'वक्ररेखी', 260: 'अपनाया', 261: 'रेटिनल', 262: 'अतः', 263: 'नवीनतम', 264: 'लगा,', 265: 'फ्लड', 266: 'हुये', 267: 'कमा', 268: 'पकाया', 269: 'इतनी', 270: 'ट्रायंगुलर', 271: 'गोलाबारी', 272: 'संश्लेषण', 273: 'सयता', 274: 'शाप', 275: 'रहिए।', 276: 'आउटपुट', 277: 'दिलाने', 278: 'रोमांचक', 279: 'प्रतीक्षा', 280: 'हवाईअड्डे', 281: 'खरीदीं।', 282: 'सिरिंज', 283: 'पावरबोट', 284: 'यहां', 285: 'गो', 286: 'तोला।', 287: 'धक़्का', 288: 'इस्राइली,', 289: 'अभिमान', 290: 'पाया', 291: '2100', 292: 'ऊष्ण-कटिबंधीय', 293: 'अथर्ववेद', 294: 'जैसा', 295: 'हानिकारक', 296: '(single', 297: 'भक्त', 298: 'इंडोनेशिया', 299: 'नज़र', 300: 'सेल', 301: 'उड़ाओ।', 302: 'कांग्रेसी', 303: 'निचले', 304: 'सिकुड़', 305: 'प्रतिशोधपूर्ण', 306: 'रख', 307: 'मेथड्स', 308: 'जाने?', 309: 'पड़ोसी', 310: 'संघीय', 311: 'बच्चे', 312: 'कूदो।', 313: 'ललित', 314: 'निभता', 315: 'कूद', 316: 'खुद', 317: 'तानाशाही', 318: 'धीरे-धीरे', 319: 'उस्मान', 320: 'मृतक', 321: 'कर्ताओं', 322: 'ट्यूमर', 323: 'भेजने', 324: 'आपूर्ति', 325: 'नहीं।', 326: 'वोह', 327: '(Bade', 328: 'उत्सुकता', 329: 'टेस्ट', 330: 'मान्यता', 331: 'शिपयार्ड', 332: 'इनका', 333: 'भैया', 334: 'फ़ीडे', 335: 'बृज', 336: 'खोलिए।', 337: 'हिन्दुस्तान', 338: 'निवासी', 339: 'उछल', 340: 'निदान', 341: 'सोविएत', 342: 'बताने', 343: 'फ़रिश्तों', 344: 'बार।', 345: 'सदा', 346: 'इमारतें', 347: '3.4', 348: 'लड़कियों', 349: 'झोंक', 350: 'अलावा', 351: 'तकनलाजी', 352: 'बावर्ची', 353: 'ख़राब', 354: 'मुस्लिम', 355: 'सुचारु', 356: 'परीक्षा', 357: '(2002)', 358: 'clathrate)', 359: '(development', 360: 'जमाने', 361: 'अंडों', 362: '368', 363: 'नकारात्मक', 364: 'आंकड़ें', 365: 'सिन्हां', 366: 'बॅटर', 367: 'करती।', 368: 'ली', 369: 'उत्तरदायित्व', 370: 'मृग', 371: 'तूफ़ान', 372: 'प्रस्तार', 373: 'है.वह', 374: 'जाओ।', 375: 'संतुष्ट', 376: 'नाथा', 377: '१९६४)', 378: 'रहस्योद्घाटन', 379: 'ली।', 380: 'रूपयोजनाएं-प्रारंभिक', 381: 'बेचने', 382: 'मर्यादा', 383: 'प्रांतीय', 384: 'रेगिस्तान', 385: 'लेग', 386: 'स्वतंत्रता', 387: 'आयुर्वेद', 388: 'सकते।', 389: 'सफल', 390: 'करोड़', 391: 'नियोजन', 392: 'उकड़ू', 393: 'बेचना', 394: 'रहीं', 395: 'काव्य', 396: 'मुलाकात', 397: 'सोचते', 398: 'ओस', 399: 'केशव', 400: 'साझे', 401: 'शिलाखण्डों', 402: 'गयामिलियन', 403: 'नियोप्रोतेरोजोइक', 404: 'युक़्त', 405: '२७', 406: 'तैरना', 407: 'विशेषताओं', 408: 'पहुंचने', 409: 'यंत्र', 410: 'बोलना', 411: 'निकेतन', 412: 'सकें,', 413: 'मलें', 414: 'वर्महोल', 415: 'बढावा', 416: 'लिंग', 417: 'वार्षिक', 418: 'कार्यकलापों', 419: 'आकर', 420: 'स्थायी', 421: 'दूसरे', 422: 'पाँचवी', 423: 'ओसाका', 424: 'गर्दन', 425: 'millions', 426: 'राजपूत', 427: 'खेद', 428: 'बलपूर्वक', 429: 'वाले1', 430: 'खट्टा', 431: 'स्थिति', 432: 'पैकेट', 433: 'लैपिज़', 434: 'व्यक्तित्व', 435: '(Lexington', 436: 'रियली', 437: 'ग्रह', 438: 'भारत,', 439: 'इसमे', 440: 'नियमानुसा', 441: 'प्रजापति', 442: 'बेटी', 443: 'जानता?', 444: 'देंगी', 445: 'संकट', 446: 'कोशिकाओं', 447: 'करदो,', 448: 'लड़ने-झगड़ने', 449: 'वजहसे', 450: 'प्रतियाँ', 451: 'लिग्नाइट', 452: 'बाहुल्य', 453: 'अविश्वसनीय!', 454: 'तरीके', 455: 'निबंध', 456: 'टिकट', 457: 'समुज्जवल', 458: 'टाइम', 459: 'बालों', 460: 'झीलों', 461: 'पत्तन', 462: 'मात्रा', 463: 'जिम्मा', 464: 'तत्काल', 465: 'शत्रुओं', 466: 'पहनी', 467: 'जबकि', 468: 'ज्ञात', 469: 'अनुयायियों', 470: 'हिन्दू', 471: 'न्यूजप्रिंट', 472: 'पतली', 473: 'कलाकार', 474: 'अण्डे', 475: 'सुमित्रानन्दन', 476: 'मानसिक', 477: 'उत्पाद', 478: 'बार', 479: 'रुप', 480: 'भुगतने', 481: 'फ़ोर्डाइस', 482: 'खुल', 483: 'मिला', 484: 'थान', 485: 'गया,', 486: 'फिक्सर', 487: '(हंसी)', 488: 'कल्याण-डोंभीवली', 489: 'सुन', 490: 'विद्यार्थियों', 491: 'युकार्योतेस', 492: 'जाऊँगा।', 493: 'डरता', 494: 'कविताओं', 495: 'सती', 496: 'स्थापित', 497: 'बाढे', 498: 'ईस्ट', 499: 'अफ़्रीका', 500: 'तबाही', 501: 'एक्सप्रेस', 502: 'लेकर', 503: 'थे:', 504: 'प्रतिष्ठित', 505: '30.', 506: 'पिया', 507: 'मास', 508: 'गुप्ता', 509: 'सोते', 510: 'पकड़ी', 511: 'तापमान', 512: '102', 513: 'Air', 514: 'Security', 515: 'मोती', 516: 'अटक', 517: 'रखूँ,', 518: 'शास्त्रीय', 519: 'इन्हेरिटेंस', 520: 'ग्रन्थसूची', 521: 'लगादी।', 522: 'तरफ़', 523: 'गारिमा', 524: 'शासनकाल', 525: 'एनर्जी', 526: 'छोटे-छोटे', 527: 'विदेशाई', 528: 'रऋगाऋ', 529: 'शोध', 530: 'वादों', 531: 'आसन्न', 532: 'मुबारक', 533: 'प्रोग्राम', 534: 'पक्तिं', 535: 'ख़तरे', 536: 'अनुभव', 537: '(0.22', 538: 'चाहें', 539: 'दूसरों', 540: 'झगड़ा', 541: 'अहंकारी', 542: 'लाइट)', 543: 'कष्टकर', 544: 'प्रकाशक:', 545: 'जिम्मेदार', 546: 'छूते', 547: 'मिलाली', 548: 'मार्गदर्शक', 549: 'बनाई', 550: 'हैं.आउट', 551: 'सो', 552: 'भराली', 553: 'अंधेर', 554: 'सारी', 555: 'डाली।', 556: 'जोसेफ', 557: 'थनों', 558: 'आपने', 559: 'अनदेखे', 560: 'छूट', 561: 'जमा', 562: 'रिपोर्टें', 563: 'भगवान,', 564: 'बूंद', 565: 'वास्तविक', 566: 'क्षेत्रफल', 567: 'यूनिसेफ़', 568: 'तिवारी', 569: 'शोधों', 570: 'नाचघर', 571: 'लो,', 572: 'गया', 573: 'भिजवादूँगा।', 574: 'जब्त', 575: 'होती', 576: 'घाना', 577: 'शक़', 578: 'मुर्गियाँ', 579: 'जीवन', 580: 'अफगानिस्तान', 581: 'होंगे।', 582: 'विधेयक', 583: 'लेजाओगे', 584: 'रहेंगे', 585: 'चट्टा', 586: 'उठाती', 587: '°F)', 588: 'कीमतें', 589: 'अमरसाल', 590: 'विघटन', 591: 'बनारस', 592: 'दूरी', 593: 'डालकर', 594: 'निकली।', 595: 'नमूना', 596: 'स्थानिय', 597: 'गला', 598: 'केद्रित', 599: 'रहस्यवाद', 600: 'पसंदीता', 601: 'गतिविधियों', 602: 'फ़ेसबुक', 603: 'एवम्', 604: 'टेलीविजन', 605: 'मरने', 606: 'स्कोरर', 607: 'केंद्र', 608: 'चिल्लाया।', 609: 'माऋग', 610: '2पृ', 611: 'शक्ल', 612: 'सदा-भूखे', 613: 'बहुत,', 614: 'हार्मोनों', 615: 'गुड़ेगुड़ने', 616: 'किलोग्राम', 617: 'उठाएं.', 618: 'मदर', 619: 'देवी-देवताओं', 620: 'शब्द', 621: '१९७३', 622: 'भीग', 623: 'सेवन,', 624: '२२४', 625: '(National', 626: 'यात्रा', 627: 'कहेंगे', 628: 'दस-साल', 629: 'वीडियॊ)', 630: 'बी.ए', 631: 'करते-करते', 632: 'सामरिक', 633: 'समीकरण', 634: 'जवानी', 635: 'पार्सल', 636: 'इंदिरा', 637: 'पडऋ', 638: 'दण्ड', 639: 'नयी', 640: '(nudity)', 641: 'दासता', 642: 'शरीर', 643: 'वाल्व', 644: 'ज़िन्दगी', 645: 'वनस्पति', 646: 'सहभागिता', 647: 'मुसीबत', 648: 'बनाने', 649: 'ओवेर्सेट', 650: 'टाइपराइटर', 651: 'जमींदारियां', 652: 'श्रेणी:धर्म', 653: 'कमेन्न्ज', 654: 'अगुआई', 655: 'बेहद', 656: 'साँयः', 657: 'सभापति', 658: 'तीक्ष्ण', 659: 'मेहमान', 660: 'रंगमंच', 661: 'महिलएं', 662: 'पढ़ने', 663: 'पुर्तगाली', 664: 'मीनारों', 665: 'कराते', 666: 'पंद्राह', 667: 'उधार', 668: 'ईश्वर', 669: 'दया', 670: 'खैर', 671: 'अंतर्बाधा', 672: 'तरीको', 673: 'सैय्यद', 674: 'माँगता', 675: 'बरफ़', 676: 'स्टेशन', 677: 'पालनी', 678: 'चार्टर', 679: 'कोशिकीय', 680: 'बिन', 681: 'नाश्ता', 682: 'कीचड़', 683: 'population)के', 684: 'भिवंडी-निज़ामपुर', 685: 'बढ़ावा', 686: 'बहिष्कार', 687: 'हिस्से', 688: 'अवसर', 689: 'आलोचनात्मक', 690: 'विदोश', 691: 'पायी।', 692: 'रिसॉर्सेस', 693: 'सहयोग', 694: 'प्रखर', 695: '(ERT)', 696: 'चेकोस्लोवाकिया', 697: 'विठ्ठल', 698: 'साक्ष्य', 699: 'नस्ल', 700: 'भूलना', 701: 'उड़न', 702: 'सजे-धजे', 703: 'बेटियाँ', 704: 'उड़ते', 705: 'निष्कासन', 706: 'हूँगा।', 707: '(मार्क्सवादी)', 708: 'निर्वाण', 709: 'अरे', 710: 'भाषा-परिवार', 711: 'समता', 712: 'मुआवज़ा', 713: 'पनीर', 714: 'बिस्तर', 715: '43वें', 716: 'मह्ल', 717: 'स्मरणशक्ति', 718: 'उड़ना', 719: 'कविताएँ', 720: 'शब्दावली', 721: 'पीछा', 722: 'हकीकतः', 723: '3', 724: 'उत्पादित', 725: 'प्रधानमन्त्री', 726: '100', 727: 'पाऊँगा।', 728: 'रामानन्द', 729: 'जगन्नाथदास', 730: 'मतलबी', 731: 'उपलब्द्ध', 732: 'ख़ूब!', 733: 'टोंस', 734: 'इसलिये', 735: 'जाना', 736: 'दृढ़', 737: '(disenfranchisement)', 738: 'याददाश्त', 739: 'ऑक्सफ़र्ड', 740: 'हीरा', 741: 'एक-दो', 742: 'सुलाना', 743: 'कालीन', 744: 'मुद्दे', 745: 'समकय', 746: 'फ़्रांसीसी', 747: 'तत्व', 748: 'भरते', 749: 'कोरिया', 750: 'उन्हीं', 751: 'शुलऋ-ऊण्श्छ्ष्-क', 752: 'ठहरा', 753: 'ढनीति', 754: '=', 755: 'जागरा', 756: 'स्याही', 757: 'ल्क्ष्य', 758: 'देखभाल', 759: 'समुंदर', 760: 'अरुचि', 761: 'आता', 762: 'ऐक्सीडेंट', 763: 'प्रवृत्तियों', 764: 'काराई', 765: 'तोड़ो।', 766: 'छात्र,', 767: 'टिपण्णी', 768: 'संवाद', 769: 'पापा', 770: 'मलमल', 771: 'दोहराने', 772: 'लेना-देना', 773: 'स्वायत्तता', 774: 'उभरे', 775: 'सदी', 776: 'खोलो!', 777: 'चाहूंगी,', 778: '(राजनीतिक)', 779: 'रौंद', 780: 'अपर्याप्त', 781: 'मंत्रालय', 782: 'जल', 783: 'प्रकोप', 784: 'दायरे', 785: 'उल्हासनगर', 786: 'स्वीकार', 787: 'पड़ते', 788: 'दीजिए।', 789: '...', 790: 'गवर्नमेंट', 791: 'कक्षों', 792: 'तैरकर', 793: 'ब्रितानी', 794: 'भरती', 795: 'जुटी', 796: 'ब्यौरा', 797: '1979-80', 798: 'पिता', 799: '(domestic', 800: 'पेड़-पौधों', 801: 'कमर', 802: 'जनता', 803: 'विशेष', 804: 'सिक़्के', 805: 'कवायदों', 806: 'अवधारणा', 807: 'देता', 808: 'प्रकाशक', 809: '(VOCs)', 810: 'बढ्ना', 811: '३-वर्षीय', 812: 'एल्गोरिदम', 813: 'उछलती', 814: 'बंगालनागपुर', 815: 'वॉर्मिंग', 816: 'मैसेजिंग', 817: 'मिली?', 818: 'डालदो।', 819: 'मे', 820: 'करूँ', 821: 'मध्य', 822: 'फिक़ह', 823: 'रक़्तस्राव', 824: 'गोलीबारी', 825: 'ख़रीदीं', 826: 'पहनता', 827: 'जेसा', 828: 'तेराब्य्ते', 829: 'आर्टिलरी', 830: 'दामहृ', 831: 'निबंधों', 832: 'पचास-एक', 833: 'ऑस्ट्रेलिया', 834: 'सकेगा', 835: 'बोला।', 836: 'षेसिडेन्टिअल्', 837: 'वर्धमान', 838: 'पन्ना', 839: 'ज़रूर', 840: 'पत्तियाँ', 841: '1956', 842: 'दीवान-ए-खास', 843: 'वैमानिकी', 844: 'ग', 845: '|', 846: 'देवर', 847: 'अस्पताल', 848: 'तैवान', 849: 'तू', 850: 'जूड़े', 851: '(फेरुनुलम)', 852: '(पूर्व', 853: '(plywood)', 854: 'घूम', 855: 'सान्याल', 856: 'समेत', 857: 'रत्न', 858: 'गुलदान', 859: 'करोगे?', 860: 'अलीगढ', 861: 'ललू', 862: 'बोलती', 863: 'बंध', 864: 'अंतराल', 865: 'माँ-बाप', 866: 'अध्यात्म', 867: 'विष्णु', 868: 'हुएँ', 869: 'माने', 870: '(यदि', 871: 'निर्वासनों', 872: 'दूंगा।', 873: 'खंडन', 874: 'Mahatma', 875: 'अनके', 876: 'कोर्ट', 877: 'match)', 878: 'पियानिस्ट', 879: 'वेबसाइट', 880: 'दूँगा।', 881: 'प्रबंधन,', 882: 'फूलन', 883: '१८८८', 884: 'आभा', 885: '२२४/५', 886: 'दुम', 887: 'सार्वजनिक', 888: 'लालकिले', 889: 'बुर्ज', 890: 'आराम', 891: 'इनकी', 892: '(advertisements)और', 893: 'चुट्टांबलम', 894: 'स्वाभाविक', 895: 'प्लैन', 896: 'भूमध्यरेखा', 897: 'फंच', 898: 'आत्मविश्वास', 899: 'सूरदास', 900: 'उम्मीदवार', 901: '27', 902: 'दोपहरभर', 903: 'हमको', 904: 'फैलती', 905: '50,000', 906: 'इनमें', 907: 'गोबोट.', 908: 'अनुशासन', 909: 'Err:509', 910: 'वो', 911: 'वापिस', 912: 'ईर्ष्यालु', 913: 'गरीब', 914: 'कई', 915: 'गवर्नर', 916: '१८८९', 917: 'I', 918: 'सकती', 919: 'पृथक', 920: 'असहमति', 921: 'जाएगी।', 922: 'संस्कृत', 923: 'थे,', 924: '(H2CO)', 925: 'विलोम', 926: 'कहानियाँ', 927: 'अड्डा', 928: 'क्षेत्रॉ', 929: 'पूछें', 930: 'अभिनेताओं', 931: 'करों', 932: 'हिन्द', 933: 'तथापि', 934: 'पद्धती', 935: 'प्रकट', 936: 'यव', 937: 'किंतु', 938: 'खिड़कियाँ', 939: 'अधिकार', 940: 'बैण्टोनाइट', 941: 'योगदान', 942: 'पुराणों', 943: 'बन्द)', 944: 'दिमाग़', 945: 'संगिनी', 946: 'cloud)', 947: 'ट्रिब्यूनल', 948: 'इजसके', 949: 'कपिल', 950: 'एच', 951: '685682', 952: 'से', 953: '“James', 954: 'स्वचलित', 955: 'सामान्यत', 956: 'कीजिएगा,', 957: 'गईं', 958: 'ऑर्डर', 959: 'बजे', 960: 'नीला', 961: 'शक्कर', 962: '(चाहे', 963: 'छोड़ी', 964: 'ये', 965: 'ख़ुद', 966: '१९९१-१९९२', 967: 'पेशियों', 968: 'लगों', 969: 'शायद', 970: '!', 971: 'हालात', 972: 'आंका', 973: 'संस्करण', 974: 'मिश्रण', 975: 'मोड़े,', 976: 'मिलेगी।', 977: 'प्रेमचंद', 978: 'जताई।', 979: 'शाखा', 980: 'गलफड़ों', 981: 'जानती', 982: 'यूट्यूब', 983: 'मोह', 984: 'एवज', 985: 'Board', 986: 'गुण', 987: 'सीमंकी', 988: 'शुरुवात', 989: '(Test', 990: 'प्रथमार्ध', 991: 'नॉट', 992: 'अजनबियों', 993: '\u200eउसने', 994: 'निबटने', 995: 'पहुंचाना', 996: 'संचालित', 997: 'सब्जियों', 998: 'तोदाइजी', 999: 'कमेटी', 1000: 'बल्लेबाजो', 1001: 'थैलों', 1002: 'सुविधाओं', 1003: 'वार्मिंग', 1004: 'चींचीं', 1005: 'गजलक्ष्मी', 1006: 'हादसा', 1007: 'श्रेणी:संयुक्त', 1008: 'ज्ञानकोष', 1009: 'आवश्यकता', 1010: 'है।', 1011: 'गाय', 1012: 'करो।', 1013: 'मोटरसाईकल', 1014: 'खिलड़ियों', 1015: 'पड़ा।', 1016: 'Available', 1017: 'चाहतें', 1018: 'की,', 1019: '२५%', 1020: 'गंभीर', 1021: '(१९८१)', 1022: 'शैली', 1023: 'अलंकृत', 1024: 'ईमानदार', 1025: 'गृह', 1026: 'नये', 1027: 'दोनो', 1028: 'हॊ', 1029: 'इसलिये,', 1030: 'दवाईयों', 1031: 'फेर', 1032: 'कंप्यूटर', 1033: 'अपूर्ण', 1034: 'मोटी', 1035: 'ग्लासिअल', 1036: 'रास्ता', 1037: 'हवाना', 1038: 'कराया', 1039: 'लंबा', 1040: 'उदा', 1041: 'अवशेष', 1042: 'विकासात्मक', 1043: 'प्रत्येक', 1044: 'बंदर', 1045: 'साधारणत:', 1046: 'मीटर', 1047: 'पल्लवों', 1048: 'म्युज़ियम', 1049: 'नींद', 1050: 'मंदिरों', 1051: 'लम्बे', 1052: 'बाँध', 1053: 'स्काटिश', 1054: 'फेडरशन', 1055: 'आया।', 1056: 'डाले', 1057: 'आखें', 1058: 'कमनीय', 1059: 'राजखोसला', 1060: 'इसको', 1061: 'बूढ़े', 1062: 'उत्तओजना', 1063: 'चाह्ती', 1064: 'उदसे', 1065: 'थर', 1066: 'नौकरशाह', 1067: 'राज्यसंगठन', 1068: 'जैसे,आपको', 1069: 'क्रीज', 1070: 'करदो।', 1071: 'अनुमोदनार्थ', 1072: 'त्रिकोणीय', 1073: 'मकान', 1074: 'मुखबिरों', 1075: '(हिजरी', 1076: 'पंद्रह', 1077: 'किसलिए', 1078: 'से]', 1079: 'गहमागहमी', 1080: 'समानित', 1081: 'भारती', 1082: 'गुट', 1083: 'उड़ाने', 1084: 'सुदूर', 1085: 'भागवत', 1086: 'प्रदर्शित', 1087: 'स्राव', 1088: 'मुझमें', 1089: 'उठाते', 1090: 'स्थ', 1091: '१८५०', 1092: 'गोलियों', 1093: 'दमयन्ती', 1094: 'आलेख', 1095: 'लक्षणों', 1096: 'रहता', 1097: 'घुसादो।', 1098: 'अंधकार-युक्त', 1099: 'प्रभावी', 1100: 'सीखनी', 1101: 'गाते', 1102: 'जटिलताएं', 1103: 'बनाओ”', 1104: 'पौधों', 1105: 'भार', 1106: 'सोमवार', 1107: 'शीशी', 1108: 'लेना।', 1109: 'घर', 1110: 'ताकत', 1111: 'यूरोपीय', 1112: 'terrorism)', 1113: 'प्रतियोगितात्मक', 1114: 'टाटा', 1115: 'Chote', 1116: 'बनने', 1117: 'कॉलेज', 1118: 'सफ़ाई', 1119: 'पात्र', 1120: 'असत्य-मार्ग', 1121: 'टाइपैड', 1122: 'खिलाफ', 1123: 'ऋषि', 1124: '१९४७', 1125: 'दरगाह', 1126: 'बनते', 1127: 'हवाईजहाज़', 1128: 'घुमाऊं,', 1129: 'विमर्शो', 1130: 'व्याख्यान', 1131: 'बेहतरीन', 1132: 'योग्यता', 1133: 'रोमांच', 1134: 'लेने', 1135: 'मानिए,', 1136: 'प्रवाहित', 1137: 'अपमानित', 1138: 'सकने', 1139: 'चोरी', 1140: 'कंपनी', 1141: 'पाए', 1142: 'जया', 1143: 'कंबल', 1144: '२५००', 1145: 'लगभग', 1146: 'संवेदनाओं', 1147: 'कल्पनाओं', 1148: 'आँसुओं', 1149: 'मूलभूत', 1150: 'बेजा', 1151: 'आऊट', 1152: 'आपके', 1153: 'रहकर', 1154: 'सिखाया।', 1155: 'नीली', 1156: 'हुयी', 1157: 'संयोग', 1158: 'मानना', 1159: 'छीना', 1160: 'मारे', 1161: 'चालू', 1162: 'झलक', 1163: 'बनना', 1164: 'गत', 1165: 'जबरदस्त', 1166: '☻☻☻☻☻', 1167: 'महज', 1168: 'उत्सर्जित', 1169: 'खुशकिसमत', 1170: 'दुखदायी', 1171: 'ब्लॉग', 1172: 'फ्रांस', 1173: 'सिर्फ', 1174: 'बुनियादी', 1175: 'अधिसूचना', 1176: 'वॉयल', 1177: 'विकिरणों', 1178: '२०', 1179: 'अपेक्षित', 1180: 'संवेदना', 1181: 'ज़हरीले', 1182: 'डी.एन.ए', 1183: 'कंजूस', 1184: 'बाताऊँगी।', 1185: 'दिये', 1186: 'बाँट', 1187: 'मुहतसिब', 1188: 'दुर्घटनाएँ', 1189: 'तय', 1190: 'एच.ई.सी', 1191: 'जिनकी', 1192: 'पेंटिंग', 1193: 'ग्रंथालय', 1194: 'यो', 1195: 'तेरा', 1196: 'रखा', 1197: 'ठहराएगा', 1198: 'हटीं', 1199: 'प्रस्थान', 1200: 'महंगा', 1201: 'गुर्दों', 1202: 'चिकितऋद्दसासऋद्दथान', 1203: 'नेतृत्व', 1204: 'विपरीत', 1205: 'मुहम्मद', 1206: 'रखते', 1207: 'गलती', 1208: 'वाशिंगटन', 1209: 'ऋषि-मुनियों', 1210: 'श्रेणी:नोबेल', 1211: '१५००', 1212: 'अरब', 1213: 'विविधतापूर्ण', 1214: 'मिथाइल', 1215: 'नजदीक', 1216: 'निकायों', 1217: '(troposphere)में', 1218: 'उत्तम!', 1219: 'लें', 1220: 'वाहन', 1221: 'हिन्द-आर्य', 1222: 'काटो।', 1223: 'समझकर', 1224: 'पाएगा।', 1225: 'मजबूरियों', 1226: 'याचिकादाता', 1227: 'पिऊँगा,', 1228: 'गीतात्मक', 1229: 'बैंड', 1230: 'बुआ-जी', 1231: 'खिलते', 1232: 'सल्फाइड', 1233: '60,000', 1234: 'पर.', 1235: 'वी/एसटीओएल', 1236: 'गहरा', 1237: 'ऋतुएं', 1238: 'घोड़ा', 1239: 'आईए।', 1240: 'दिखाना', 1241: 'बना', 1242: 'आयात', 1243: 'कजा', 1244: 'बारे', 1245: 'बजट', 1246: 'बकवास', 1247: 'पार्लियामेट', 1248: '(conflict).संघर्ष', 1249: 'पेकिंग', 1250: 'मजदूरी', 1251: 'प्रातः', 1252: 'कोलम्बस', 1253: 'विचारशील', 1254: 'खान', 1255: 'सांस्कृतिक', 1256: 'कायल', 1257: 'तक,', 1258: 'कर,', 1259: 'कॉमिक', 1260: 'आजमगढ़', 1261: 'बोलने', 1262: 'विलम', 1263: 'कुछेक', 1264: 'नियत', 1265: 'अलाउद्दीन', 1266: 'करूँ।', 1267: 'इनसे', 1268: 'उछलो.', 1269: 'भरना', 1270: 'आओ', 1271: 'दूरदर्शिता', 1272: 'अनधिकृत', 1273: 'विवेकाधिकार', 1274: 'मंगवाया', 1275: 'गठन', 1276: 'मंज़िल', 1277: 'सामान्य', 1278: 'व्यतीत', 1279: 'पर्वतों', 1280: 'रखनी', 1281: 'ऑपरेशन', 1282: 'मरा।', 1283: 'भीत्त', 1284: 'अधिनियमों', 1285: 'जुड़', 1286: 'प्यार', 1287: 'संभावनाओं', 1288: 'ज़िला', 1289: 'बडी', 1290: 'बीवी', 1291: 'भरी', 1292: 'शीध्र', 1293: 'अनुरेखक', 1294: 'काट', 1295: 'अधीक', 1296: 'कर्ण', 1297: 'रूचिकारक', 1298: 'डरना', 1299: 'सेनाएँ', 1300: '१', 1301: 'पांडिचेरी', 1302: 'बंदूक', 1303: 'बन्धन', 1304: 'पुष्टि', 1305: 'बेमानी', 1306: 'साइकिल', 1307: 'नमस्ते।', 1308: 'चाहते', 1309: 'प्रयोजन', 1310: 'वासुदेव', 1311: 'मित्र', 1312: '12', 1313: '१९९०', 1314: 'तुम्हारा', 1315: 'हेल्थ', 1316: 'चलानी', 1317: 'उभरा', 1318: 'बंगाल', 1319: 'कीजिएगा।', 1320: 'तेजी', 1321: 'तोड-फोड़', 1322: '17', 1323: 'Journal)ने', 1324: 'रिटा