<a href="https://colab.research.google.com/github/PriyanshuChaudhary00/English_to_hindi_using_encoder_decoder/blob/main/Hindi_to_english.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [130]:
import torch
import torch.nn as nn
import torch.optim as optim
import random

In [87]:
# #!/bin/bash
# !kaggle datasets download preetviradiya/english-hindi-dataset

In [88]:
# !unzip english-hindi-dataset.zip

In [89]:
import pandas as pd

In [90]:
df = pd.read_csv("Dataset_English_Hindi.csv")

In [91]:
df.head()

  English    Hindi
0   Help!    बचाओ!
1   Jump.    उछलो.
2   Jump.    कूदो.
3   Jump.   छलांग.
4  Hello!  नमस्ते।

In [92]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 130476 entries, 0 to 130475
Data columns (total 2 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   English  130474 non-null  object
 1   Hindi    130164 non-null  object
dtypes: object(2)
memory usage: 2.0+ MB

In [93]:
df["English"] = df["English"].str.lower().str.split()
df["Hindi"] = df["Hindi"].str.split()

In [94]:
df.head()

    English      Hindi
0   [help!]    [बचाओ!]
1   [jump.]    [उछलो.]
2   [jump.]    [कूदो.]
3   [jump.]   [छलांग.]
4  [hello!]  [नमस्ते।]

In [95]:
df["Hindi"] = df["Hindi"].apply(
    lambda x: ["<start>"] + x + ["<end>"] if isinstance(x, list) else ["<start>", "<end>"]
    )

In [96]:
df.head()

    English                      Hindi
0   [help!]    [<start>, बचाओ!, <end>]
1   [jump.]    [<start>, उछलो., <end>]
2   [jump.]    [<start>, कूदो., <end>]
3   [jump.]   [<start>, छलांग., <end>]
4  [hello!]  [<start>, नमस्ते।, <end>]

In [97]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 130476 entries, 0 to 130475
Data columns (total 2 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   English  130474 non-null  object
 1   Hindi    130476 non-null  object
dtypes: object(2)
memory usage: 2.0+ MB

In [98]:
df_subset = df.head(5000)

In [99]:
vocab_english = []
for i , sentance in enumerate(df_subset["English"]) :
  vocab_english.extend(sentance)
  # print(sentance)
  # if i == 5000 :break
vocab_english = list(set(vocab_english))
vocab_english = ["<pad>" , "<UNK>"] + vocab_english
print(vocab_english)

['<pad>', '<UNK>', 'of', 'vishwa', 'not),', 'control', 'cave.', '-pace,', 'morning.', '27', "'sum", 'explain.', 'imposed', 'geypadoan', 'pendulum', 'treaty', 'photosynth,', 'everywhere', 'barabaki', 'brother', 'matter', 'caustic', 'london?', 'bath.', 'identities', 'nice', 'knife', 'run.', 'wine.', 'strange', 'me.', 'rome', 'you', 'traitor.', '“”global', 'terrorists', '1979-80', 'represents', 'drona', 'terrorism.', 'discomfort', 'squirrel', 'lachmi', 'inflict', 'combined', 'highways', 'drinks?', 'infrastructure', 'decorated', '5,00,000', 'mean', 'insurgency', 'customs', 'maulana', 'foreign-made', 'loyalty', 'matter?', 'disappointed.', 'natures', 'rolling', 'earlier.', 'bipin', 'singer', 'visvabharati', 'imperialist', 'japanese.', '265', 'industrial', 'salient', 'pardon', '“”chandravanshi-suryavanshi“”', 'resolutions', 'seek', 'abstract.', 'grand', 'memoirs', '1980s.', '[unclear],', 'mandaley', 'markup', 'steam', 'crudest', 'inevitable', 'flow', 'profession', 'eds.)', 'skies', 'representing', 'contrast', 'courts-', 'helen', 'requested', 'once.', 'timber', 'considered', 'orphan.', 'lecture', '650,000', 'motherland', 'summer.', 'crew', 'least', 'pressure', 'poisoned', 'races', 'mysore', 'ammonia', 'rung', 'golf.', '99,', 'enhancements', 'breakthrough', 'willing', 'everest', 'yields', 'language;', 'privileges', 'ashwin', 'side,', '“if', 'public.', 'presiding', 'tokyo."', 'involvement', '(1946)', 'relevant', '14,000', 'whose', 'situation', 'forehead.', 'resisted', 'properly', 'divided', 'dhrutrashtra', 'nations', 'invention', 'tulsi', 'faces.', 'else', 'allahabad', 'organization(who)', 'for', 'arbitrator', 'padas', '(perspective)', 'decades', 'troops', 'administrative', 'door?', 'context', 'ashtank', 'dense', 'soon.', 'unceremoniously', 'foam', 'thrust', 'udahrano', 'failure,and', '(gujrat)', 'lowering', 'stated', 'amalgamation', 'facade', 's.', '3100-5600', '“design', 'colliery', 'each', 'split', 'returned', 'jaya.', 'deliberately', 'resource,', 'miss', 'abdominal', 'aatre', 'farakka', 'blames', 'ruled', 'ruling', 'coming', 'prince', 'clothes', 'murder', 'bull', 'pace', 'original', 'jahangir', 'girls.', 'dad', '1947.', 'calling', '3,262', 'cute.', 'recorded', 'track', 'resultant', 'nauseous.', 'sweater', 'while', 'intuition', 'like,', 'supposed', 'tall', 'england.', 'sullied', 'circumstances.', 'sang', 'punjab', 'complained', 'dial', 'bill', 'subject,', 'ghosts.', 'hygiene', 'bytes', 'proyog', 'name?', 'carrier', 'gun', 'made.', 'spite', '2004,', 'affiliation', '324[1],', 'game,', 'prospect', 'pallava', 'tanker', 'distant', 'much.', 'darkness', 'expenses.', 'ram', 'definitely!', 'whip', 'big.', 'stomach', 'chief', 'words.', 'comparable', 'servants', 'topic', 'be?', 'runs.', 'form,', 'blue', 'bharatendu', 'friend.', 'advent', 'patterned', '“”your', 'wiped', 'planning', 'restriction', 'samser', 'somebody.', 'wife.', 'surya', 'glum', 'waiting.', 'principles', 'structure', 'drona:', 'mukhlis', 'complexes', '1803', 'peking', 'kuda', 'tokyo,', 'marut-pa', 'sunga,', '1947,', 'scale', 'plant', 'declares', 'four', 'haji', 'typewriter', 'balls.', 'posture', 'religion.', 'unrealistic', 'nevertheless', 'european', 'woke', 'associated', 'requisite', '12th', 'check', 'sanskrit_ocr', 'interfering', 'focus', 'jamshedpur', 'task.', 'produced', 'deposits', 'operate', 'judicial', 'breast', 'positive', 'exposed', 'fed', 'men)', 'plus', 'hit', 'hero', 'dose', 'boars', 'speaking,', 'f)', 'chakrabarti', 'developed', 'aboriginal', 'library', 'bmc,', '6th-7th', 'foundation', '(fehruanulam)', 'cost.', 'our', 'concentrations', 'nepal.', 'censor', 'wrong?', 'fire“”', 'party)can', 'italy.', 'metaphysical', 'english?', 'proceed', 'hair.', 'finally', 'practised', 'carries', 'forts', 'tame.', 'pipe', 'weather', 'daal', 'film', 'work.', 'possibilities', '1939', 'summed', 'calcutta', 'compensation', 'model', 'drinkable.', '[according', 'liturature:', 'british-indian', 'round', 'completely', 'orissa', 'little.', 'expiation', '[if', 'curtailed', '1.because', 'cut', 'sulphide', '224', 'done.', 'messaging', 'hate', 'swollen', 'season', 'now?', 'research', 'europe', 'karunguzhi', 'nothing', 'lahaul', 'way', 'mine', 'nuisance', 'rites', 'indulging', 'waited', 'square', 'diminished', 'manured', 'him?', 'errand', 'world,', 'arising', 'protest', 'lishment', 'disappointment.', 'across.', 'crucifix', 'ultra-left', 'imagine', 'indeed', 'autocracy', 'conquests', 'commercial', 'green', 'foot.', 'kshetrapala', 'digital', 'put', 'arithmetic', 'syed', 'goes,', 'choudhury', 'attitude', 'third', 'invitation.', 'honoured', 'religion,', 'woven,', 'ghat', 'genital', 'should', 'requires', 'sister.', 'voluntary', 'inside.', 'longer', 'exposure', "power's", 'convinience,', 'bihar', 'swear', 'noise', 'bugs', 'browse.', 'wise', 'valid', 'years,', 'ideals', '1850,', 'inquire', 'equal.', 'insulin', 'director-general', 'birthday.', 'loyalty.', 'these?', 'recurring', 'contribute', 'diplomatically', 'arrange', "i've", 'fundamental,', 'factor', 'acute', 'meant', 'guntur', 'preventive', 'island', 'centres', '14', 'reach', 'gradual', 'sprinkles', 'nehru', 'vivan', 'believes', 'devote', 'nimbark,', 'connotation', '63', 'central', 'general,', 'baby.', 'tennis', 'qualify', 'last', 'god', 'amithab', 'doctor', 'filmfare', 'vote', 'reserves', 'saamvedh', 'done', 'talks', 'officer', 'non-partisan', 'justice', 'antarraman', 'one.', 'prestige', 'allowed', 'projected', 'hatred', 'know', 'works.', '1-1/2', 'group,', 'embezzled', 'flooding', '2000,india', 'entrusted', 'arrival', 'release', 'birthday!', 'listening.', 'missed', 'newsprint', 'tablets', 'proteins', 'nice.', 'berating', 'happen', 'danceroom', 'provincial', 'assessment', 'videos,', 'documents.', '97', 'leftist', 'virasikhamani', 'arab', 'chitvan', 'sufficiently', 'galaxy,', 'male-specific', 'shoeing', 'smiled', 'favor', 'soothe', 'laid', 'dominions', 'course,', 'upbraided', 'break', 'man,', 'bridge.', 'dreams', 'angle', 'v', 'successful', 'photograph', 'fewer', 'prompt', 'lone', 'days', 'ideologically', 'happened', 'grooming', 'impact', 'rear', 'usual', 'universityfor', 'roads', 'acknowledgement', 'typical', 'afraid', 'ligament', 'paes', 'recent', 'discourse', 'with?', 'current', 'madhwa', 'lose.', 'rajasthan.', 'duration', '8', 'january', 'dangerous.', 'loaded', 'gallows', 'custom', 'instrument', 'thirsty.', 'counted', 'cult', 'population', 'falls', 'baggage?', 'researches', 'elaborately.', 'dove', 'profit-crazy', 'ventured', 'us?', 'status', 'hungry', 'abcl', 'aligarh,', 'gurus', 'idea.', 'thus', 'manager', 'falls.', 'sit.', 'best,', 'request', 'bit.', 'husband.', 'fostering', 'drink', 'superintentant', 'galaxy', '“now', 'font', 'consulted', 'courses', 'please', 'bank,', 'untouchability', 'taken', 'cells)', 'born', 'outstanding', 'weather."', 'rabindranath', 'oars', 'drawing', '(icc),', 'absolutely', 'murder.', 'pistol', 'sleepy.', 'municipal', 'destruction', '181,278', 'subunits', 'depending', 'maximum', 'dictionary.', 'feeling', '(1958)', 'persian', 'supper.', 'colds', 'depended', 'portraits', '2008.', 'wo', 'brain', 'intends', '0.001', 'shop', 'portuguese', 'doordarshan', 'arzu', 'vidyapathi', '[any]?', 'publisher:', 'shooting', 'ramchandra', 'approximately', 'autism', 'casual', 'drudgery', 'undertook', '“”gamal', 'atharvavedh-', 'villages', 'products', 'gods', 'human', 'districtscomprising', 'nuts.', 'pride', 'station.', 'harichandra', 'manufactures', '1876-77', 'calculate}in', 'supervisor', 'bullet.', 'gloating', 'honest.', 'cultural', 'pertaining', 'syeds', 'future', 'due', 'assent', 'staple', 'jungle', 'pleasure', 'delicate', 'fined', 'orthopaedic', 'weaving', 'dance,', 'zindabad.', 'farmlands', 'wears', 'suicide', 'ceased', 'repeated', 'cancer.', 'poets,', 'pretty.', 'bat)', 'fact', "beatles'", 'feynman', 'tends', 'fit,', 'questions.', 'lesser', 'leaped', '1973', 'sons', 'face.', 'club', 'niche', 'black?', 'realize', 'dais', 'headquartered', 'sadhu', 'year-old', 'sentences', 'ballabhacharya.', 'head?', 'discard', 'wing', 'stingy.', '1350', 'undue', 'mahal', 'go', 'manufacturing', 'clouds', 'staring', 'chalukyas', 'batter', 'intelligence', 'gut', 'epoch-making', 'radio', 'sanskrit-first', 'mahanta', 'fool', 'music,', 'seventh', 'account.', 'followed', 'foreign', 'taila', '1,500', 'schedule', 'forgot', 'hear?', 'exhibition,', '"yes', 'marked', 'quadrangular', 'bonnet', 'leg-spin', 'inflame', 'sluggish', 'disqualified', '1995', 'females', 'like.', 'seats', 'bite', 'hungry.', 'day', 'beauty', 'spurious', 'mix', 'cat?”', 'sugary', 'liquor', 'see.', 'exaggerated', 'hinda', 'bowling.', '1131', '“”agreshvar', "i'll", 'curing', 'couple', 'stand', 'a.m.', 'connection.', 'unapproachable', 'team.', 'directed', 'blasting', 'ulasnagar', 'played', 'catalogue', 'example.', 'supremacy', 'morals', 'exception', 'discussed', 'television.', 'b', 'machine.', 'we', 'elderly', 'prided', 'alcohol.', "she's", 'which', 'stroke', 'expenditures', 'adjacent', '31', 'important.', 'advaita', 'mirzapur,patna,and', 'paragraph', 'countries.', 'story', 'instead', 'april', 'oath', 'considerations', 'trees', 'require', 'bern', 'broaden', 'bring', 'in', 'england', 'bachchan', 'iconography', 'purse.', 'vainglorious', 'devi', 'norms', 'courts', 'exquisitely', 'basit', 'legislatures', 'vegetables', 'electoral', '(the', 'court.', 'hard.', 'ceylon', 'sites', 'acquiring', 'informtion', 'inclined', 'warned', 'u.s.department', 'local', 'regulating', 'visiting', 'terrorism', 'paragraphs', 'adopt', 'attest', 'attractive', 'delisting', 'snowball', 'form', '(choice)', 'st', 'circus', 'narayan', 'abandoned', 'struggled', 'particular', 'behaviour', 'existed.', 'pigeons', 'towards', 'tonnes.', 'bus.', 'gradually', 'script', 'resign', 'janmejay.', 'bombing', 'attract', 'felt', 'reconditioned', 'region', 'w', 'betrayed', 'oxford', 'ownership', 'longest', 'accomplished', 'write', 'infant', '“but,', 'output', '(development', 'bold,', 'elevator', 'robot.', 'account', 'frequently', 'hijri,', 'bending', 'photons', 'sunday?', 'reasonable', 'production', 'secured', 'g.v', 'fat.', 'correlation,', 'khurian', 'manages', 'core', 'arguments', 'melted', 'impass.', 'kinship', 'politics', 'readies', 'cave-temple', 'runs', 'august,', 'fly.', 'milk.', 'suing', 'ink?', 'barmak', 'haste.', 'late', 'conscious', 'attain', 'leaves', 'technological', 'merits', 'self-reliant', 'elastic.', 'do', 'demanding', 'leaf-a', 'outside.', 'zankar', 'stamp', 'salas', '266', 'open', 'everything.', 'tracks.', 'scepticism', 'attracts', 'died.', 'pilot', 'tchub', 'pada', 'ship.', 'thin.', 'bhishma', 'rooms.', 'communitythe', 'seem', 'turkey.', 'harder', 'excuse.', "'re", 'relationship', 'often', 'prescription', "we're", 'convert', 'daughters.', 'netaji', 'stairs', "'ll", 'developmental', '1958', 'post', 'chandra', 'expedient', 'files', 'congratulate', '1917', 'dug', 'recommend', 'gaslight', 'cama', '200', 'wicket.common', 'office.', '80', 'sleeping', 'tiger', 'called', 'motor', 'welcome', 'next-door', 'change', 'complain', 'phone.”', 'viewpoint,during', 'peace.', '6', 'says.', 'pounds', 'ganghasnan', 'hazari', 'muslims', 'keeps', 'slowly?', 'alpa', '3:', 'jumping', 'sari', 'fibbi', 'fashion', 'adversely', 'entrance', 'hindrance', 'chewing', 'measured', 'examples.', 'wool.', 'mother', 'parturition', 'jacket.', 'tickets', 'appearing', 'shan', 'late.', 'theater', 'expected', '1998', 'cradle.', 'accounted', 'grasshoppers', 'revolution', 'hens', 'yesterday!', 'oblation,', 'somehow,', 'belong', 'cupboards', 'farms,', '1960', 'hokkaido?', 'lets', 'bottles', "akbar's", 'institution', 'easy.', 'risk', 'carts', 'fate', 'south', "brahma's", 'honor', 'offerings', 'strong', 'absolute,', 'tails', 'yourself.', 'complexity.', 'scot', 'will.', 'cost?', 'ch4', 'thoracic', 'subba', 'many', 'hormonal', '1980s', 'extra', 'kipling', 'pawns', 'undertaken', 'japan', '[o3]', 'ten-year-old', 'golden', 'harinarayana', 'yours?', 'searching', 'notoriously', 'films', 'approaching', "camera's", 'beard.', 'horses', 'tekchand', 'anything.', 'purchases', 'prior', 'nida', 'tribunal', 'characters', 'cancel', 'ocean,second', 'baseball.', 'spanish', '2008,', 'block', 'hexafluoride', 'tolerate.', 'reeks', 'up', 'vivekanand(12th', 'peek', '25,980', 'set', 'feel', 'gurudev', 'specifically', 'agra', 'seeds', 'goal', '375', 'p+q', 'drowsy', 'spending', 'then.', 'cured', 'meanwhile', 'company.', 'advice.', 'bow', 'anything?', 'detachment', 'chini', 'trouble,', 'shouted', 'female', 'bhojraj', 'relations.', 'meaningless', 'science,', 'ranjan', 'wine', 'age', 'dharma', 'wash', 'pickpocketing.', 'tariff', 'said', 'trust', 'yes', 'changsha', 'caught', 'cylset', 'scarab', 'increased', 'ranging', 'soft-drink', 'record', 'navrathris', 'result', 'soverign,', 'destined', 'me,', 'utsava-mandapas', 'agriculture', '1989', 'martial', 'valley.', 'joined-up', 'mountain', 'waterway.', 'items', 'dam,and', 'mauryan', 'unit', 'wakes', 'affronts', 'arrogant.', 'furnished', 'extincted.', 'era|', 'mendelian', 'pradesh', 'dignity', 'parking.', 'performs', 'anniversary', 'reality,“”', 'it)but', 'into', 'fig.4', 'told,', 'three-letter', 'severity,causing', 'parliament.', 'motifs', "o'clock.", 'thing,', 'shrine-cells', 'memorable', 'persons', 'tumbling', 'usman', 'epic.', 'work,', 'associations', 'mucous', 'calamities', 'yesterday', 'bentonite,', 'medium.', 'eye,', 'unconfused', 'culture', 'neoproterozoic,', ',nuclear', 'development,', 'launched', 'eighteen.', 'greenhouse', 'brahmaji', 'explains', '1991-1992', 'pitied', 'gold', 'move', 'effect', 'silence', 'delivers', 'quality', 'negative', 'nakkarkhana', 'salary', 'erijona', 'everybody', "vishnu's", 'staff', 'summary', 'ago,', 'relations', 'sur', '138', 'phoolan', 'taiwan,', 'about,', 'contract', 'indigo', 'everyone', '...', 'dealing', 'rosey', 'low-cost', 'pakistanis', "“i'm", 'restaurant', 'resolution', 'impeccable', 'shurpanakha', 'sighned.', 'schemes', 'shirt.', 'measure', 'dust-storms', 'convention', 'monopolies', 'savarkar', 'provinces', 'scruple', "what're", 'survival', 'cushion', 'shot.', 'come,', 'i.', 'me!', 'broz', 'octagon,', 'gujarat', 'would', 'sree', 'therefore', 'intended', 'empirical', 'bramha', 'aloud.', 'parents?', 'jati', 'extract', 'biography', 'below,', 'vidur', 'ok?', 'storage', 'liked', 'calculation,', 'abstract', 'why', 'tons', 'metabolism', 'glucose', 'objects', '(e-paper,unicoded)', 'filled', 'gentle', 'preached', 'winning', 'eligible', 'innovation', 'snow', 'forward', 'gases', 'women', 'jaitly', 'wedding', 'consultant', 'wonderful', 'sirajuddin', 'begins', 'secure', 'malaria,', 'whistling', 'fast-day', 'smoke?', 'innovative', 'meeting.', 'writings', 'tonal', 'sought', 'renuka', 'teeth', 'force,', 'strong,', 'treasure.', '1977.', 'taught', 'supply', 'showing', 'gold.', 'clarificatory', 'somnathpur', '3.42', 'travelers', 'tumor', 'currency', 'accountable', 'army,', 'seeing', 'web', 'understand,', 'e', 'continents', 'brij', 'ignored', '1865.', 'achieved', 'soup.', 'there?', 'plenum', 'deities', '}or', 'remember.', 'overseas', 'story?', 'chennakesvara', 'increasing', 'hurried', 'enforcement', "'naldhamayanthi'", 'octagon', 'ocean', 'swimming.', 'seamonkey', 'pakistan]', 'forthcoming', 'tilawat.', 'nevada', 'spanish.', 'room.', 'revolution,the', 'graveyard.', 'mention', 'misunderstood', 'weighed', '1927', 'application.', 'fernandes', 'satellite', 'muhammad', 'tar', 'tata', 'altogether', 'providing', 'maharashtra.', 'strategy', 'modularized', 'horse.', 'bike', 'brothers?', 'match.so', 'offences', 'teaching.', 'occasionally', 'anybody', 'sounds', 'elaborates', 'where,', 'final', 'cabinet', 'mostly', 'p.n', 'facilities', 'jobseekers', 'temperature', 'ashokvatika', '“nyan', 'kids?', 'challenge', 'suits', 'rajput', 'music.', 'uma', 'medicine', 'warming', 'unesco', 'successful.', 'me', 'philanthropy', "deer's", 'numbers', 'thinks', 'home-bred', 'grandmother.', 'pushcart.', '“”set', 'skilled', 'yellow', 'rebirth', 'questions?', 'habit.', 'upheavel', '(prays)', 'rooms,', 'bored.', 'special', 'comfort', 'german.', 'montana', 'sifferent', 'egg', 'bibliography', 'obstinate', 'ali', 'and,', 'worse', 'then,', 'non-maintained', 'liberalism', "(1998)'", 'roses.', 'him,', 'cake.', 'straight', 'ill', '90', 'real', 'nagesh', 'drained', 'haze', 'cats', 'shared', 'sides', 'studied', 'applies', 'estimate', 'styles', 'inc.', 'century', 'nehru:', 'ayodhya', 'colonialism', 'intelligent', 'broke.', 'limited', 'rupnnie', 'commitment', 'tackle', 'nearby.', 'additional', 'pressing', 'arjuna', 'soorsaravali', 'express', 'brahnwnism', 'wonderful!', 'users', 'bankers', 'dna.', 'example', '4-5', 'becomes', 'limits', 'condons', 'durban.', 'com-', 'scientific', 'be', 'affairs', 'thackeray', 'described', 'deal', 'revolution-er)', 'modified', 'court', 'transcendental', 'bathroom.', 'franco-german', 'protection', 'miracle', 'permament', 'produced.', 'chapter', 'acronym.', 'respect', 'afghanistan,', 'taken?', 'sector', 'nine.', 'india', 'hold', 'bicycle.', 'they(homo', 'did.', '1930,', 'lice', 'credible', 'aditya', 'steel', 'childhood.', 'airpix.', 'ambitious', '0.22', 'undavalli', 'sangam', '[japanese]', 'salt?', 'meaning', 'father', 'spmmers', 'mathematics', 'so,', 'palaces', 'aryans,and', 'laughed.', '11', 'supplied', 'excited', 'some', 'student.', 'types', 'spade', 'could', 'program?', 'inspiration.', 'sunk', 'piano.', 'picked', 'proper', 'sectioned', 'senators', '4,', 'workers,', 'cubic', 'revolutionary', 'moral', 'girls', 'necessarily', 'hurry', '(applause)', 'satisfied', "grier's", 'successful,', '15-20', 'kites.', 'businessman', 'sleep.', 'present', 'ideal', 'illness', 'communal', 'mavalankar', '(then', 'pollutants', 'monastery', 'invert', 'ball', '<number>', 'knowing', 'quiet', 'danger', 'dna', 'instrumental', 'potatoes.', 'flying', 'harvest', 'relied', 'stolen', 'upanishad.', 'anyone', 'wretched', 'minds,', 'want', 'parts', 'british', 'deficiency', 'bigger', 'veritable', '100,', 'miyan', 'good-for-nothing', 'personally', 'shall', 'selfish', 'devotee', 'conference.', 'sex', 'sole', 'manifest', 'shiva', 'abused', 'bet', '[1]', 'are', 'help.', 'emphasis', 'camp', '45', 'phd', 'teenagers', 'sung', 'counsel', 'backbone', 'denominational', 'since.', 'turn.', 'hands', 'leave?', 'incident', 'english.', 'trpannee', 'exhibited', 'gives', 'importance,', 'anything', '“”non-alignment“”', 'docility', "one's", 'satellite,', 'paralysis', 'depressing', 'business', 'demise,', 'meet', 'interests', 'computer', "he's", '(united', 'floor.', 'chemicals', 'guru', 'working.', 'causing', 'door,', 'duryodhan', 'acts,', 'incurable', 'yutub', 'rituals', 'crime', 'virgin', 'multiple', 'controlled', 'place', 'fell', 'fever.', 'belur', 'japanese', 'otherwise', 'component', 'permission', 'century,after', 'temporarily', 'complaints', 'tips', 'allowances', 'jagaran', 'tajmahal', 'letting', 'developing', 'mohan.', 'speech?', 'are.', 'fiqh|', '(social', 'direct', 'bermai', 'segregation', '1.75', 'votes.', 'image', 'blue.', 'station', "they're", 'housing', 'balls', 'leaflet', 'desirous', 'justiciable', 'borders.', 'siraj-ul-lughat', 'changes', 'incorporation', 'decided', 'travel', 'bought?', 'sitting', 'betel', 'warnings', 'agree', 'headlines', 'models', 'friendship', 'joins', 'propane', '(emergency)', '1949', 'ira', 'feelings.', 'further', 'teacher?', 'accepted.”', 'resulting', 'points', 'districts', 'ceiling.', 'sacramento,', 'walk', 'rules.', 'tube.', 'anxiety', 'bank', '1860', "kabir's", 'being,', 'pals', 'dividends', 'owned', 'naidu', 'bride', 'stagnation', 'khan)', 'road', 'night', 'allahabad,', 'chose', 'bed.', 'rs', 'all-india', 'engulf', 'comprehensively', 'onetime', 'indoor', 'everything', 'meddle', 'lbw,', 'monthly', 'expressions', 'holy', 'acknowledged', 'reviewing', 'forces,', 'familiar', 'guitar', 'younger', 'branches.', 'clathrate', 'uniform', 'again?', 'dorset', 'lie', 'ayurvedic', 'running', 'consonants', '6.00', 'fortunate', 'chuttambalam', 'truth', 'pollutants.', 'commandant', 'sound', 'sand.', 'see,', 'cafe?', 'goals', 'alters', 'titled', 'foretold', 'sumitranandan', 'needed', 'core.', 'riaz:', 'faulty', "hasn't", 'stronger.', 'singh', 'pronounces', 'lackeys', 

In [100]:
vocab_hindi = []
for i , sentance in enumerate(df_subset["Hindi"]) :
  vocab_hindi.extend(sentance)

  # print(sentance)
  if i == 5000 :break
vocab_hindi = list(set(vocab_hindi))
vocab_hindi = ["<pad>" , "<start>" , "<end>"] + vocab_hindi
print(vocab_hindi)
print(len(vocab_hindi))

['<pad>', '<start>', '<end>', 'लेना', 'स्टेडियमों', 'गणेश', 'सेवन,', 'of', 'याचिका', 'भयंदर', 'नाइजीरियाई', 'ट्रेड', 'ऑस्ट्रेलिया', 'conduct)निषिद्ध', 'देकर', '27', 'कुरियना', 'सत्तासीन', 'देखा,', 'शक्तियों', 'सबको', 'समालोचना', 'उठानी', 'पार्टनर', 'भार', 'सोचो', 'नेहरु', 'बतादेना।', 'जनसंख्या', 'आधे', 'क्लब', 'तर्कसंगत', 'चला', 'मिनट', 'साZथ', 'यव', 'महानता', 'सकलेश', 'आकृति', '1979-80', 'प्लान', 'हटा', 'मिलाली', 'जीते', 'गाने', 'बुलाई', 'नन्हाँ', 'संसार', 'मैमोग्राफ', 'cloud)', 'हिलो', 'सिस्टर', 'उस्मान', 'उम्र', 'बल्ख', 'की,', 'हुये', 'मेहराबाकार', 'स्कूल', 'पहुँचा', 'उतरेगा।', 'काउंटर', 'हवाऋ', 'चुना', 'असुरक्षित', 'ब्रोड', 'नियुक्त', 'चाहता।', 'खिलजी', 'कैदी', 'सादा', 'कम्प्यूटर', 'रोना', 'टीम', 'समझदार', 'सपनों', 'आच्छादित', 'है?', 'चलना', 'राजस्थानी', 'सहभागिता', 'जज़िया', '(carcinogen)', 'मंड़पम', 'हें', 'आपसे', 'बनाओ।', 'आज़माती', 'मम्मी-पापा', 'प्रोग्राम', 'डालोगे', 'पसन्द', 'टाइम', 'गतिविधि', 'अथवा', 'मोटरसाईकल', 'ब्राउज़िंग', 'डरते', 'गेंदबाज', 'वैध', 'रौंद', 'भद्दा', 'खतम', 'यहां,', 'Taj', 'तैरना', 'परिवर्तित', 'बर्लिन', 'टाँगा', 'जोड़ें।', '368इन', 'गैज़ेटियर', 'खेतों', 'डैस्क', 'श्रीलंका', 'दाम', 'पुरुष', 'ग्रामीण', 'आधिकारिक', 'करके', '(1946)', 'मगर,', 'ढूँढो।', 'नाथा', 'बीवा', 'बोर्डिंग', 'वेश्या', 'ग्रेट', 'स्पर्धा', 'सिरे', 'हो?', 'द्रविड़', 'प्रोटीनों', 'सान्याल', 'प्रदूषित', 'अस्थायी', 'विश्वकोष', 'दिखती', '(harassment)', 'पहुचाते', 'मीराबाई', 'for', 'दुबई', 'सल्फर', 'पड़ते', 'वीडियो', 'सिवाय', 'रखे', 'पोस्ट', 'जानकारी,', 'फर्नांड़ीस', 'प्रदूषक', 'दंत', 'अपडेट', 'तौलिये', 'के.इस', 'भगवान्.”', 'खुशखबर', 'दबाते', 'अदा', 'उड़न', 'युक्ति', 'स्राव', 'चलें', 'पाठक', 'भीग', 'औद्योगिक', 'होतीं', 'बातचीत', 'सरल', 'पूर्वी', 'ऑर्डर', 'भुगत', 'हेल्थ', 'पतियों', 'झूठ', 'वस्तुए', 'गुंबज', 'दिशाओं', 'हुऋ', 'चश्मदीद', 'तेरह', '(शायर)', 'पुकारते', 'भूमिका', 'है.उदाहरण', 'चुनीं,', '१००', 'आधारशिला', 'हवाई', 'बीच', 'चीज़ों', 'विकरणशील', 'कब', 'खरीदी।', 'नेक्टर', 'कमीज़', 'बन्धन', 'अस्तबल', 'बिज़ी', 'सुंदरता', 'एल्गोरिदम', 'मैसाच्युएट्स', 'गयी', '2000में', 'मिक्रोTAC', 'रेखाओं', 'गा', 'पैमाने', 'इश्क', 'निकोबार', 'अनपढ़', 'दिवालिया', 'ए.सी.एन', 'कर्कश', 'तरिकों', 'दें।', 'बधाईंयाँ।', 'सेवाएं', 'बजे', 'नाकामयाब', 'रिसने', 'डऋआंट', 'मुँह', 'बुनी', 'दियें', 'अराजकतावादी', 'विकास', 'जयशंकर', 'खोलो।', 'मल्टीलैटरेशन', 'चलो', 'रहा', 'भौतिकी', 'लिया,', 'एमी,', 'उत्पन्न', 'बढेतरी', 'प्रतीक्षा', 'असामान्य', 'करती', 'हुए,', 'सेलूलर', 'जन-स्वास्थ्य', 'विधायकों', 'भूलना।', 'पीछे-पीछे', 'धोखा', 'जोडके', 'जुड़ने', 'पाठ्य', 'युगान्तरकारी', 'कुपित', 'पकड़ा', 'ला', 'सर्वेक्षण', 'शंकाएं', 'प्रयाग', 'केन्द्रित', 'अधीन', 'ग', 'झिलता', 'तेजड़ियों', 'निर्जलित', '(roadway', 'खतरा', 'नीचे,', 'प्', 'टकरवा', 'पुत्रबधू', '1803', 'अयूब', 'बताए', 'भरी', 'नरंसिह', 'होता।', 'हृदयंगम', 'इनमें', 'तोड', 'बर्तन', 'नाममात्र', 'AvaQaarNaa', 'उनऋ-ऊण्श्छ्ष्-होंने', 'भरी।', 'गणितज्ञ', '२००८', 'जावास्क्रिप्ट', 'वेल्स', 'भाई-चारे', 'जीन्स', 'श्रद्धालुओं', 'करनेवालों', 'ऋषि', 'खाया', 'मॉटिफ', 'दुखी', 'सड़क', 'औपचारिक', 'हिन्द', 'है.इन', 'ठाकुर', 'देखें.', 'दक्षतापूर्वक', 'ओब्सटेट्रीशियन', 'ज़्यादातर', 'दौरान', 'घिराव', 'हौजरी', 'इ-मेल', 'विवेकानुसार', 'ट्रायंगुलर', 'दिखाए', 'लगता', 'जाओगी.”', 'स्वदेशी', 'घोषणापत्र', 'स्थिर', 'कारखानों', 'our', 'थी।', 'जैसे-जैसे', 'नारेबाजी', 'सभ्यता', 'हाटिया', 'विशेषज्ञ', '(granny', 'लेटा', 'तरीकों', 'चादरें', 'गर्मी', 'वादी', 'सीखनी', 'शस्त्रक्रिया', 'हंकाऊ', 'है.रिटायर्ड', 'पनीर', 'बहतर', 'खाज', 'पोंछा।', '1939', 'बादशाहों', 'संबंद्धता', 'तराशना', 'वर्मा', 'सैनिकों', 'बसे।', 'धूल', 'लगा?', 'अक्षय', 'थी', 'भाग', 'साम्रज़्यवाद', 'किसान', 'warming)', 'हुई।', 'बेकार', 'देहाती', 'जैम', '(Intimacy)', 'अल्प', 'प्रतिनिधितऋद्दव', 'नाल', 'अपमानित', 'वंगी', 'पर्वत', 'होली', 'दिखाने', 'तालियां', 'गाडि़यों', 'विधानमंडल', 'हुए)', 'ज़्वालामुखी', 'एक-साथ', 'पकड़नी', 'कृपा-ग्रंथ', 'सुनीये', 'पंक', 'अतीत', 'हुक़्म', 'अचानक', 'ज्होल', 'क्युंकि', 'कसौटी', 'अतिक्रमण', 'रद्द', 'इन्द्र', 'चरण', 'अल्कोहल', 'केशव', 'चतुर्भुज', 'जाँचक', 'आठवाँ', 'श्वेत', 'वाहवाही', 'वायुमंडल', 'से]', 'रोक', '२१', 'भंडारों', 'हूँ.', 'एग्रीगेटर्स', 'लगाया।', '१९४७', 'सम्पूर्ण', 'इटली', 'चाहिए', 'मालिक', 'पंख', '|भाष्;', 'भव्य', 'कौस्ट्स', 'जाकर', 'करीगर', 'गोलार्ध', 'भारतीय', 'दायरे', 'ओक', 'ग़लतियाँ', 'प्रस्ताव', 'है॰', 'पक्ष', 'तरह', 'पदगतियों', 'पारिदाइजा़', 'ऊंचे-ऊंचे', 'लन्च', 'निरूपण', 'नाम', 'निर्णयों', 'युनिसायकल', '14', 'अकेलापन', 'मरना', 'या', 'बीस', 'ऋन', 'फैसल', 'जंबुद्वीप', 'थार', 'किया', 'शहरी', '☻', '63', 'नव्योत्तर', 'अवश्य', 'सदृश', '१९३४', 'प्रासंगिक', '१९९९', 'दुर्धर्ष', 'मर्यादा', 'मुस्लिम', 'सुना', 'संवर्ग', 'मुताबिक', 'पूंजीपतियों', 'पूरा', 'स्कोरर', 'समाहित', 'हर्ज', 'धन्यवाद.', 'बनना', 'और-भी-और', 'नगरपालिकाएं', 'हुई.सन्', 'क़ब्र', 'खारे', 'अग्रिम', 'शक्श', '☺', 'प्रौद्योगिकी', 'इंसान', 'लगभग', 'सांगा', 'चुकें', 'विधियां', 'शोध-समूह', 'पटरी', 'सिल्क', 'चालढाल', 'है”', 'मंडलों', 'अन्दर', 'घोसले', 'साथ।', '97', 'शासी', 'फ्लड', 'बनातीं', 'दिलचस्प', 'श्वास', 'प्रतिशत', 'अदालत', 'व्यर्थ', 'उपबंधित', '१९७७', 'बनाओ”', 'जरूरी', '☻☻', '(1990', 'त्रिभुवनका', 'करोड़', 'जलता', 'बोली,“पर,', 'इंगलिश', 'खाकर', 'हवा', 'हडसन', 'days', '१८', 'दिग्गज', 'महत्ता', 'अलैहि', 'न्यूजप्रिंट', 'पदार्थों', 'नही', 'बॉस्टन', 'वासियों', 'क्रयशक्ति', '“आदमियों', 'ZLफर', '(terabyte))और', 'recent', 'बीयर', 'गुजरना', 'फैदे', '‘सक्सेरिया', 'उपयोगकर्ता', 'श्रेणी:पाकिस्तान', 'करदी।', 'National', 'मानता', 'गुणों', 'छात्र', 'मुंडन्', 'लेंगे', 'वर्णन', 'दोस्त', 'अंतरराष्ट्रीय', 'नर्सरीज़', 'बरबाद', 'मौसम', 'स्वास्थ्य', 'उनपर', 'साँयः', 'कारोबार', 'वरदान', 'टकराव', 'भुजाना', 'बडी', 'ज़हरीले', 'लाए', 'सुंदरवन', 'गेट', 'अन्तर्राष्ट्रीय', 'अधीक', 'तिरूनलवेली', 'परिश्रम', 'शांतिपर्व', 'वाह-वाह!', 'चेहरे', 'सर्वप्रथम', 'रखने', 'अधिकतर', 'उभार', 'लाता', 'ढेर', 'डीमोज', 'पडऋ', 'थे।', 'प्रतिपूर्ति', 'cells)', 'सम्पर्क', 'चाहूंगी,', 'योनियां', 'यत्र-तत्र', 'कुदु', 'फंचाई', 'प्रतिस्थापित', 'अलग-', 'समस्याएँ', 'युक्त', 'विद्यमान', 'नांबियार', 'अग्रदूत', 'गाँधीजी', 'गोरखपुर', 'कीमतें', 'बिस्टर', '(1958)', 'है.ह्यखहृ', 'याद', '(फेमिली)', 'मोहर', 'पकड़े', 'स्मारक', 'नियमों', 'बुलवाई।', 'पीछ', 'देवी', 'पैसा', 'रिजस्ट्रेशन', '0.001', 'आगरा', 'कराते', 'असल', 'प्रांत', 'भगतराम', 'मंत्री', 'गिरावट', 'आया।', 'लने', 'खुले', 'गाँवघर', '(scientific', 'गुरु', 'सिरिंज', 'बिताई।', 'सेवानेपाल', 'आशंका', 'तेल', 'तीनों', 'प्रयोगकर्ताओं', 'बी', 'वितरण', 'विरूद्ध', 'सतह', 'भरना', 'उन्हीं', 'विपदा', 'आएगी', 'अनाज', 'नगर', '1876-77', 'पराजित', 'पार्लियामेंट', 'बिल', 'Zकुछ', 'भटेना', 'रहना', 'इंजन', 'समस्याग्रस्त', 'उनमे', 'मिसाल', 'विज्ञान', 'घटने', 'भला', 'विजयादशमी', 'तीर्थों', 'गुम्बद', 'मोह', 'प्राप्त', 'अतिवादी', 'गुना', 'एबीसीएल', 'तुम!', 'अतिरि>', 'नंदीश', 'ले।', 'सच', 'चौटाल', 'जुटे', 'तरफ', 'कवियों', 'लेरि', 'शासन', 'अतः', 'कितने', 'शौकीन', 'Inc.', 'फारसी', 'ख़रीद', 'वातावण', 'हुआ.', 'एक्सप्रेस', 'लाये', 'खाली', 'अपमान', 'बार-पुणे-संधि-की', 'स्वभाव', 'छोडकर', '1350', 'दिया?', '<start>', 'शराब', 'चलती', 'होस्ट', 'विफल', 'अब्राहम-पथ', 'आयरन', 'डालर', 'मूल्यवान', 'करें।', 'बांध', 'शक्तिशाली', 'जिसमे', 'वैचारिक', 'बाँट', 'किसके', 'बनाने', 'घरवालों', 'ड़ेवेलपिंग', 'निष्फल', '°C', 'फिर', 'क्रम', 'भजन', 'प्रतिवर्ष', 'मीनार', 'दी.अगर', 'गयीं।', '५८०', 'रामलिंग', 'वायुमण्डलीय', 'चौथा', 'छठी', 'लड़की', 'संधियों', 'समिति', 'बरसात', 'आते?', 'भल', '(socioeconomic)', 'उमा', 'खींचा।', 'दुश्मनों', 'ओडिया', 'उत्तराधिकार', 'उत्तरप्रदेश', 'खराबी', 'निकलते', 'है.मादा', 'लूँ।', 'है-लोकप्रिय', '(wood)', 'चलानी', 'नई', 'मंगवाया', 'उद्यानों', 'है।"', 'भाभी', 'कार्य-संचालन', 'विकेट', 'कैंसर', '(extreme', 'व्याख्या', 'पोंछो।', 'जंग', 'निदान', 'पुरातत्व', 'ज़बान', 'चंद', 'पतवार', 'उल्टी', 'ड्रा', 'नासा', 'अशोकवाटिका', 'महाशय', 'भीतर', 'गई।', 'सूरसारावली', 'चुकी', 'चौक', 'स्टानफोर्ड', 'रीति-रिवाजों', 'मित्सुबिशी', 'प्रोपेगंडा', 'उपाय', 'कहती', 'निजी', 'नेत्रहीन', '31', 'मानक', 'अठारह', 'समेत', 'साम्राज़्य', 'लागू', 'मार्च', '(ISBN', 'उज़्ज़्वल', 'रूक', 'लाहौल', 'आते', 'आये', 'तिरूप्परांकुयम', 'पीठे', 'कोऋ', 'करें', 'लगकर', 'मिश्रित', 'गुड़गुड़ा', 'करना', 'मशीन', 'मानस-लंका', '(१६००', 'बनाओगे', 'एच.ई.सी', 'लाते', 'बोल', 'टाटा', '"तीन', 'व्यापारी', 'एल.ई.डी.', 'पूछूँगा।', 'होनेवाले', 'जलमार्ग', 'पाय', 'डाले', 'जाते.', 'मोरक़्को', 'मुशलिस', 'देखना', 'चार्जरों', 'कजा', 'संसदीय', 'प्रदूषण', 'तोड़ो।', 'सिद्वांत', 'कपड़ै', 'उपायों', 'बाइक', 'शिखर', 'अंतरंग', 'पीले', 'पेकिंग', '(Sebaceous', 'बुद्धिमान', 'क्रमिक', 'मंत्रिपरिषद', '19वीं', 'क्रिकेट', 'बेच', 'बुरे', '(Cambrian', '१८८८', 'शाखा-', '(disenfranchisement)', 'यू', 'ढूंढने', 'अवरोधित', 'गेय', 'रूपांतर', 'बैठक', 'बेसब्री', 'विश्व', 'निपटाने', 'समान', 'विकिरण', 'हिंदुस्तानी', 'काली', 'दोनो', 'संस्पर्श', 'सम्भाल', 'महानगर', 'बहुत', 'विशेषाधिकार', 'किता', '(development', 'अवधारण', 'लेखकों', 'उखाड़ने', 'अवयवों', '(Hindustan', 'साधारण', 'अनुपस्थिती', 'डकवर्थ', 'पड़ेता', 'साक्ष्यों', 'ताकतवर', 'हिंदू', 'नदियाँ', 'टीमों', 'व्ययॉ', 'सऋ-ऊण्श्छ्ष्-पषऋ-ऊण्श्छ्ष्-ट', 'संगठन', 'सड़', 'है.राजनीति', 'एप्रोप्रिएशन', 'लेने', 'नवंबर', 'बैठकें', 'हुई', 'शोषण', 'बदलें।', 'सैक्रामेंटो', 'कीजिएगा,', 'सम्रथन', 'आदत', 'किताबें', 'लिंकन', 'रेशम', 'असीमित।', 'डे', 'कीजिएगा', 'WMW', '[o३]', 'मिलनी', 'स्वरों', 'तुमपर', 'प्रतिमा', 'शत्रुओं', 'पीड़ित', 'गंगास्नान', 'निहित', 'रवीन्द्रनाथ', 'दिखाऊँगा', 'वैधानिक', 'निपटारे', 'वफादार', 'झलक', 'पड़नी', 'शिक्षकों', 'कहेगी', 'जीना', 'शैक्षणिक', 'धातुखंड', 'बाध्यकारी', 'सैधांतिक', 'है.वायु', 'आर्ट', 'थें', 'पढ़ाना', 'यहाँ', 'कोक-शोक', 'ढंग', 'चिंता', 'चाबी', 'कॉटन', '266', 'अख़बार', 'अलीगढ', 'सुझाव', 'जमींदारियां', 'गुड़ेगुड़ने', 'प्रारुपों', 'जेल-अधीक्षक', 'घी', 'समुदायों', 'घुटनों', '[जापानी]', 'अधिकारिता', 'नये', 'तुममें', 'आज', 'सच्ची', 'बेहतरीन', 'उद्यान', 'तैवान', 'अधूरी', 'सर्वश्रेष्ठ', 'जल', 'शक़', 'बनावट', 'छाता', 'हीरों', 'लेटी', 'स्थायी,', 'रिर्पोट', 'साथ).मोबाइल', 'छाप', '(स्टोरेज', '1958', 'कॉमिक', 'लंबा-चौड़ा', 'निकालते', '1917', 'का)', 'बरेली', '200', 'जिले', '80', 'परिस्थिति', 'निकाय', 'चूहे', 'प्रतिद्वंद्वी', 'शुक्ल', 'हम', 'दीवार', 'दानवीर-कर्ण', 'शिश्नच्छद', 'इसी', 'वेदान्त', 'नियति', '6', '-झूला', 'कैलेण्डर', 'देखनी', 'तत्त्व', 'लगेगी?', 'खो', 'रहोगे', '(climate', 'हलाँकि', 'सोवियत', 'क्रुद्ध', 'निगम', '\u200eफ़रमाते', 'संबंधियों', 'ड़रबन', '1988', 'न्यायपालिका', 'खयाल', 'समझाना', 'रहूं', 'परंपराओं', 'टोपी', 'आईएमई', '1998', 'जाए।', 'मोर्चे', 'भेड़', 'बेहद', 'पतलून', 'कभिवचनों', 'मुक्तहस्त', 'hO', 'पहेले', 'बलसोर', 'लगाते', 'उतने', 'मूल्य', 'थ्फ्', 'उपदेवताओं', 'प्रजाति', 'गोल', 'विशेषकर', 'वक्र', '1960', 'धोने', 'सक्सेना', 'वजहसे', 'बावजूद', 'अमेरिका', 'बसाये', 'रिपब्लिकन', 'खोज', 'जुड़', 'उत्प्रेरित', 'जीनत', 'जाई', 'सहित', 'हँस', 'मिलेंगीं।', 'युग़्मज', 'करता', 'अमीर', 'निचले', 'प्रतिध्वनि', 'करूंगी।', '(गुजरात)', 'बनाकर', 'पहुंचाना', 'शक्तियाँ', 'कन्याओं', 'बाँटना', 'नकद', 'खिलाना', 'compounds)', 'बताई', 'मजेदार', 'फ़र्निचर', 'दावों', 'चालू', 'हर्षध्वनि)', 'तोर्णा-राज्य', 'कैमरा', 'चियर्स!', 'मुल्कों', 'लगा।', 'नहीँ', 'खोलो!', 'लंपट', 'पालन', 'यदाकदा', 'ठंड', 'अंगरक्षक', 'छाँओं', 'कुंवर', 'मुर्गे', 'पुत्र', 'फीड', '25,980', 'कुल', 'मत्स्य', 'लाइट)', 'बाबूलाल', 'बाधाएं', 'अधिकतम', 'भेज', 'समर्थ', 'कैरियर', 'प्रसन्न', 'समाज', 'हफ़्तों', 'कारणों', 'समपर्क', 'पुलीस', 'ग्राहस्थिक', 'प्रेषित', 'एक्सप्लोरेशन', 'टैक्स', 'भरना।', 'हैः', 'देखा।', 'सहमति', 'भरते', 'स्टेशन', 'पडा।', 'बंटवारे', 'मस्तिष्क', 'नेहरू', 'पुलिस', 'माक्र्सवादी', 'टिहरी', 'निपुण', 'फड़फड़ा', 'तोहफ़ा', 'दृढ़ता', 'सूट', 'ग्रहित', 'हेलन', 'परिपत्र', 'हिन्द-आर्य', 'बोधगम्य', 'वाकर', 'ब्राएन', 'मान्य', 'हिट', 'वक्ररेखी', 'वर्धमान', 'मुश्किल', 'आपत्तिजनक', 'वालं', 'र्थे', 'घूमती', 'हेब्रीयस', 'विशुद्ध', 'दिखा?', 'मजबूत', 'न्यायिक', '1989', 'चीज़ें', 'परिणत', 'द्वीपों', 'बोल्ड', 'नवीन', 'पढ़', 'कराकर', 'चलाया।', 'होता,', 'फैट', 'लंबित', 'खत्म', 'नक्शा', '(greenhouse', 'पिया', 'बुआ-जी', 'सेल्सियस', 'अध्यात्म', 'आपत्ति', 'पंहुचा', '२०५०', 'लाइसेंस', 'अबौद्ध', 'अमेरिकीपन', 'देसाई', 'जानती', 'स्पेस', 'अकेले', 'टल', 'दाभोल', 'तारामंडल।', 'लेकर', '२', 'टूटे', 'सहेलियों', 'पार', 'चुनो।', 'सहउत्पादों', 'कैट”?', 'बेलजियम', 'हजार', 'फौजो', 'कुत्ता', 'पर्यटन', 'अनहोनी', 'टिकट', 'धागे', 'जी।', '(Best', 'देखे', 'अत्यन्त', 'बदले', 'मोहक', 'वर्गो', 'रिज़ल्ट', 'सौहार्दपूर्ण', 'विनोबा', 'हट्', 'वरिष्', 'वासुदेव', 'चीज़', 'निरीक्षक', 'विरोध', 'दृढ़', 'बताते', 'होनी', 'बहुत,', 'पालक', 'दिवसीय', 'घूमते', 'लौटाना', '(retired', 'वायुमंडलीय', 'कार्यकर्ता', 'जनमेजय', 'डिक्शनरी', 'धुएं', 'रनों', 'क-ख-ग-ध', 'बाँध।', 'ऋसकी', 'मारा।', 'bahut', '“हे', 'घंटो', 'मश्हूर', 'टूटू', 'संभालती', 'कहां', 'रखो!', 'कहूँ।', 'उठा', 'अछूता', 'कीर्तन', 'तिलक', 'सुल्तानों', 'छोटी', '...', 'पुरुल', 'ट्राफ़िक', 'बने।', 'दशमी', 'संतुलन', 'सुदार', 'हत्याएँ', '७५०', 'तहत', 'विकासशील', 'ह', 'अभियुक़्तों', 'अव्यवस्थित', 'तकनलाजी', 'मामल्लपुरम', 'आदिम-हिन्द-यूरोपीय', 'गई', 'रक्षक', 'मूल', '१८९५', '११३१', 'निधन', '५/२२४).', 'समझता', 'युवराज', 'कार्यकलाप', 'बज', 'बेटी', 'बुनियादी', 'वारंटी', 'सार्वजनिक', 'गलतियों', 'था.वरन्', 'बुखार', 'झेला', 'मरीज', 'लेख', 'अध्यक्ष/सभापति', 'सुल्तान', 'था.एचयूएम', 'ज्यादा', 'धरती', 'कृतियाँ', 'मौज', 'देंखे', '10वीं', 'चाहिएL', 'अम्रीकी', 'तैरकर', 'आएगा,', 'गुफाएं', 'घटक', 'ग्रह', 'ल्क्ष्य', 'टेकचंद', 'चाहते', 'परब्रह्म', 'भूमिगत', 'सुदृश्य', 'वैसी', 'संवैधानिक', 'यूनाईटेड', 'कूल्हों', 'समझाउँगा।', 'तेज', '(अनुभूति)', 'अंजीर', 'प्रस्तार', 'सोशलिस्ट', 'क्यूंकि', 'भरती', 'राज', 'अस्वीकार', 'राष्ट्रवादी-अलगाववादी', 'षष्ठ', 'हासिल', 'कराता', 'गिटार', 'बारें', 'डी', 'इमारतें', 'दी', 'मिलाते', 'लेकरौ', 'मुसल्मानों', 'आइसोसाइनेट', 'मुय', 'पड़ेगी।', 'चल', 'मध्व', 'हौं', 'खर्च', 'दाय', 'निराश', 'देती', 'गुड़िया', 'पर्स', 'बिल्ली', 'साफ-सुथरे', 'تاج', 'पंद्रह', 'प्रदेशों', 'असत्य-मार्ग', 'कमजोरी', 'निर्णयानुसार', 'यूनाइटेड', 'चौंकाने', 'परेशानियाँ', 'परेशान', 'सेइचो', 'बनवालिया।', 'अर्थव्यवस्था', '१३६६२८८५', 'सन्दर्भों', 'कलकत्ता', 'संकरों', 'पास', 'मुड़े', 'दिया.', 'पुराना', 'मेक्सिको', 'कर्तव्य', 'रंअं', 'बंधे', 'अहोनेन', 'होयसल', 'संपनऋद्दन', 'अड्डे', 'explosions)और', 'काराई', 'सुनाओ।', 'विलम', 'years)से', 'लेबनान', 'साहचर्य', 'याचिकादाता', 'रूसी', 'त्रोपोस्फेरे', 'पैराग्राफ', 'बुलाया', 'उत्तरी', '1927', 'कैंपसका', 'औलियां', 'टाईपिंग', 'ऊंचाई', 'कोलोनियों', '(U.S.', 'लैफ्टिनेंट', 'बचते', 'रहेंगे', 'खुशहाली', 'दांत', 'विजेताओं', 'इंद्र', 'इसका', 'घोषित', 'गहरे', 'तौडैंमडलम', 'बूढ़े', 'वर्षों', 'फायदा', 'जायें', 'अनदेखे', 'temperature', 'रोडिका', 'दर्शनशास्र', 'गुणसूत्र', 'हिन्दू', 'उतनी', 'दवाई', 'हितों', 'प्लायवुड', 'उसे', 'कॉनसर्ट', '(ठहाके)', 'maoM', 'बडऋऋ', 'लोकप्रिय', 'आएँ।', 'हुये।', '(सरहाना', 'उपलब्धियों', 'गंगावतरण', 'न्यायशास्त्र', 'जगा', 'डब्बा', 'दी।', 'आदान-प्रदान', 'नोटस', 'फरार', 'एकेश्वरवाद', 'रचने-के', 'ड़ॉ.देव', 'सांस्कृतिक', 'वापिस', 'टोक्यो', 'टेलीविजन', 'प्यास', '८', 'इस्तेमाल', ',किसी', 'चिड़ियाँ', 'सान्द्रित', 'disease)', 'प्रकरण', 'थूकेगा', 'थे?', 'राष्ट्रपतीय', '90', 'कुसुम', 'मानवो', 'फिब्बि', 'सत्य', 'नंदीकेश्र', 'सबके', 'पढऋने', 'कहा', 'सीप', 'सकने', 'शिक्षित', 'कुत्ते।', 'लिच्छवियो', 'करके,', 'तिवारी', '(अति', 'बज्र', 'गहरी', 'केथोलिक', 'संभावनाओं', 'पुराण', 'कथित', 'थप्पड़', 'कनाडा', 'चार्ल्स', '(religious', 'जाते', 'कुत्ते', 'कालोनी', 'हुकूमत', 'लेथब्रिज', 'पंछी', 'विवादों', 'नकार', 'गिरा', 'अँग्रेजी़:', 'दाहिना', 'वल्लभाचार्य', 'बना।', 'बधाईयाँ।', 'अल्पकाली', 'डा', 'थे.', 'दिन', 'टीवी', 'रोल', 'टाईम', 'साथियों', 'महिला', 'बीकानेर', 'मज़े', 'बढ़ती', 'प्रोपेन', 'बेरूत', 'वल्ली', 'थान', 'बबलगम', 'होयसलों', 'protection', 'यात्रियों', 'न्यूयॉर्क:', 'धीरे', 'महाजनों', 'फय्मेन्ट्स्', 'मायनों', 'अगस्त', 'औरतें”', 'निर्माताओं', 'प्रकीर्णन', 'रिमोट', 'सम्भवतः', 'पत्र', 'खालिस्तान', 'प्रारंभ', 'एड्स', 'चिकित्सकीय', 'गणितीय', 'फ़्रानसीसी', 'PC', 'बौद्ध', 'बीटल्स', 'श्रेणी', 'इंजीनियरिंग', '(वेद)', 'होना', '0.22', 'संगिनी', 'सूखी', 'जलन', 'जीव', 'दिखाते', 'बधिया', 'बॉलीवुड', 'है.ज्यादातर', 'डालीं।', 'अधिकरण', 'Y', 'वार्षिक', 'एटीपी', '11', 'some', 'मिलते', 'पहुंची', 'मां', 'फाइलं', '(National', 'लाई।', 'भारित', 'पत्रिका', 'असंतुलन', 'गुणवत्ता', 'लम्बी', 'दोनों', 'अस्पताल', 'गठन', 'पेन', 'ऐतयार', 'तुरन्त', 'दृढ़तापूर्वक', '(Rosey', 'जेटली', 'सफल', 'भोजन', 'आस्ट्रेलिया', 'रहेंगे।', '५', 'गाँव', 'थी,', 'संयंत्रों', 'लगना', 'हिन्दुस्तान', 'क्रोमोसोमों', 'ग्रन्थ', 'डीज़ल', 'पैर', 'सर्वोत्तम', 'समितियों', 'करनीं', 'कप', 'लंदन', 'लिये', 'नारायण', 'आदम', 'छिड़कता', 'सर्जरी', 'प्रोस्टेट', 'द्रव', 'फायरफाक्स', 'दास', 'हुआ।', 'रन', 'करेंगे।', 'छाया', 'एलसीए', 'आश्चर्यों', 'हैं.ऐसा', 'विवश', 'डिजाइन', 'उपस्थित', 'वंचना', 'बचने', 'टावरों', '1949ः', 'इसने', 'ट्रांस्पोर्ट', 'विलोम', 'गऋ', '45', 'पत्थर', 'संख्या', 'नकारात्मक', 'अंकीय', '“एक', 'जुर्रत', 'झाडियों', 'उपद्रव', 'सरकार', 'करोगे', 'आवाजें', 'बॅटर', 'सदैव', 'धुलाई', 'एकसत्तावादी', 'सुषमा', 'प्रिंसिपल', 'कुछेक', 'सीएफ़डी', 'नियंत्रण', 'बुलन्द', 'मरोडने', 'है?”', 'अनन्त', 'ग्रीक', 'यथापारित', 'आज्ञा', 'layer)', 'नजदीक', 'प्रोतऋ-ऊण्श्छ्ष्-साहन', 'मुकाबले।', 'प्रचलित', 'ह्यबिना', 'ग्लास,', 'तोड़ी', 'पंजाब', 'पकाने', 'राजकुमारों', 'गवा', 'गोली', 'मोडल्स', 'खिड़कियों', 'भेद', 'बाहरी', 'ड्रग्स', 'ब', 'बैंकिंग', 'उत्साहित', 'कत्ल', 'होक्काईदो', 'है.इनका', 'गुदा', 'ग्लोबल', '(आईसीसी)', 'भवन', 'कर्नाटक', 'आया.गौतम', 'आभूषणों', 'अंग्रेजी', 'विदेश', 'अभिलाषा', 'ताकतें', 'डाला', 'गन्ने', 'करूंगुझी', '..भी', 'टूटी', 'रोगी', 'रोकने', 'तंत्र', 'लिए,', 'आपत्ती', 'वल्लभ', 'माईने', '1.75', 'मध्यम', 'प्रक्रियाओं', 'बासित', 'है,', 'आपने', 'सामुदायिक', 'जुड़वा', 'टी.एम.जे', 'हां', 'मुकंकेबाज', 'यंग', 'कालेज', 'मुलाकातें', 'समुंदर', 'सूप', 'फतेहपुर', 'प्रवर्तनीय', 'दुविधा', 'एकत्र', 'नदियों', 'बल', 'Zकिया', 'षड़्यंत्र', 'संगमरमर', 'पश्चिम', '१९०७', 'योग्य', 'गये', 'शोभायमान', 'काल', '1860', 'छिपी', '(counter', 'हटाए', '३-वर्षीय', 'गान', 'मुकाबले', 'शिखरों', 'मित्रों', 'ग्रंथ', 'अंतराल', 'विधान', 'खरीदने', 'कॉम्प्लेक्स', 'शासक', 'पर्याप्त', 'जतींद्र', 'तुमसे', 'हिला', 'भाई', 'मुसलाधार', 'अपवाद', 'वस्त', 'खिलफ', 'प्रयोगों', 'अनुरूप', 'चन्द्रगुप्त', 'संसाधन', 'ताकि', 'सलह', 'पेंटिंग', 'कक्ष', 'बर्न', 'शिल्प', 'परियोजना', 'में।', 'आआ', 'मलनी', 'कदाचित', 'सैय्दों', 'महिलाओं', 'डालने', 'आठवें', 'हुएँ', 'संघर्षरत', 'समर्थन', 'अपनी', 'याकूब', '२५००', 'प्रेमचंद', 'प्रयास', 'पुर', 'आकांक्षी', 'थक़्का', 'नज़र', '"बस', 'भूलती', 'आता।', 'एरिज़ोना', 'गीलीं', 'बावर्ची', 'तोषकाकार', 'इसे', '(महाराष्ट्र', 'करतीं', 'दर्जा', 'की', 'आई', 'दीं।', 'कमीज़ें', 'खुलेआम', 'तोड़ोगे', 'नीले', 'बैठी', 'जातियों', 'हैं.वहां', 'तार', 'सम्बन्ध', 'शरणागत', 'सेवियों', 'इनकार', 'राज्य', 'गरम', 'पढ़ी', 'प्रलय', 'वैशाली', 'स्टालिन', 'कुरुक्षेत्र', 'अंदाज़', 'करवा', 'पहुँचना', 'और', 'बॉस', 'आंकडें', 'अवस्थित', 'प्राथमिकता', 'जयदेव)', 'करदिआ।', 'इनके', 'जमू', 'क्रम.', 'नाप', 'फ्रेंच', '50,000', 'पेशियों', 'बने', 'बढ़ी।', '70', 'उस', 'अनिश्चितताओं', 'सांवली', 'प्रतिबंधों', 'पेस', 'हूँगा', 'करियर', 'पहुँचेगा।', 'परियों', 'क़त्ल', 'युक़्त', 'सूपरमार्केट', 'फेंको।', 'जैसलमेर', 'विशेषज्ञों', 'निभाएगा।', 'तत्पर', 'उतारने', 'खाती', 'बार', 'धुंध', '+', 'अबसे', 'हुनरशुदा', 'ऋनके', 'लिजिए', 'मुखिया', 'नोबल', 'व्यंजन', 'विघटन', 'क्षमता', 'कटाने', 'सहने', 'घायल', 'निशाना', 'दाता', 'सैनिक', 'निकल', 'कट्टंरपंथ', 'रेशेयुक़्त', 'दक्षिणी', 'हिटलर', 'दूर', 'वजनी', 'पड़ोस', 'षेसिडेन्टिअल्', 'चुनावी', 'तैंतीस', 'बोर्ड', 'पऋद्दयास', 'अजीब', 'चुराना', 'बेरों', 'प्रकाशक', 'air', 'न्यायालयों', 'कानून', 'लघु', 'मदनी', 'तालाबों', 'जामिन', 'पचीस', 'भेजा', 'सुनी', 'जिलों', 'संचालन', 'श्रेणी:ताजमहल', 'वाद', 'साथी', 'चट्टान', 'आवाज़', 'फ़ायदा', 'दिया', '(Medieval', 'मैसूर', 'बिताएंगे', 'सैय्यद', 'भारतेन्दु', 'माइक्रो', 'Protocol)पर', 'मुक़्त', 'हिन्द-यूरोपीय', 'हिस्सा', 'बेड़ै', 'वाणी', 'स्वर्ग', 'तेराब्य्ते', 'पुरुषों', 'आएंगे?', 'वी', 'तर', 'भरा', 'सवारी', 'स्थापत्य', 'भागीदारी', 'एंड', 'सिद्धांत', 'अभिलेखक', 'खिलाफ', 'झारखण्ड', 'III', 'शोधों', 'तक,', 'पक्का', 'उ', 'जानता?', 'हाथगाढ़ी.', 'क्योकि', 'बदलाव', 'यही', '3-8204-1217-4', '1903', 'जळ', 'अमूल्य', 'प्रसारित', 'लिया।', 'छोड़ी', 'उपभोकऋ-ऊण्श्छ्ष्-ता', 'दरवाज़े', 'टेलीग्राफ', 'असली', 'जोड़', 'वर्ग', 'फ़्रेंच', 'साईकल', 'सल्लल्लाहु', 'ज़माने', 'पार्टियों', 'करवाने', 'महंत', 'मिचलाना', 'तस्वीरें', 'सांख्यिकी', 'क्रांतिकारी', 'यहां', 'बिक', 'सरीखे', 'बुलाएँगे।', 'सके', 'लाना।', 'कोटा', 'मधुर', 'अपौइंटमेंट', 'अम्ल', 'ठगे', 'संगम', 'रथों', 'अरगंडनल्लुर', 'सेंटर', 'खट्टा', 'कबज़े', 'उलटा', 'करेगी!', 'पश्चात', 'भले', 'दिवाई', 'पॉ', 'बताता', 'मोजिल्ला)', 'जाओगी।', '(रात', 'बगीचे', 'samaga', 'तभी', 'बर्फीला', 'तकनीक', 'काउंटी', 'देखेंगी', 'उठाकर', 'सदस्यता', 'Kasam)', '.बड़ी', 'उल्टा', 'पान', 'दस्ते', 'सिंडिकेशन', 'उड़ते', '(nudity)', 'गाड़ी', 'डेटा', 'खिलाड़ी', 'आज़ादी', 'स्वरूपों', 'ज़रूरी', 'आलू', 'नाइट्रोजन', 'संत', 'था,', 'चिरस्थायी', 'फेंक', 'तैयारी', 'बलराम', 'वर्चस्व', 'लगा', 'पहनने', 'लॅटरी', 'खि

In [101]:
eng_word_2_idx = {word : idx for idx , word in enumerate(vocab_english)}
print(eng_word_2_idx)

{'<pad>': 0, '<UNK>': 1, 'of': 2, 'vishwa': 3, 'not),': 4, 'control': 5, 'cave.': 6, '-pace,': 7, 'morning.': 8, '27': 9, "'sum": 10, 'explain.': 11, 'imposed': 12, 'geypadoan': 13, 'pendulum': 14, 'treaty': 15, 'photosynth,': 16, 'everywhere': 17, 'barabaki': 18, 'brother': 19, 'matter': 20, 'caustic': 21, 'london?': 22, 'bath.': 23, 'identities': 24, 'nice': 25, 'knife': 26, 'run.': 27, 'wine.': 28, 'strange': 29, 'me.': 30, 'rome': 31, 'you': 32, 'traitor.': 33, '“”global': 34, 'terrorists': 35, '1979-80': 36, 'represents': 37, 'drona': 38, 'terrorism.': 39, 'discomfort': 40, 'squirrel': 41, 'lachmi': 42, 'inflict': 43, 'combined': 44, 'highways': 45, 'drinks?': 46, 'infrastructure': 47, 'decorated': 48, '5,00,000': 49, 'mean': 50, 'insurgency': 51, 'customs': 52, 'maulana': 53, 'foreign-made': 54, 'loyalty': 55, 'matter?': 56, 'disappointed.': 57, 'natures': 58, 'rolling': 59, 'earlier.': 60, 'bipin': 61, 'singer': 62, 'visvabharati': 63, 'imperialist': 64, 'japanese.': 65, '265': 66, 'industrial': 67, 'salient': 68, 'pardon': 69, '“”chandravanshi-suryavanshi“”': 70, 'resolutions': 71, 'seek': 72, 'abstract.': 73, 'grand': 74, 'memoirs': 75, '1980s.': 76, '[unclear],': 77, 'mandaley': 78, 'markup': 79, 'steam': 80, 'crudest': 81, 'inevitable': 82, 'flow': 83, 'profession': 84, 'eds.)': 85, 'skies': 86, 'representing': 87, 'contrast': 88, 'courts-': 89, 'helen': 90, 'requested': 91, 'once.': 92, 'timber': 93, 'considered': 94, 'orphan.': 95, 'lecture': 96, '650,000': 97, 'motherland': 98, 'summer.': 99, 'crew': 100, 'least': 101, 'pressure': 102, 'poisoned': 103, 'races': 104, 'mysore': 105, 'ammonia': 106, 'rung': 107, 'golf.': 108, '99,': 109, 'enhancements': 110, 'breakthrough': 111, 'willing': 112, 'everest': 113, 'yields': 114, 'language;': 115, 'privileges': 116, 'ashwin': 117, 'side,': 118, '“if': 119, 'public.': 120, 'presiding': 121, 'tokyo."': 122, 'involvement': 123, '(1946)': 124, 'relevant': 125, '14,000': 126, 'whose': 127, 'situation': 128, 'forehead.': 129, 'resisted': 130, 'properly': 131, 'divided': 132, 'dhrutrashtra': 133, 'nations': 134, 'invention': 135, 'tulsi': 136, 'faces.': 137, 'else': 138, 'allahabad': 139, 'organization(who)': 140, 'for': 141, 'arbitrator': 142, 'padas': 143, '(perspective)': 144, 'decades': 145, 'troops': 146, 'administrative': 147, 'door?': 148, 'context': 149, 'ashtank': 150, 'dense': 151, 'soon.': 152, 'unceremoniously': 153, 'foam': 154, 'thrust': 155, 'udahrano': 156, 'failure,and': 157, '(gujrat)': 158, 'lowering': 159, 'stated': 160, 'amalgamation': 161, 'facade': 162, 's.': 163, '3100-5600': 164, '“design': 165, 'colliery': 166, 'each': 167, 'split': 168, 'returned': 169, 'jaya.': 170, 'deliberately': 171, 'resource,': 172, 'miss': 173, 'abdominal': 174, 'aatre': 175, 'farakka': 176, 'blames': 177, 'ruled': 178, 'ruling': 179, 'coming': 180, 'prince': 181, 'clothes': 182, 'murder': 183, 'bull': 184, 'pace': 185, 'original': 186, 'jahangir': 187, 'girls.': 188, 'dad': 189, '1947.': 190, 'calling': 191, '3,262': 192, 'cute.': 193, 'recorded': 194, 'track': 195, 'resultant': 196, 'nauseous.': 197, 'sweater': 198, 'while': 199, 'intuition': 200, 'like,': 201, 'supposed': 202, 'tall': 203, 'england.': 204, 'sullied': 205, 'circumstances.': 206, 'sang': 207, 'punjab': 208, 'complained': 209, 'dial': 210, 'bill': 211, 'subject,': 212, 'ghosts.': 213, 'hygiene': 214, 'bytes': 215, 'proyog': 216, 'name?': 217, 'carrier': 218, 'gun': 219, 'made.': 220, 'spite': 221, '2004,': 222, 'affiliation': 223, '324[1],': 224, 'game,': 225, 'prospect': 226, 'pallava': 227, 'tanker': 228, 'distant': 229, 'much.': 230, 'darkness': 231, 'expenses.': 232, 'ram': 233, 'definitely!': 234, 'whip': 235, 'big.': 236, 'stomach': 237, 'chief': 238, 'words.': 239, 'comparable': 240, 'servants': 241, 'topic': 242, 'be?': 243, 'runs.': 244, 'form,': 245, 'blue': 246, 'bharatendu': 247, 'friend.': 248, 'advent': 249, 'patterned': 250, '“”your': 251, 'wiped': 252, 'planning': 253, 'restriction': 254, 'samser': 255, 'somebody.': 256, 'wife.': 257, 'surya': 258, 'glum': 259, 'waiting.': 260, 'principles': 261, 'structure': 262, 'drona:': 263, 'mukhlis': 264, 'complexes': 265, '1803': 266, 'peking': 267, 'kuda': 268, 'tokyo,': 269, 'marut-pa': 270, 'sunga,': 271, '1947,': 272, 'scale': 273, 'plant': 274, 'declares': 275, 'four': 276, 'haji': 277, 'typewriter': 278, 'balls.': 279, 'posture': 280, 'religion.': 281, 'unrealistic': 282, 'nevertheless': 283, 'european': 284, 'woke': 285, 'associated': 286, 'requisite': 287, '12th': 288, 'check': 289, 'sanskrit_ocr': 290, 'interfering': 291, 'focus': 292, 'jamshedpur': 293, 'task.': 294, 'produced': 295, 'deposits': 296, 'operate': 297, 'judicial': 298, 'breast': 299, 'positive': 300, 'exposed': 301, 'fed': 302, 'men)': 303, 'plus': 304, 'hit': 305, 'hero': 306, 'dose': 307, 'boars': 308, 'speaking,': 309, 'f)': 310, 'chakrabarti': 311, 'developed': 312, 'aboriginal': 313, 'library': 314, 'bmc,': 315, '6th-7th': 316, 'foundation': 317, '(fehruanulam)': 318, 'cost.': 319, 'our': 320, 'concentrations': 321, 'nepal.': 322, 'censor': 323, 'wrong?': 324, 'fire“”': 325, 'party)can': 326, 'italy.': 327, 'metaphysical': 328, 'english?': 329, 'proceed': 330, 'hair.': 331, 'finally': 332, 'practised': 333, 'carries': 334, 'forts': 335, 'tame.': 336, 'pipe': 337, 'weather': 338, 'daal': 339, 'film': 340, 'work.': 341, 'possibilities': 342, '1939': 343, 'summed': 344, 'calcutta': 345, 'compensation': 346, 'model': 347, 'drinkable.': 348, '[according': 349, 'liturature:': 350, 'british-indian': 351, 'round': 352, 'completely': 353, 'orissa': 354, 'little.': 355, 'expiation': 356, '[if': 357, 'curtailed': 358, '1.because': 359, 'cut': 360, 'sulphide': 361, '224': 362, 'done.': 363, 'messaging': 364, 'hate': 365, 'swollen': 366, 'season': 367, 'now?': 368, 'research': 369, 'europe': 370, 'karunguzhi': 371, 'nothing': 372, 'lahaul': 373, 'way': 374, 'mine': 375, 'nuisance': 376, 'rites': 377, 'indulging': 378, 'waited': 379, 'square': 380, 'diminished': 381, 'manured': 382, 'him?': 383, 'errand': 384, 'world,': 385, 'arising': 386, 'protest': 387, 'lishment': 388, 'disappointment.': 389, 'across.': 390, 'crucifix': 391, 'ultra-left': 392, 'imagine': 393, 'indeed': 394, 'autocracy': 395, 'conquests': 396, 'commercial': 397, 'green': 398, 'foot.': 399, 'kshetrapala': 400, 'digital': 401, 'put': 402, 'arithmetic': 403, 'syed': 404, 'goes,': 405, 'choudhury': 406, 'attitude': 407, 'third': 408, 'invitation.': 409, 'honoured': 410, 'religion,': 411, 'woven,': 412, 'ghat': 413, 'genital': 414, 'should': 415, 'requires': 416, 'sister.': 417, 'voluntary': 418, 'inside.': 419, 'longer': 420, 'exposure': 421, "power's": 422, 'convinience,': 423, 'bihar': 424, 'swear': 425, 'noise': 426, 'bugs': 427, 'browse.': 428, 'wise': 429, 'valid': 430, 'years,': 431, 'ideals': 432, '1850,': 433, 'inquire': 434, 'equal.': 435, 'insulin': 436, 'director-general': 437, 'birthday.': 438, 'loyalty.': 439, 'these?': 440, 'recurring': 441, 'contribute': 442, 'diplomatically': 443, 'arrange': 444, "i've": 445, 'fundamental,': 446, 'factor': 447, 'acute': 448, 'meant': 449, 'guntur': 450, 'preventive': 451, 'island': 452, 'centres': 453, '14': 454, 'reach': 455, 'gradual': 456, 'sprinkles': 457, 'nehru': 458, 'vivan': 459, 'believes': 460, 'devote': 461, 'nimbark,': 462, 'connotation': 463, '63': 464, 'central': 465, 'general,': 466, 'baby.': 467, 'tennis': 468, 'qualify': 469, 'last': 470, 'god': 471, 'amithab': 472, 'doctor': 473, 'filmfare': 474, 'vote': 475, 'reserves': 476, 'saamvedh': 477, 'done': 478, 'talks': 479, 'officer': 480, 'non-partisan': 481, 'justice': 482, 'antarraman': 483, 'one.': 484, 'prestige': 485, 'allowed': 486, 'projected': 487, 'hatred': 488, 'know': 489, 'works.': 490, '1-1/2': 491, 'group,': 492, 'embezzled': 493, 'flooding': 494, '2000,india': 495, 'entrusted': 496, 'arrival': 497, 'release': 498, 'birthday!': 499, 'listening.': 500, 'missed': 501, 'newsprint': 502, 'tablets': 503, 'proteins': 504, 'nice.': 505, 'berating': 506, 'happen': 507, 'danceroom': 508, 'provincial': 509, 'assessment': 510, 'videos,': 511, 'documents.': 512, '97': 513, 'leftist': 514, 'virasikhamani': 515, 'arab': 516, 'chitvan': 517, 'sufficiently': 518, 'galaxy,': 519, 'male-specific': 520, 'shoeing': 521, 'smiled': 522, 'favor': 523, 'soothe': 524, 'laid': 525, 'dominions': 526, 'course,': 527, 'upbraided': 528, 'break': 529, 'man,': 530, 'bridge.': 531, 'dreams': 532, 'angle': 533, 'v': 534, 'successful': 535, 'photograph': 536, 'fewer': 537, 'prompt': 538, 'lone': 539, 'days': 540, 'ideologically': 541, 'happened': 542, 'grooming': 543, 'impact': 544, 'rear': 545, 'usual': 546, 'universityfor': 547, 'roads': 548, 'acknowledgement': 549, 'typical': 550, 'afraid': 551, 'ligament': 552, 'paes': 553, 'recent': 554, 'discourse': 555, 'with?': 556, 'current': 557, 'madhwa': 558, 'lose.': 559, 'rajasthan.': 560, 'duration': 561, '8': 562, 'january': 563, 'dangerous.': 564, 'loaded': 565, 'gallows': 566, 'custom': 567, 'instrument': 568, 'thirsty.': 569, 'counted': 570, 'cult': 571, 'population': 572, 'falls': 573, 'baggage?': 574, 'researches': 575, 'elaborately.': 576, 'dove': 577, 'profit-crazy': 578, 'ventured': 579, 'us?': 580, 'status': 581, 'hungry': 582, 'abcl': 583, 'aligarh,': 584, 'gurus': 585, 'idea.': 586, 'thus': 587, 'manager': 588, 'falls.': 589, 'sit.': 590, 'best,': 591, 'request': 592, 'bit.': 593, 'husband.': 594, 'fostering': 595, 'drink': 596, 'superintentant': 597, 'galaxy': 598, '“now': 599, 'font': 600, 'consulted': 601, 'courses': 602, 'please': 603, 'bank,': 604, 'untouchability': 605, 'taken': 606, 'cells)': 607, 'born': 608, 'outstanding': 609, 'weather."': 610, 'rabindranath': 611, 'oars': 612, 'drawing': 613, '(icc),': 614, 'absolutely': 615, 'murder.': 616, 'pistol': 617, 'sleepy.': 618, 'municipal': 619, 'destruction': 620, '181,278': 621, 'subunits': 622, 'depending': 623, 'maximum': 624, 'dictionary.': 625, 'feeling': 626, '(1958)': 627, 'persian': 628, 'supper.': 629, 'colds': 630, 'depended': 631, 'portraits': 632, '2008.': 633, 'wo': 634, 'brain': 635, 'intends': 636, '0.001': 637, 'shop': 638, 'portuguese': 639, 'doordarshan': 640, 'arzu': 641, 'vidyapathi': 642, '[any]?': 643, 'publisher:': 644, 'shooting': 645, 'ramchandra': 646, 'approximately': 647, 'autism': 648, 'casual': 649, 'drudgery': 650, 'undertook': 651, '“”gamal': 652, 'atharvavedh-': 653, 'villages': 654, 'products': 655, 'gods': 656, 'human': 657, 'districtscomprising': 658, 'nuts.': 659, 'pride': 660, 'station.': 661, 'harichandra': 662, 'manufactures': 663, '1876-77': 664, 'calculate}in': 665, 'supervisor': 666, 'bullet.': 667, 'gloating': 668, 'honest.': 669, 'cultural': 670, 'pertaining': 671, 'syeds': 672, 'future': 673, 'due': 674, 'assent': 675, 'staple': 676, 'jungle': 677, 'pleasure': 678, 'delicate': 679, 'fined': 680, 'orthopaedic': 681, 'weaving': 682, 'dance,': 683, 'zindabad.': 684, 'farmlands': 685, 'wears': 686, 'suicide': 687, 'ceased': 688, 'repeated': 689, 'cancer.': 690, 'poets,': 691, 'pretty.': 692, 'bat)': 693, 'fact': 694, "beatles'": 695, 'feynman': 696, 'tends': 697, 'fit,': 698, 'questions.': 699, 'lesser': 700, 'leaped': 701, '1973': 702, 'sons': 703, 'face.': 704, 'club': 705, 'niche': 706, 'black?': 707, 'realize': 708, 'dais': 709, 'headquartered': 710, 'sadhu': 711, 'year-old': 712, 'sentences': 713, 'ballabhacharya.': 714, 'head?': 715, 'discard': 716, 'wing': 717, 'stingy.': 718, '1350': 719, 'undue': 720, 'mahal': 721, 'go': 722, 'manufacturing': 723, 'clouds': 724, 'staring': 725, 'chalukyas': 726, 'batter': 727, 'intelligence': 728, 'gut': 729, 'epoch-making': 730, 'radio': 731, 'sanskrit-first': 732, 'mahanta': 733, 'fool': 734, 'music,': 735, 'seventh': 736, 'account.': 737, 'followed': 738, 'foreign': 739, 'taila': 740, '1,500': 741, 'schedule': 742, 'forgot': 743, 'hear?': 744, 'exhibition,': 745, '"yes': 746, 'marked': 747, 'quadrangular': 748, 'bonnet': 749, 'leg-spin': 750, 'inflame': 751, 'sluggish': 752, 'disqualified': 753, '1995': 754, 'females': 755, 'like.': 756, 'seats': 757, 'bite': 758, 'hungry.': 759, 'day': 760, 'beauty': 761, 'spurious': 762, 'mix': 763, 'cat?”': 764, 'sugary': 765, 'liquor': 766, 'see.': 767, 'exaggerated': 768, 'hinda': 769, 'bowling.': 770, '1131': 771, '“”agreshvar': 772, "i'll": 773, 'curing': 774, 'couple': 775, 'stand': 776, 'a.m.': 777, 'connection.': 778, 'unapproachable': 779, 'team.': 780, 'directed': 781, 'blasting': 782, 'ulasnagar': 783, 'played': 784, 'catalogue': 785, 'example.': 786, 'supremacy': 787, 'morals': 788, 'exception': 789, 'discussed': 790, 'television.': 791, 'b': 792, 'machine.': 793, 'we': 794, 'elderly': 795, 'prided': 796, 'alcohol.': 797, "she's": 798, 'which': 799, 'stroke': 800, 'expenditures': 801, 'adjacent': 802, '31': 803, 'important.': 804, 'advaita': 805, 'mirzapur,patna,and': 806, 'paragraph': 807, 'countries.': 808, 'story': 809, 'instead': 810, 'april': 811, 'oath': 812, 'considerations': 813, 'trees': 814, 'require': 815, 'bern': 816, 'broaden': 817, 'bring': 818, 'in': 819, 'england': 820, 'bachchan': 821, 'iconography': 822, 'purse.': 823, 'vainglorious': 824, 'devi': 825, 'norms': 826, 'courts': 827, 'exquisitely': 828, 'basit': 829, 'legislatures': 830, 'vegetables': 831, 'electoral': 832, '(the': 833, 'court.': 834, 'hard.': 835, 'ceylon': 836, 'sites': 837, 'acquiring': 838, 'informtion': 839, 'inclined': 840, 'warned': 841, 'u.s.department': 842, 'local': 843, 'regulating': 844, 'visiting': 845, 'terrorism': 846, 'paragraphs': 847, 'adopt': 848, 'attest': 849, 'attractive': 850, 'delisting': 851, 'snowball': 852, 'form': 853, '(choice)': 854, 'st': 855, 'circus': 856, 'narayan': 857, 'abandoned': 858, 'struggled': 859, 'particular': 860, 'behaviour': 861, 'existed.': 862, 'pigeons': 863, 'towards': 864, 'tonnes.': 865, 'bus.': 866, 'gradually': 867, 'script': 868, 'resign': 869, 'janmejay.': 870, 'bombing': 871, 'attract': 872, 'felt': 873, 'reconditioned': 874, 'region': 875, 'w': 876, 'betrayed': 877, 'oxford': 878, 'ownership': 879, 'longest': 880, 'accomplished': 881, 'write': 882, 'infant': 883, '“but,': 884, 'output': 885, '(development': 886, 'bold,': 887, 'elevator': 888, 'robot.': 889, 'account': 890, 'frequently': 891, 'hijri,': 892, 'bending': 893, 'photons': 894, 'sunday?': 895, 'reasonable': 896, 'production': 897, 'secured': 898, 'g.v': 899, 'fat.': 900, 'correlation,': 901, 'khurian': 902, 'manages': 903, 'core': 904, 'arguments': 905, 'melted': 906, 'impass.': 907, 'kinship': 908, 'politics': 909, 'readies': 910, 'cave-temple': 911, 'runs': 912, 'august,': 913, 'fly.': 914, 'milk.': 915, 'suing': 916, 'ink?': 917, 'barmak': 918, 'haste.': 919, 'late': 920, 'conscious': 921, 'attain': 922, 'leaves': 923, 'technological': 924, 'merits': 925, 'self-reliant': 926, 'elastic.': 927, 'do': 928, 'demanding': 929, 'leaf-a': 930, 'outside.': 931, 'zankar': 932, 'stamp': 933, 'salas': 934, '266': 935, 'open': 936, 'everything.': 937, 'tracks.': 938, 'scepticism': 939, 'attracts': 940, 'died.': 941, 'pilot': 942, 'tchub': 943, 'pada': 944, 'ship.': 945, 'thin.': 946, 'bhishma': 947, 'rooms.': 948, 'communitythe': 949, 'seem': 950, 'turkey.': 951, 'harder': 952, 'excuse.': 953, "'re": 954, 'relationship': 955, 'often': 956, 'prescription': 957, "we're": 958, 'convert': 959, 'daughters.': 960, 'netaji': 961, 'stairs': 962, "'ll": 963, 'developmental': 964, '1958': 965, 'post': 966, 'chandra': 967, 'expedient': 968, 'files': 969, 'congratulate': 970, '1917': 971, 'dug': 972, 'recommend': 973, 'gaslight': 974, 'cama': 975, '200': 976, 'wicket.common': 977, 'office.': 978, '80': 979, 'sleeping': 980, 'tiger': 981, 'called': 982, 'motor': 983, 'welcome': 984, 'next-door': 985, 'change': 986, 'complain': 987, 'phone.”': 988, 'viewpoint,during': 989, 'peace.': 990, '6': 991, 'says.': 992, 'pounds': 993, 'ganghasnan': 994, 'hazari': 995, 'muslims': 996, 'keeps': 997, 'slowly?': 998, 'alpa': 999, '3:': 1000, 'jumping': 1001, 'sari': 1002, 'fibbi': 1003, 'fashion': 1004, 'adversely': 1005, 'entrance': 1006, 'hindrance': 1007, 'chewing': 1008, 'measured': 1009, 'examples.': 1010, 'wool.': 1011, 'mother': 1012, 'parturition': 1013, 'jacket.': 1014, 'tickets': 1015, 'appearing': 1016, 'shan': 1017, 'late.': 1018, 'theater': 1019, 'expected': 1020, '1998': 1021, 'cradle.': 1022, 'accounted': 1023, 'grasshoppers': 1024, 'revolution': 1025, 'hens': 1026, 'yesterday!': 1027, 'oblation,': 1028, 'somehow,': 1029, 'belong': 1030, 'cupboards': 1031, 'farms,': 1032, '1960': 1033, 'hokkaido?': 1034, 'lets': 1035, 'bottles': 1036, "akbar's": 1037, 'institution': 1038, 'easy.': 1039, 'risk': 1040, 'carts': 1041, 'fate': 1042, 'south': 1043, "brahma's": 1044, 'honor': 1045, 'offerings': 1046, 'strong': 1047, 'absolute,': 1048, 'tails': 1049, 'yourself.': 1050, 'complexity.': 1051, 'scot': 1052, 'will.': 1053, 'cost?': 1054, 'ch4': 1055, 'thoracic': 1056, 'subba': 1057, 'many': 1058, 'hormonal': 1059, '1980s': 1060, 'extra': 1061, 'kipling': 1062, 'pawns': 1063, 'undertaken': 1064, 'japan': 1065, '[o3]': 1066, 'ten-year-old': 1067, 'golden': 1068, 'harinarayana': 1069, 'yours?': 1070, 'searching': 1071, 'notoriously': 1072, 'films': 1073, 'approaching': 1074, "camera's": 1075, 'beard.': 1076, 'horses': 1077, 'tekchand': 1078, 'anything.': 1079, 'purchases': 1080, 'prior': 1081, 'nida': 1082, 'tribunal': 1083, 'characters': 1084, 'cancel': 1085, 'ocean,second': 1086, 'baseball.': 1087, 'spanish': 1088, '2008,': 1089, 'block': 1090, 'hexafluoride': 1091, 'tolerate.': 1092, 'reeks': 1093, 'up': 1094, 'vivekanand(12th': 1095, 'peek': 1096, '25,980': 1097, 'set': 1098, 'feel': 1099, 'gurudev': 1100, 'specifically': 1101, 'agra': 1102, 'seeds': 1103, 'goal': 1104, '375': 1105, 'p+q': 1106, 'drowsy': 1107, 'spending': 1108, 'then.': 1109, 'cured': 1110, 'meanwhile': 1111, 'company.': 1112, 'advice.': 1113, 'bow': 1114, 'anything?': 1115, 'detachment': 1116, 'chini': 1117, 'trouble,': 1118, 'shouted': 1119, 'female': 1120, 'bhojraj': 1121, 'relations.': 1122, 'meaningless': 1123, 'science,': 1124, 'ranjan': 1125, 'wine': 1126, 'age': 1127, 'dharma': 1128, 'wash': 1129, 'pickpocketing.': 1130, 'tariff': 1131, 'said': 1132, 'trust': 1133, 'yes': 1134, 'changsha': 1135, 'caught': 1136, 'cylset': 1137, 'scarab': 1138, 'increased': 1139, 'ranging': 1140, 'soft-drink': 1141, 'record': 1142, 'navrathris': 1143, 'result': 1144, 'soverign,': 1145, 'destined': 1146, 'me,': 1147, 'utsava-mandapas': 1148, 'agriculture': 1149, '1989': 1150, 'martial': 1151, 'valley.': 1152, 'joined-up': 1153, 'mountain': 1154, 'waterway.': 1155, 'items': 1156, 'dam,and': 1157, 'mauryan': 1158, 'unit': 1159, 'wakes': 1160, 'affronts': 1161, 'arrogant.': 1162, 'furnished': 1163, 'extincted.': 1164, 'era|': 1165, 'mendelian': 1166, 'pradesh': 1167, 'dignity': 1168, 'parking.': 1169, 'performs': 1170, 'anniversary': 1171, 'reality,“”': 1172, 'it)but': 1173, 'into': 1174, 'fig.4': 1175, 'told,': 1176, 'three-letter': 1177, 'severity,causing': 1178, 'parliament.': 1179, 'motifs': 1180, "o'clock.": 1181, 'thing,': 1182, 'shrine-cells': 1183, 'memorable': 1184, 'persons': 1185, 'tumbling': 1186, 'usman': 1187, 'epic.': 1188, 'work,': 1189, 'associations': 1190, 'mucous': 1191, 'calamities': 1192, 'yesterday': 1193, 'bentonite,': 1194, 'medium.': 1195, 'eye,': 1196, 'unconfused': 1197, 'culture': 1198, 'neoproterozoic,': 1199, ',nuclear': 1200, 'development,': 1201, 'launched': 1202, 'eighteen.': 1203, 'greenhouse': 1204, 'brahmaji': 1205, 'explains': 1206, '1991-1992': 1207, 'pitied': 1208, 'gold': 1209, 'move': 1210, 'effect': 1211, 'silence': 1212, 'delivers': 1213, 'quality': 1214, 'negative': 1215, 'nakkarkhana': 1216, 'salary': 1217, 'erijona': 1218, 'everybody': 1219, "vishnu's": 1220, 'staff': 1221, 'summary': 1222, 'ago,': 1223, 'relations': 1224, 'sur': 1225, '138': 1226, 'phoolan': 1227, 'taiwan,': 1228, 'about,': 1229, 'contract': 1230, 'indigo': 1231, 'everyone': 1232, '...': 1233, 'dealing': 1234, 'rosey': 1235, 'low-cost':

In [102]:
hindi_word_2_idx = {word : idx for idx , word in enumerate(vocab_hindi)}
print(hindi_word_2_idx)

{'<pad>': 0, '<start>': 683, '<end>': 5710, 'लेना': 3, 'स्टेडियमों': 4, 'गणेश': 5, 'सेवन,': 6, 'of': 7, 'याचिका': 8, 'भयंदर': 9, 'नाइजीरियाई': 10, 'ट्रेड': 11, 'ऑस्ट्रेलिया': 12, 'conduct)निषिद्ध': 13, 'देकर': 14, '27': 15, 'कुरियना': 16, 'सत्तासीन': 17, 'देखा,': 18, 'शक्तियों': 19, 'सबको': 20, 'समालोचना': 21, 'उठानी': 22, 'पार्टनर': 23, 'भार': 24, 'सोचो': 25, 'नेहरु': 26, 'बतादेना।': 27, 'जनसंख्या': 28, 'आधे': 29, 'क्लब': 30, 'तर्कसंगत': 31, 'चला': 32, 'मिनट': 33, 'साZथ': 34, 'यव': 35, 'महानता': 36, 'सकलेश': 37, 'आकृति': 38, '1979-80': 39, 'प्लान': 40, 'हटा': 41, 'मिलाली': 42, 'जीते': 43, 'गाने': 44, 'बुलाई': 45, 'नन्हाँ': 46, 'संसार': 47, 'मैमोग्राफ': 48, 'cloud)': 49, 'हिलो': 50, 'सिस्टर': 51, 'उस्मान': 52, 'उम्र': 53, 'बल्ख': 54, 'की,': 55, 'हुये': 56, 'मेहराबाकार': 57, 'स्कूल': 58, 'पहुँचा': 59, 'उतरेगा।': 60, 'काउंटर': 61, 'हवाऋ': 62, 'चुना': 63, 'असुरक्षित': 64, 'ब्रोड': 65, 'नियुक्त': 66, 'चाहता।': 67, 'खिलजी': 68, 'कैदी': 69, 'सादा': 70, 'कम्प्यूटर': 71, 'रोना': 72, 'टीम': 73, 'समझदार': 74, 'सपनों': 75, 'आच्छादित': 76, 'है?': 77, 'चलना': 78, 'राजस्थानी': 79, 'सहभागिता': 80, 'जज़िया': 81, '(carcinogen)': 82, 'मंड़पम': 83, 'हें': 84, 'आपसे': 85, 'बनाओ।': 86, 'आज़माती': 87, 'मम्मी-पापा': 88, 'प्रोग्राम': 89, 'डालोगे': 90, 'पसन्द': 91, 'टाइम': 92, 'गतिविधि': 93, 'अथवा': 94, 'मोटरसाईकल': 95, 'ब्राउज़िंग': 96, 'डरते': 97, 'गेंदबाज': 98, 'वैध': 99, 'रौंद': 100, 'भद्दा': 101, 'खतम': 102, 'यहां,': 103, 'Taj': 104, 'तैरना': 105, 'परिवर्तित': 106, 'बर्लिन': 107, 'टाँगा': 108, 'जोड़ें।': 109, '368इन': 110, 'गैज़ेटियर': 111, 'खेतों': 112, 'डैस्क': 113, 'श्रीलंका': 114, 'दाम': 115, 'पुरुष': 116, 'ग्रामीण': 117, 'आधिकारिक': 118, 'करके': 119, '(1946)': 120, 'मगर,': 121, 'ढूँढो।': 122, 'नाथा': 123, 'बीवा': 124, 'बोर्डिंग': 125, 'वेश्या': 126, 'ग्रेट': 127, 'स्पर्धा': 128, 'सिरे': 129, 'हो?': 130, 'द्रविड़': 131, 'प्रोटीनों': 132, 'सान्याल': 133, 'प्रदूषित': 134, 'अस्थायी': 135, 'विश्वकोष': 136, 'दिखती': 137, '(harassment)': 138, 'पहुचाते': 139, 'मीराबाई': 140, 'for': 141, 'दुबई': 142, 'सल्फर': 143, 'पड़ते': 144, 'वीडियो': 145, 'सिवाय': 146, 'रखे': 147, 'पोस्ट': 148, 'जानकारी,': 149, 'फर्नांड़ीस': 150, 'प्रदूषक': 151, 'दंत': 152, 'अपडेट': 153, 'तौलिये': 154, 'के.इस': 155, 'भगवान्.”': 156, 'खुशखबर': 157, 'दबाते': 158, 'अदा': 159, 'उड़न': 160, 'युक्ति': 161, 'स्राव': 162, 'चलें': 163, 'पाठक': 164, 'भीग': 165, 'औद्योगिक': 166, 'होतीं': 167, 'बातचीत': 168, 'सरल': 169, 'पूर्वी': 170, 'ऑर्डर': 171, 'भुगत': 172, 'हेल्थ': 173, 'पतियों': 174, 'झूठ': 175, 'वस्तुए': 176, 'गुंबज': 177, 'दिशाओं': 178, 'हुऋ': 179, 'चश्मदीद': 180, 'तेरह': 181, '(शायर)': 182, 'पुकारते': 183, 'भूमिका': 184, 'है.उदाहरण': 185, 'चुनीं,': 186, '१००': 187, 'आधारशिला': 188, 'हवाई': 189, 'बीच': 190, 'चीज़ों': 191, 'विकरणशील': 192, 'कब': 193, 'खरीदी।': 194, 'नेक्टर': 195, 'कमीज़': 196, 'बन्धन': 197, 'अस्तबल': 198, 'बिज़ी': 199, 'सुंदरता': 200, 'एल्गोरिदम': 201, 'मैसाच्युएट्स': 202, 'गयी': 203, '2000में': 204, 'मिक्रोTAC': 205, 'रेखाओं': 206, 'गा': 207, 'पैमाने': 208, 'इश्क': 209, 'निकोबार': 210, 'अनपढ़': 211, 'दिवालिया': 212, 'ए.सी.एन': 213, 'कर्कश': 214, 'तरिकों': 215, 'दें।': 216, 'बधाईंयाँ।': 217, 'सेवाएं': 218, 'बजे': 219, 'नाकामयाब': 220, 'रिसने': 221, 'डऋआंट': 222, 'मुँह': 223, 'बुनी': 224, 'दियें': 225, 'अराजकतावादी': 226, 'विकास': 227, 'जयशंकर': 228, 'खोलो।': 229, 'मल्टीलैटरेशन': 230, 'चलो': 231, 'रहा': 232, 'भौतिकी': 233, 'लिया,': 234, 'एमी,': 235, 'उत्पन्न': 236, 'बढेतरी': 237, 'प्रतीक्षा': 238, 'असामान्य': 239, 'करती': 240, 'हुए,': 241, 'सेलूलर': 242, 'जन-स्वास्थ्य': 243, 'विधायकों': 244, 'भूलना।': 245, 'पीछे-पीछे': 246, 'धोखा': 247, 'जोडके': 248, 'जुड़ने': 249, 'पाठ्य': 250, 'युगान्तरकारी': 251, 'कुपित': 252, 'पकड़ा': 253, 'ला': 254, 'सर्वेक्षण': 255, 'शंकाएं': 256, 'प्रयाग': 257, 'केन्द्रित': 258, 'अधीन': 259, 'ग': 260, 'झिलता': 261, 'तेजड़ियों': 262, 'निर्जलित': 263, '(roadway': 264, 'खतरा': 265, 'नीचे,': 266, 'प्': 267, 'टकरवा': 268, 'पुत्रबधू': 269, '1803': 270, 'अयूब': 271, 'बताए': 272, 'भरी': 273, 'नरंसिह': 274, 'होता।': 275, 'हृदयंगम': 276, 'इनमें': 277, 'तोड': 278, 'बर्तन': 279, 'नाममात्र': 280, 'AvaQaarNaa': 281, 'उनऋ-ऊण्श्छ्ष्-होंने': 282, 'भरी।': 283, 'गणितज्ञ': 284, '२००८': 285, 'जावास्क्रिप्ट': 286, 'वेल्स': 287, 'भाई-चारे': 288, 'जीन्स': 289, 'श्रद्धालुओं': 290, 'करनेवालों': 291, 'ऋषि': 292, 'खाया': 293, 'मॉटिफ': 294, 'दुखी': 295, 'सड़क': 296, 'औपचारिक': 297, 'हिन्द': 298, 'है.इन': 299, 'ठाकुर': 300, 'देखें.': 301, 'दक्षतापूर्वक': 302, 'ओब्सटेट्रीशियन': 303, 'ज़्यादातर': 304, 'दौरान': 305, 'घिराव': 306, 'हौजरी': 307, 'इ-मेल': 308, 'विवेकानुसार': 309, 'ट्रायंगुलर': 310, 'दिखाए': 311, 'लगता': 312, 'जाओगी.”': 313, 'स्वदेशी': 314, 'घोषणापत्र': 315, 'स्थिर': 316, 'कारखानों': 317, 'our': 318, 'थी।': 319, 'जैसे-जैसे': 320, 'नारेबाजी': 321, 'सभ्यता': 322, 'हाटिया': 323, 'विशेषज्ञ': 324, '(granny': 325, 'लेटा': 326, 'तरीकों': 327, 'चादरें': 328, 'गर्मी': 329, 'वादी': 330, 'सीखनी': 331, 'शस्त्रक्रिया': 332, 'हंकाऊ': 333, 'है.रिटायर्ड': 334, 'पनीर': 335, 'बहतर': 336, 'खाज': 337, 'पोंछा।': 338, '1939': 339, 'बादशाहों': 340, 'संबंद्धता': 341, 'तराशना': 342, 'वर्मा': 343, 'सैनिकों': 344, 'बसे।': 345, 'धूल': 346, 'लगा?': 347, 'अक्षय': 348, 'थी': 349, 'भाग': 350, 'साम्रज़्यवाद': 351, 'किसान': 352, 'warming)': 353, 'हुई।': 354, 'बेकार': 355, 'देहाती': 356, 'जैम': 357, '(Intimacy)': 358, 'अल्प': 359, 'प्रतिनिधितऋद्दव': 360, 'नाल': 361, 'अपमानित': 362, 'वंगी': 363, 'पर्वत': 364, 'होली': 365, 'दिखाने': 366, 'तालियां': 367, 'गाडि़यों': 368, 'विधानमंडल': 369, 'हुए)': 370, 'ज़्वालामुखी': 371, 'एक-साथ': 372, 'पकड़नी': 373, 'कृपा-ग्रंथ': 374, 'सुनीये': 375, 'पंक': 376, 'अतीत': 377, 'हुक़्म': 378, 'अचानक': 379, 'ज्होल': 380, 'क्युंकि': 381, 'कसौटी': 382, 'अतिक्रमण': 383, 'रद्द': 384, 'इन्द्र': 385, 'चरण': 386, 'अल्कोहल': 387, 'केशव': 388, 'चतुर्भुज': 389, 'जाँचक': 390, 'आठवाँ': 391, 'श्वेत': 392, 'वाहवाही': 393, 'वायुमंडल': 394, 'से]': 395, 'रोक': 396, '२१': 397, 'भंडारों': 398, 'हूँ.': 399, 'एग्रीगेटर्स': 400, 'लगाया।': 401, '१९४७': 402, 'सम्पूर्ण': 403, 'इटली': 404, 'चाहिए': 405, 'मालिक': 406, 'पंख': 407, '|भाष्;': 408, 'भव्य': 409, 'कौस्ट्स': 410, 'जाकर': 411, 'करीगर': 412, 'गोलार्ध': 413, 'भारतीय': 414, 'दायरे': 415, 'ओक': 416, 'ग़लतियाँ': 417, 'प्रस्ताव': 418, 'है॰': 419, 'पक्ष': 420, 'तरह': 421, 'पदगतियों': 422, 'पारिदाइजा़': 423, 'ऊंचे-ऊंचे': 424, 'लन्च': 425, 'निरूपण': 426, 'नाम': 427, 'निर्णयों': 428, 'युनिसायकल': 429, '14': 430, 'अकेलापन': 431, 'मरना': 432, 'या': 433, 'बीस': 434, 'ऋन': 435, 'फैसल': 436, 'जंबुद्वीप': 437, 'थार': 438, 'किया': 439, 'शहरी': 440, '☻': 441, '63': 442, 'नव्योत्तर': 443, 'अवश्य': 444, 'सदृश': 445, '१९३४': 446, 'प्रासंगिक': 447, '१९९९': 448, 'दुर्धर्ष': 449, 'मर्यादा': 450, 'मुस्लिम': 451, 'सुना': 452, 'संवर्ग': 453, 'मुताबिक': 454, 'पूंजीपतियों': 455, 'पूरा': 456, 'स्कोरर': 457, 'समाहित': 458, 'हर्ज': 459, 'धन्यवाद.': 460, 'बनना': 461, 'और-भी-और': 462, 'नगरपालिकाएं': 463, 'हुई.सन्': 464, 'क़ब्र': 465, 'खारे': 466, 'अग्रिम': 467, 'शक्श': 468, '☺': 469, 'प्रौद्योगिकी': 470, 'इंसान': 471, 'लगभग': 472, 'सांगा': 473, 'चुकें': 474, 'विधियां': 475, 'शोध-समूह': 476, 'पटरी': 477, 'सिल्क': 478, 'चालढाल': 479, 'है”': 480, 'मंडलों': 481, 'अन्दर': 482, 'घोसले': 483, 'साथ।': 484, '97': 485, 'शासी': 486, 'फ्लड': 487, 'बनातीं': 488, 'दिलचस्प': 489, 'श्वास': 490, 'प्रतिशत': 491, 'अदालत': 492, 'व्यर्थ': 493, 'उपबंधित': 494, '१९७७': 495, 'बनाओ”': 496, 'जरूरी': 497, '☻☻': 498, '(1990': 499, 'त्रिभुवनका': 500, 'करोड़': 501, 'जलता': 502, 'बोली,“पर,': 503, 'इंगलिश': 504, 'खाकर': 505, 'हवा': 506, 'हडसन': 507, 'days': 508, '१८': 509, 'दिग्गज': 510, 'महत्ता': 511, 'अलैहि': 512, 'न्यूजप्रिंट': 513, 'पदार्थों': 514, 'नही': 515, 'बॉस्टन': 516, 'वासियों': 517, 'क्रयशक्ति': 518, '“आदमियों': 519, 'ZLफर': 520, '(terabyte))और': 521, 'recent': 522, 'बीयर': 523, 'गुजरना': 524, 'फैदे': 525, '‘सक्सेरिया': 526, 'उपयोगकर्ता': 527, 'श्रेणी:पाकिस्तान': 528, 'करदी।': 529, 'National': 530, 'मानता': 531, 'गुणों': 532, 'छात्र': 533, 'मुंडन्': 534, 'लेंगे': 535, 'वर्णन': 536, 'दोस्त': 537, 'अंतरराष्ट्रीय': 538, 'नर्सरीज़': 539, 'बरबाद': 540, 'मौसम': 541, 'स्वास्थ्य': 542, 'उनपर': 543, 'साँयः': 544, 'कारोबार': 545, 'वरदान': 546, 'टकराव': 547, 'भुजाना': 548, 'बडी': 549, 'ज़हरीले': 550, 'लाए': 551, 'सुंदरवन': 552, 'गेट': 553, 'अन्तर्राष्ट्रीय': 554, 'अधीक': 555, 'तिरूनलवेली': 556, 'परिश्रम': 557, 'शांतिपर्व': 558, 'वाह-वाह!': 559, 'चेहरे': 560, 'सर्वप्रथम': 561, 'रखने': 562, 'अधिकतर': 563, 'उभार': 564, 'लाता': 565, 'ढेर': 566, 'डीमोज': 567, 'पडऋ': 568, 'थे।': 569, 'प्रतिपूर्ति': 570, 'cells)': 571, 'सम्पर्क': 572, 'चाहूंगी,': 573, 'योनियां': 574, 'यत्र-तत्र': 575, 'कुदु': 576, 'फंचाई': 577, 'प्रतिस्थापित': 578, 'अलग-': 579, 'समस्याएँ': 580, 'युक्त': 581, 'विद्यमान': 582, 'नांबियार': 583, 'अग्रदूत': 584, 'गाँधीजी': 585, 'गोरखपुर': 586, 'कीमतें': 587, 'बिस्टर': 588, '(1958)': 589, 'है.ह्यखहृ': 590, 'याद': 591, '(फेमिली)': 592, 'मोहर': 593, 'पकड़े': 594, 'स्मारक': 595, 'नियमों': 596, 'बुलवाई।': 597, 'पीछ': 598, 'देवी': 599, 'पैसा': 600, 'रिजस्ट्रेशन': 601, '0.001': 602, 'आगरा': 603, 'कराते': 604, 'असल': 605, 'प्रांत': 606, 'भगतराम': 607, 'मंत्री': 608, 'गिरावट': 609, 'आया।': 610, 'लने': 611, 'खुले': 612, 'गाँवघर': 613, '(scientific': 614, 'गुरु': 615, 'सिरिंज': 616, 'बिताई।': 617, 'सेवानेपाल': 618, 'आशंका': 619, 'तेल': 620, 'तीनों': 621, 'प्रयोगकर्ताओं': 622, 'बी': 623, 'वितरण': 624, 'विरूद्ध': 625, 'सतह': 626, 'भरना': 627, 'उन्हीं': 628, 'विपदा': 629, 'आएगी': 630, 'अनाज': 631, 'नगर': 632, '1876-77': 633, 'पराजित': 634, 'पार्लियामेंट': 635, 'बिल': 636, 'Zकुछ': 637, 'भटेना': 638, 'रहना': 639, 'इंजन': 640, 'समस्याग्रस्त': 641, 'उनमे': 642, 'मिसाल': 643, 'विज्ञान': 644, 'घटने': 645, 'भला': 646, 'विजयादशमी': 647, 'तीर्थों': 648, 'गुम्बद': 649, 'मोह': 650, 'प्राप्त': 651, 'अतिवादी': 652, 'गुना': 653, 'एबीसीएल': 654, 'तुम!': 655, 'अतिरि>': 656, 'नंदीश': 657, 'ले।': 658, 'सच': 659, 'चौटाल': 660, 'जुटे': 661, 'तरफ': 662, 'कवियों': 663, 'लेरि': 664, 'शासन': 665, 'अतः': 666, 'कितने': 667, 'शौकीन': 668, 'Inc.': 669, 'फारसी': 670, 'ख़रीद': 671, 'वातावण': 672, 'हुआ.': 673, 'एक्सप्रेस': 674, 'लाये': 675, 'खाली': 676, 'अपमान': 677, 'बार-पुणे-संधि-की': 678, 'स्वभाव': 679, 'छोडकर': 680, '1350': 681, 'दिया?': 682, 'शराब': 684, 'चलती': 685, 'होस्ट': 686, 'विफल': 687, 'अब्राहम-पथ': 688, 'आयरन': 689, 'डालर': 690, 'मूल्यवान': 691, 'करें।': 692, 'बांध': 693, 'शक्तिशाली': 694, 'जिसमे': 695, 'वैचारिक': 696, 'बाँट': 697, 'किसके': 698, 'बनाने': 699, 'घरवालों': 700, 'ड़ेवेलपिंग': 701, 'निष्फल': 702, '°C': 703, 'फिर': 704, 'क्रम': 705, 'भजन': 706, 'प्रतिवर्ष': 707, 'मीनार': 708, 'दी.अगर': 709, 'गयीं।': 710, '५८०': 711, 'रामलिंग': 712, 'वायुमण्डलीय': 713, 'चौथा': 714, 'छठी': 715, 'लड़की': 716, 'संधियों': 717, 'समिति': 718, 'बरसात': 719, 'आते?': 720, 'भल': 721, '(socioeconomic)': 722, 'उमा': 723, 'खींचा।': 724, 'दुश्मनों': 725, 'ओडिया': 726, 'उत्तराधिकार': 727, 'उत्तरप्रदेश': 728, 'खराबी': 729, 'निकलते': 730, 'है.मादा': 731, 'लूँ।': 732, 'है-लोकप्रिय': 733, '(wood)': 734, 'चलानी': 735, 'नई': 736, 'मंगवाया': 737, 'उद्यानों': 738, 'है।"': 739, 'भाभी': 740, 'कार्य-संचालन': 741, 'विकेट': 742, 'कैंसर': 743, '(extreme': 744, 'व्याख्या': 745, 'पोंछो।': 746, 'जंग': 747, 'निदान': 748, 'पुरातत्व': 749, 'ज़बान': 750, 'चंद': 751, 'पतवार': 752, 'उल्टी': 753, 'ड्रा': 754, 'नासा': 755, 'अशोकवाटिका': 756, 'महाशय': 757, 'भीतर': 758, 'गई।': 759, 'सूरसारावली': 760, 'चुकी': 761, 'चौक': 762, 'स्टानफोर्ड': 763, 'रीति-रिवाजों': 764, 'मित्सुबिशी': 765, 'प्रोपेगंडा': 766, 'उपाय': 767, 'कहती': 768, 'निजी': 769, 'नेत्रहीन': 770, '31': 771, 'मानक': 772, 'अठारह': 773, 'समेत': 774, 'साम्राज़्य': 775, 'लागू': 776, 'मार्च': 777, '(ISBN': 778, 'उज़्ज़्वल': 779, 'रूक': 780, 'लाहौल': 781, 'आते': 782, 'आये': 783, 'तिरूप्परांकुयम': 784, 'पीठे': 785, 'कोऋ': 786, 'करें': 787, 'लगकर': 788, 'मिश्रित': 789, 'गुड़गुड़ा': 790, 'करना': 791, 'मशीन': 792, 'मानस-लंका': 793, '(१६००': 794, 'बनाओगे': 795, 'एच.ई.सी': 796, 'लाते': 797, 'बोल': 798, 'टाटा': 799, '"तीन': 800, 'व्यापारी': 801, 'एल.ई.डी.': 802, 'पूछूँगा।': 803, 'होनेवाले': 804, 'जलमार्ग': 805, 'पाय': 806, 'डाले': 807, 'जाते.': 808, 'मोरक़्को': 809, 'मुशलिस': 810, 'देखना': 811, 'चार्जरों': 812, 'कजा': 813, 'संसदीय': 814, 'प्रदूषण': 815, 'तोड़ो।': 816, 'सिद्वांत': 817, 'कपड़ै': 818, 'उपायों': 819, 'बाइक': 820, 'शिखर': 821, 'अंतरंग': 822, 'पीले': 823, 'पेकिंग': 824, '(Sebaceous': 825, 'बुद्धिमान': 826, 'क्रमिक': 827, 'मंत्रिपरिषद': 828, '19वीं': 829, 'क्रिकेट': 830, 'बेच': 831, 'बुरे': 832, '(Cambrian': 833, '१८८८': 834, 'शाखा-': 835, '(disenfranchisement)': 836, 'यू': 837, 'ढूंढने': 838, 'अवरोधित': 839, 'गेय': 840, 'रूपांतर': 841, 'बैठक': 842, 'बेसब्री': 843, 'विश्व': 844, 'निपटाने': 845, 'समान': 846, 'विकिरण': 847, 'हिंदुस्तानी': 848, 'काली': 849, 'दोनो': 850, 'संस्पर्श': 851, 'सम्भाल': 852, 'महानगर': 853, 'बहुत': 854, 'विशेषाधिकार': 855, 'किता': 856, '(development': 857, 'अवधारण': 858, 'लेखकों': 859, 'उखाड़ने': 860, 'अवयवों': 861, '(Hindustan': 862, 'साधारण': 863, 'अनुपस्थिती': 864, 'डकवर्थ': 865, 'पड़ेता': 866, 'साक्ष्यों': 867, 'ताकतवर': 868, 'हिंदू': 869, 'नदियाँ': 870, 'टीमों': 871, 'व्ययॉ': 872, 'सऋ-ऊण्श्छ्ष्-पषऋ-ऊण्श्छ्ष्-ट': 873, 'संगठन': 874, 'सड़': 875, 'है.राजनीति': 876, 'एप्रोप्रिएशन': 877, 'लेने': 878, 'नवंबर': 879, 'बैठकें': 880, 'हुई': 881, 'शोषण': 882, 'बदलें।': 883, 'सैक्रामेंटो': 884, 'कीजिएगा,': 885, 'सम्रथन': 886, 'आदत': 887, 'किताबें': 888, 'लिंकन': 889, 'रेशम': 890, 'असीमित।': 891, 'डे': 892, 'कीजिएगा': 893, 'WMW': 894, '[o३]': 895, 'मिलनी': 896, 'स्वरों': 897, 'तुमपर': 898, 'प्रतिमा': 899, 'शत्रुओं': 900, 'पीड़ित': 901, 'गंगास्नान': 902, 'निहित': 903, 'रवीन्द्रनाथ': 904, 'दिखाऊँगा': 905, 'वैधानिक': 906, 'निपटारे': 907, 'वफादार': 908, 'झलक': 909, 'पड़नी': 910, 'शिक्षकों': 911, 'कहेगी': 912, 'जीना': 913, 'शैक्षणिक': 914, 'धातुखंड': 915, 'बाध्यकारी': 916, 'सैधांतिक': 917, 'है.वायु': 918, 'आर्ट': 919, 'थें': 920, 'पढ़ाना': 921, 'यहाँ': 922, 'कोक-शोक': 923, 'ढंग': 924, 'चिंता': 925, 'चाबी': 926, 'कॉटन': 927, '266': 928, 'अख़बार': 929, 'अलीगढ': 930, 'सुझाव': 931, 'जमींदारियां': 932, 'गुड़ेगुड़ने': 933, 'प्रारुपों': 934, 'जेल-अधीक्षक': 935, 'घी': 936, 'समुदायों': 937, 'घुटनों': 938, '[जापानी]': 939, 'अधिकारिता': 940, 'नये': 941, 'तुममें': 942, 'आज': 943, 'सच्ची': 944, 'बेहतरीन': 945, 'उद्यान': 946, 'तैवान': 947, 'अधूरी': 948, 'सर्वश्रेष्ठ': 949, 'जल': 950, 'शक़': 951, 'बनावट': 952, 'छाता': 953, 'हीरों': 954, 'लेटी': 955, 'स्थायी,': 956, 'रिर्पोट': 957, 'साथ).मोबाइल': 958, 'छाप': 959, '(स्टोरेज': 960, '1958': 961, 'कॉमिक': 962, 'लंबा-चौड़ा': 963, 'निकालते': 964, '1917': 965, 'का)': 966, 'बरेली': 967, '200': 968, 'जिले': 969, '80': 970, 'परिस्थिति': 971, 'निकाय': 972, 'चूहे': 973, 'प्रतिद्वंद्वी': 974, 'शुक्ल': 975, 'हम': 976, 'दीवार': 977, 'दानवीर-कर्ण': 978, 'शिश्नच्छद': 979, 'इसी': 980, 'वेदान्त': 981, 'नियति': 982, '6': 983, '-झूला': 984, 'कैलेण्डर': 985, 'देखनी': 986, 'तत्त्व': 987, 'लगेगी?': 988, 'खो': 989, 'रहोगे': 990, '(climate': 991, 'हलाँकि': 992, 'सोवियत': 993, 'क्रुद्ध': 994, 'निगम': 995, '\u200eफ़रमाते': 996, 'संबंधियों': 997, 'ड़रबन': 998, '1988': 999, 'न्यायपालिका': 1000, 'खयाल': 1001, 'समझाना': 1002, 'रहूं': 1003, 'परंपराओं': 1004, 'टोपी': 1005, 'आईएमई': 1006, '1998': 1007, 'जाए।': 1008, 'मोर्चे': 1009, 'भेड़': 1010, 'बेहद': 1011, 'पतलून': 1012, 'कभिवचनों': 1013, 'मुक्तहस्त': 1014, 'hO': 1015, 'पहेले': 1016, 'बलसोर': 1017, 'लगाते': 1018, 'उतने': 1019, 'मूल्य': 1020, 'थ्फ्': 1021, 'उपदेवताओं': 1022, 'प्रजाति': 1023, 'गोल': 1024, 'विशेषकर': 1025, 'वक्र': 1026, '1960': 1027, 'धोने': 1028, 'सक्सेना': 1029, 'वजहसे': 1030, 'बावजूद': 1031, 'अमेरिका': 1032, 'बसाये': 1033, 'रिपब्लिकन': 1034, 'खोज': 1035, 'जुड़': 1036, 'उत्प्रेरित': 1037, 'जीनत': 1038, 'जाई': 1039, 'सहित': 1040, 'हँस': 1041, 'मिलेंगीं।': 1042, 'युग़्मज': 1043, 'करता': 1044, 'अमीर': 1045, 'निचले': 1046, 'प्रतिध्वनि': 1047, 'करूंगी।': 1048, '(गुजरात)': 1049, 'बनाकर': 1050, 'पहुंचाना': 1051, 'शक्तियाँ': 1052, 'कन्याओं': 1053, 'बाँटना': 1054, 'नकद': 1055, 'खिलाना': 1056, 'compounds)': 1057, 'बताई': 1058, 'मजेदार': 1059, 'फ़र्निचर': 1060, 'दावों': 1061, 'चालू': 1062, 'हर्षध्वनि)': 1063, 'तोर्णा-राज्य': 1064, 'कैमरा': 1065, 'चियर्स!': 1066, 'मुल्कों': 1067, 'लगा।': 1068, 'नहीँ': 1069, 'खोलो!': 1070, 'लंपट': 1071, 'पालन': 1072, 'यदाकदा': 1073, 'ठंड': 1074, 'अंगरक्षक': 1075, 'छाँओं': 1076, 'कुंवर': 1077, 'मुर्गे': 1078, 'पुत्र': 1079, 'फीड': 1080, '25,980': 1081, 'कुल': 1082, 'मत्स्य': 1083, 'लाइट)': 1084, 'बाबूलाल': 1085, 'बाधाएं': 1086, 'अधिकतम': 1087, 'भेज': 1088, 'समर्थ': 1089, 'कैरियर': 1090, 'प्रसन्न': 1091, 'समाज': 1092, 'हफ़्तों': 1093, 'कारणों': 1094, 'समपर्क': 1095, 'पुलीस': 1096, 'ग्राहस्थिक': 1097, 'प्रेषित': 1098, 'एक्सप्लोरेशन': 1099, 'टैक्स': 1100, 'भरना।': 1101, 'हैः': 1102, 'देखा।': 1103, 'सहमति': 1104, 'भरते': 1105, 'स्टेशन': 1106, 'पडा।': 1107, 'बंटवारे': 1108, 'मस्तिष्क': 1109, 'नेहरू': 1110, 'पुलिस': 1111, 'माक्र्सवादी': 1112, 'टिहरी': 1113, 'निपुण': 1114, 'फड़फड़ा': 1115, 'तोहफ़ा': 1116, 'दृढ़ता': 1117, 'सूट': 1118, 'ग्रहित': 1119, 'हेलन': 1120, 'परिपत्र': 1121, 'हिन्द-आर्य': 1122, 'बोधगम्य': 1123, 'वाकर': 1124, 'ब्राएन': 1125, 'मान्य': 1126, 'हिट': 1127, 'वक्ररेखी': 1128, 'वर्धमान': 1129, 'मुश्किल': 1130, 'आपत्तिजनक': 1131, 'वालं': 1132, 'र्थे': 1133, 'घूमती': 1134, 'हेब्रीयस': 1135, 'विशुद्ध': 1136, 'दिखा?': 1137, 'मजबूत': 1138, 'न्यायिक': 1139, '1989': 1140, 'चीज़ें': 1141, 'परिणत': 1142, 'द्वीपों': 1143, 'बोल्ड': 1144, 'नवीन': 1145, 'पढ़': 1146, 'कराकर': 1147, 'चलाया।': 1148, 'होता,': 1149, 'फैट': 1150, 'लंबित': 1151, 'खत्म': 1152, 'नक्शा': 1153, '(greenhouse': 1154, 'पिया': 1155, 'बुआ-जी': 1156, 'सेल्सियस': 1157, 'अध्यात्म': 1158, 'आपत्ति': 1159, 'पंहुचा': 1160, '२०५०': 1161, 'लाइसेंस': 1162, 'अबौद्ध': 1163, 'अमेरिकीपन': 1164, 'देसाई': 1165, 'जानती': 1166, 'स्पेस': 1167, 'अकेले': 1168, 'टल': 1169, 'दाभोल': 1170, 'तारामंडल।': 1171, 'लेकर': 1172, '२': 1173, 'टूटे': 1174, 'सहेलियों': 1175, 'पार': 1176, 'चुनो।': 1177, 'सहउत्पादों': 1178, 'कैट”?': 1179, 'बेलजियम': 1180, 'हजार': 1181, 'फौजो': 1182, 'कुत्ता': 1183, 'पर्यटन': 1184, 'अनहोनी': 1185, 'टिकट': 1186, 'धागे': 1187, 'जी।': 1188, '(Best': 1189, 'देखे': 1190, 'अत्यन्त': 1191, 'बदले': 1192, 'मोहक': 1193, 'वर्गो': 1194, 'रिज़ल्ट': 1195, 'सौहार्दपूर्ण': 1196, 'विनोबा': 1197, 'हट्': 1198, 'वरिष्': 1199, 'वासुदेव': 1200, 'चीज़': 1201, 'निरीक्षक': 1202, 'विरोध': 1203, 'दृढ़': 1204, 'बताते': 1205, 'होनी': 1206, 'बहुत,': 1207, 'पालक': 1208, 'दिवसीय': 1209, 'घूमते': 1210, 'लौटाना': 1211, '(retired': 1212, 'वायुमंडलीय': 1213, 'कार्यकर्ता': 1214, 'जनमेजय': 1215, 'डिक्शनरी': 1216, 'धुएं': 1217, 'रनों': 1218, 'क-ख-ग-ध': 1219, 'बाँध।': 1220, 'ऋसकी': 1221, 'मारा।': 1222, 'bahut': 1223, '“हे': 1224, 'घंटो': 1225, 'मश्हूर': 1226, 'टूटू': 1227, 'संभालती': 1228, 'कहां': 1229, 'रखो!': 1230, 'कहूँ।': 1231, 'उठा': 1232, 'अछूता': 1233, 'कीर्तन': 1234, 'तिलक': 1235, 'सुल्तानों': 1236, 'छोटी': 1237, '...': 1238, 'पुरुल': 1239, 'ट्राफ़िक': 1240, 'बने।': 1241, 'दशमी': 1242, 'संतुलन': 1243, 'सुदार': 1244, 'हत्याएँ': 1245, '७५०': 1246, 'तहत': 1247, 'विकासशील': 1248, 'ह': 1249, 'अभियुक़्तों': 1250, 'अव्यवस्थित': 1251, 'तकनलाजी': 1252, 'मामल्लपुरम': 1253, 'आदिम-हिन्द-यूरोपीय': 1254, 'गई': 1255, 'रक्षक': 1256, 'मूल': 1257, '१८९५': 1258, '११३१': 1259, 'निधन': 1260, '५/२२४).': 1261, 'समझता': 1262, 'युवराज': 1263, 'कार्यकलाप': 1264, 'बज': 1265, 'बेटी': 1266, 'बुनियादी': 1267, 'वारंटी': 1268, 'सार्वजनिक': 1269, 'गलतियों': 1270, 'था.वरन्': 1271, 'बुखार': 1272, 'झेला': 1273, 'मरीज': 1274, 'लेख': 1275, 'अध्यक्ष/सभापति': 1276, 'सुल्तान': 1277, 'था.एचयूएम': 1278, 'ज्यादा': 1279, 'धरती': 1280, 'कृतियाँ': 1281, 'मौज': 1282, 'देंखे': 1283, '10वीं': 1284, 'चाहिएL': 1285, 'अम्रीकी': 1286, 'तैरकर': 1287, 'आएगा,': 1288, 'गुफाएं': 1289, 'घटक': 1290, 'ग्रह': 1291, 'ल्क्ष्य': 1292, 'टेकचंद': 1293, 'चाहते': 1294, 'परब्रह्म': 1295, 'भूमिगत': 1296, 'सुदृश्य': 1297, 'वैसी': 1298, 'संवैधानिक': 1299, 'यूनाईटेड': 1300, 'कूल्हों': 1301, 'समझाउँगा।': 1302, 'तेज': 1303, '(अनुभूति)': 1304, 'अंजीर': 1305, 'प्रस्तार': 1306, 'सोशलिस्ट': 1307, 'क्यूंकि': 1308, 'भरती': 1309, 'राज': 1310, 'अस्वीकार': 1311, 'राष्ट्रवादी-अलगाववादी': 1312, 'षष्ठ': 1313, 'हासिल': 1314, 'कराता': 1315, 'गिटार': 1316, 'बारें': 1317, 'डी': 1318, 'इमारतें': 1319, 'दी': 1320, 'मिलाते': 1321, 'लेकरौ': 1322, 'मुसल्मानों': 1323, 'आइसोसाइनेट': 1324, 'मुय': 1325, 'पड़ेगी।': 1326, 'चल': 1327, 'मध्व': 1328, 'हौं': 1329, 'खर्च': 1330, 'दाय': 1331, 

In [103]:
def word_to_number(sentance , vocab):
  value = []
  for i in sentance:
    value.append(vocab[i])
  return value

In [104]:
word_to_number(["reminded" , "and" , "in"] , eng_word_2_idx)

[7990, 9546, 819]

In [105]:
# ["English"] , df_subset["hindi"]

In [106]:
temp_for_eng = []
temp_for_hindi = []
for i , j in zip(df_subset["English"] , df_subset["Hindi"]):
  temp_for_eng.append(word_to_number(i , eng_word_2_idx))
  temp_for_hindi.append(word_to_number(j , hindi_word_2_idx))


# print(temp_for_eng)
df_subset["English"] = temp_for_eng
df_subset["Hindi"] = temp_for_hindi

/tmp/ipykernel_1805/3841854393.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_subset["English"] = temp_for_eng
/tmp/ipykernel_1805/3841854393.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_subset["Hindi"] = temp_for_hindi

In [107]:
df_subset["English"][100]
df_subset["Hindi"][100]

[683, 9800, 1355, 10181, 1183, 5548, 5710]

In [108]:
df_subset.head()

  English              Hindi
0  [2927]  [683, 2071, 5710]
1  [7586]  [683, 2706, 5710]
2  [7586]  [683, 9364, 5710]
3  [7586]  [683, 9728, 5710]
4  [1949]  [683, 6902, 5710]

In [109]:
# from torch.nn.utils.rnn import pad_sequence

# padded = pad_sequence(
#     sequences,
#     batch_first=True,
#     padding_value = eng_word_2_idx["<PAD>"]
# )

In [110]:
from torch.utils.data import DataLoader , Dataset

In [111]:
class dataset(Dataset):
  def __init__(self , df):
    self.x = df["English"]
    self.y = df["Hindi"]

    self.x = torch.tensor(self.x , dtype=torch.float)
    self.y = torch.tensor(self.y , dtype=torch.float)

  def __len__(self):
    return len(self.x)
  def __getitem__(self , index):

    return self.x[index] , self.y[index]

In [112]:
from torch.utils.data import DataLoader , Dataset
import torch

class dataset(Dataset):
  def __init__(self , df):
    self.x = df["English"].tolist()
    self.y = df["Hindi"].tolist()

  def __len__(self):
    return len(self.x)

  def __getitem__(self , index):
    return torch.tensor(self.x[index] , dtype=torch.long) , torch.tensor(self.y[index] , dtype=torch.long)

In [113]:
from torch.nn.utils.rnn import pad_sequence
import torch

PAD_IDX = 0

def collate_fn(batch):

    src = [torch.tensor(x[0]) for x in batch]
    trg = [torch.tensor(x[1]) for x in batch]

    src = pad_sequence(
        src,
        batch_first=True,
        padding_value=PAD_IDX
    )

    trg = pad_sequence(
        trg,
        batch_first=True,
        padding_value=PAD_IDX
    )

    return src, trg

In [114]:
train_dataset = dataset(df_subset)
dataLoader = DataLoader(train_dataset , batch_size=32 , shuffle=True , collate_fn=collate_fn)

In [115]:
for i , (m, n) in enumerate(dataLoader):
  print(m.size())
  if i == 5 : break

torch.Size([32, 29])
torch.Size([32, 58])
torch.Size([32, 27])
torch.Size([32, 60])
torch.Size([32, 47])
torch.Size([32, 37])

/tmp/ipykernel_1805/3754108929.py:8: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  src = [torch.tensor(x[0]) for x in batch]
/tmp/ipykernel_1805/3754108929.py:9: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  trg = [torch.tensor(x[1]) for x in batch]

In [116]:
class Encoder(nn.Module):
  def __init__(self , vocab_size):
    super().__init__()
    self.emb = nn.Embedding(vocab_size , 500)
    self.GRU = nn.GRU(500 , 200 , 3 , batch_first=True)

  def forward(self , x):
    emb = self.emb(x)
    output , hidden = self.GRU(emb)
    return hidden

In [117]:
class Decoder(nn.Module):
  def __init__(self , vocab_size):
    super().__init__()
    self.emb = nn.Embedding(vocab_size , 500)
    self.gru = nn.GRU(500 , 200 , 2 , batch_first=True)
    self.fc = nn.Linear(200 , vocab_size)

  def forward(self , prev_prediction , hidden):
    emb = self.emb(prev_prediction)
    output , hidden = self.gru(emb , hidden)
    prediction = self.fc(output)
    return prediction , hidden

In [118]:
len(vocab_english)

10377

In [136]:
class Seq2Seq(nn.Module):
  def __init__(self , vocab_english , vocab_hindi):
    super().__init__()
    self.encoder = Encoder(len(vocab_english))
    self.decoder = Decoder(len(vocab_hindi))

  def forward(self , english_src , hindi_target):
    hidden = self.encoder(english_src)
    decoder_input = hindi_target[: , 0]

    predictions = []

    target_len = hindi_target.shape[1]

    for t in range(1, target_len):

      prediction , hidden = self.decoder(decoder_input , hidden)
      predictions.append(prediction)

      teacher_forcing_ratio = 0.7
      teacher_force = random.random() < teacher_forcing_ratio

      if teacher_force:
        decoder_input = hindi_target[: , t]
      else:
        decoder_input = prediction.argmax(dim=1)

    predictions = torch.stack(predictions, dim=1)
    return predictions